<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Hafiz Arslan Amjad">
<meta name="dcterms.date" content="2026-07-17">

<title>Structuring Probability Problem – Mathematical Understanding</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c98d9d0b3b0a085d3ddf71e6e91476d8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Mathematical Understanding</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Articles</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/hafizarslanamjad/mathematical-understanding"> <i class="bi bi-github" role="img" aria-label="GitHub repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#from-210-times-to-210-complete-probability-trials" id="toc-from-210-times-to-210-complete-probability-trials" class="nav-link" data-scroll-target="#from-210-times-to-210-complete-probability-trials"><span class="header-section-number">1</span> From “210 Times” to 210 Complete Probability Trials</a></li>
  <li><a href="#determining-the-meaning-and-unit-of-the-answer" id="toc-determining-the-meaning-and-unit-of-the-answer" class="nav-link" data-scroll-target="#determining-the-meaning-and-unit-of-the-answer"><span class="header-section-number">2</span> Determining the Meaning and Unit of the Answer</a></li>
  <li><a href="#numerical-commutativity-and-the-conceptual-roles-of-the-factors" id="toc-numerical-commutativity-and-the-conceptual-roles-of-the-factors" class="nav-link" data-scroll-target="#numerical-commutativity-and-the-conceptual-roles-of-the-factors"><span class="header-section-number">3</span> Numerical Commutativity and the Conceptual Roles of the Factors</a></li>
  <li><a href="#why-dividing-210-by-7-requires-an-explanation" id="toc-why-dividing-210-by-7-requires-an-explanation" class="nav-link" data-scroll-target="#why-dividing-210-by-7-requires-an-explanation"><span class="header-section-number">4</span> Why Dividing 210 by 7 Requires an Explanation</a></li>
  <li><a href="#fractional-scaling-as-broadcasting-across-the-210-trials" id="toc-fractional-scaling-as-broadcasting-across-the-210-trials" class="nav-link" data-scroll-target="#fractional-scaling-as-broadcasting-across-the-210-trials"><span class="header-section-number">5</span> Fractional Scaling as Broadcasting Across the 210 Trials</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Structuring Probability Problem</h1>
<p class="subtitle lead">Fractions Needed for Probability</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Hafiz Arslan Amjad </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 17, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="introduction">Introduction</h2>
<p>Consider a spinner divided into seven equally likely regions. Four regions contain an elephant, two contain a mouse, and one contains a monkey. The learner is asked to predict how many times the spinner will land on an elephant if it is spun 210 times.</p>
<div id="fig-spinner-problem" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-spinner-problem-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/spinner-probability-problem.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-spinner-problem-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: A probability problem asking for the predicted number of elephant outcomes in 210 spins.
</figcaption>
</figure>
</div>
<p>A conventional solution begins by finding the probability of landing on an elephant:</p>
<p><span class="math display">\[
P(\text{elephant})=\frac{4}{7}.
\]</span></p>
<p>It then multiplies this probability by the number of spins:</p>
<p><span class="math display">\[
210\times\frac47=120.
\]</span></p>
<p>The predicted answer is therefore written as <span class="math inline">\(120\)</span> times. From the perspective of computation, the solution appears complete. The probability has been identified, the multiplication has been performed, and the correct numerical result has been obtained. Yet the shortness of the calculation conceals nearly all the interpretive and relational work that makes it meaningful. For example, why can a number that counts spins be multiplied by a fraction constructed from regions? What relationship allows the internal structure of one spinner to predict a result across 210 separate trials? Why does the denominator <span class="math inline">\(7\)</span>, which initially counts regions, later appear to divide a number <span class="math inline">\(210\)</span> that counts spins? What kind of quantity is <span class="math inline">\(120\)</span> produced by the multiplication, and how should the learner determine the unit or descriptive label attached to the answer? These questions surrounding are real mathematics and they concern the mental structure that must exist before the calculation can be understood as a solution.</p>
<p>The initial step in solving mathematical problems is to determine the roles of symbols or quantities being presented. For example, the role of number <span class="math inline">\(7\)</span> is to initially count all equally likely regions in one spin. The number <span class="math inline">\(4\)</span> counts the regions that produce the desired result. The fraction <span class="math inline">\(\frac47\)</span> expresses the probability of an elephant result on one complete trial. The number <span class="math inline">\(210\)</span> counts how many times that trial is repeated. The final number <span class="math inline">\(120\)</span> represents the expected, rather than guaranteed, number of elephant outcomes.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Presented information</th>
<th>Role in the probability model</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Seven equal regions</td>
<td>The complete set of equally likely outcomes for one spin</td>
</tr>
<tr class="even">
<td>Four elephant regions</td>
<td>The favorable outcomes within that set</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\frac47\)</span></td>
<td>The probability of an elephant result on one spin</td>
</tr>
<tr class="even">
<td>One spin</td>
<td>One complete probability trial</td>
</tr>
<tr class="odd">
<td>210 spins</td>
<td>The number of times the trial is repeated</td>
</tr>
<tr class="even">
<td>120</td>
<td>The expected number of elephant outcomes</td>
</tr>
</tbody>
</table>
<p>After, these roles have been identified, the relationship between quantities must be determined. Role assignment tells us what each component means; relational integration tells us why the components belong together. The seven regions and the 210 spins are not instances of the same object. At the start of the problem, these two objects or quantities are unrelated since one quantity describes the internal possibility structure of a single trial, while the other describes how many times that trial is performed. The fraction <span class="math inline">\(\frac47\)</span> connects them, but this connection must be constructed rather than assumed.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    A["7 equally likely regions"] --&gt; B["4 elephant regions"]
    B --&gt; C["One-spin probability: 4/7"]
    C --&gt; D["210 repeated spins"]
    D --&gt; E["Expected elephant count"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>The movement represented in this diagram is compressed into the expression</p>
<p><span class="math display">\[
210\times\frac47.
\]</span></p>
<p>This article reconstructs the hidden thought process through five connected realizations. It begins by examining how the phrase “210 times” must be interpreted as 210 complete probability trials. It then investigates how the learner can determine what kind of quantity the answer represents and why the result must retain a meaningful descriptive unit. The third section distinguishes the numerical commutativity of multiplication from the different conceptual roles played by the factors. The fourth examines what must be established before dividing <span class="math inline">\(210\)</span> by <span class="math inline">\(7\)</span> in order to be interpreted as forming groups of trials. The final section expands the compact multiplication into repeated expected contributions, showing how <span class="math inline">\(\frac47\)</span> can be understood as being applied across all 210 trials.</p>
<p>As we know that, the spinner contains seven equally likely regions, four of which contain an elephant. Therefore,</p>
<p><span class="math display">\[
P(\text{elephant on one spin})
=
\frac{\text{number of elephant regions}}
{\text{total number of equally likely regions}}
=
\frac47.
\]</span></p>
<p>Due to its distinct role, the number <span class="math inline">\(7\)</span> is part of structure of the problem that counts the equally likely regions available during one trial. The <span class="math inline">\(210\)</span> in statement “spin the spinner 210 times” in its original verbal form, however, describes only how many times an action will be performed. Moreover, the number <span class="math inline">\(210\)</span> is not part of the structure of the problem that forms the region. Because these numbers belong to different structures therefore this makes them different objects and no direct relationship between them should yet be assumed.</p>
<p><span class="math display">\[
\text{one complete spin}
\longrightarrow
\text{one of seven equally likely regions}.
\]</span></p>
<p><span class="math display">\[
\text{one complete spin}
\longrightarrow
\text{repeated 210 times}.
\]</span></p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    A["One complete spin"] --&gt; B["7 possible regions"]
    A --&gt; C["Repeated 210 times"]
    B --&gt; D["4 elephant regions"]
    D --&gt; E["Elephant probability"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Therefore, before the learner can understand the expression.</p>
<p><span class="math display">\[
210\times\frac47,
\]</span></p>
<p>the phrase “210 times” must be reorganized mentally as a collection of “210 complete probability trials”.</p>
</section>
<section id="from-210-times-to-210-complete-probability-trials" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="from-210-times-to-210-complete-probability-trials"><span class="header-section-number">1</span> From “210 Times” to 210 Complete Probability Trials</h2>
<p>In terms of probability, the meaning of one complete spin is one complete trial. Calling the spin as complete does not mean that all seven regions are visited during that spin. Instead, a single spin actually lands on only one region and each new spin begins with the complete set of seven possible regions available to it. One of those possible regions will become the observed result of the spin. For example, the first spin or trial has seven possible regions. After it has finished, the second spin once again has the same seven possible regions. The same possibility structure is recreated for the third spin and continues to be recreated throughout the experiment. The <span class="math inline">\(210\)</span> spins can therefore be represented as</p>
<p><span class="math display">\[
210\text{ spins}
=
\underbrace{
1\text{ complete trial}
+
1\text{ complete trial}
+
\cdots
+
1\text{ complete trial}
}_{210\text{ complete trials}}.
\]</span></p>
<p>If we instead talk about fractions, then each trial would then be translated to one complete whole and hence the <span class="math inline">\(210\)</span> trials are interpretated as <span class="math inline">\(210\)</span> wholes. Therefore, each spin is one complete trial in terms of probability experiment and each trial is one whole in terms of fractions.</p>
<p>If we now shift our focus towards the numerator <span class="math inline">\(4\)</span> and denominator <span class="math inline">\(7\)</span> we must note that they both count regions:</p>
<p><span class="math display">\[
\frac{4\text{ elephant regions}}
{7\text{ total regions}}.
\]</span></p>
<p>The fraction is therefore dimensionless in the numerical sense because it compares a count of regions with another count of regions. Semantically, however, it preserves a classification relationship: four members of the complete set of seven possible regions belong to the elephant category.</p>
<p>Morevoer, the fraction <span class="math inline">\(210\times\frac47,\)</span> becomes a probability because one spin selects one of those seven equally likely regions. This selection mechanism supplies the relationship between the physical spinner and the result of a trial:</p>
<p><span class="math display">\[
\begin{aligned}
&amp;\text{one spin selects one region},\\
&amp;\text{four of the seven possible regions contain elephants},\\
&amp;\therefore P(\text{elephant on one spin})=\frac47.
\end{aligned}
\]</span></p>
<p>Without the relationship “one spin selects one region,” the fraction <span class="math inline">\(\frac47\)</span> would describe only the visible composition of the spinner. It becomes a statement about the possible result of a trial because the action of spinning connects the set of regions to the outcome that will be observed. The reasoning has therefore passed through several related but distinct objects:</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    A["Spinner"] --&gt; B["7 equal regions"]
    B --&gt; C["4 elephant regions"]
    C --&gt; D["Probability 4/7"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>The spinner is the physical object. Its seven regions form the complete possibility structure. Four regions form the favorable part of that structure. Because a spin selects one region, the favorable-to-total relationship becomes the probability of an elephant outcome on one trial. The objects differ, but their relationships integrate them into one model.</p>
<p>Once <span class="math inline">\(\frac47\)</span> has been established as the probability governing one complete spin, the number <span class="math inline">\(210\)</span> can enter the same relational structure. Each of the 210 spins is a new performance of the same experiment. The same spinner is used, the same seven possible regions are available, and the same four regions produce an elephant result. Consequently, the probability <span class="math inline">\(\frac47\)</span> applies to each complete trial:</p>
<p><span class="math display">\[
\begin{aligned}
\text{spin }1 &amp;: P(\text{elephant})=\frac47,\\
\text{spin }2 &amp;: P(\text{elephant})=\frac47,\\
\text{spin }3 &amp;: P(\text{elephant})=\frac47,\\
&amp;\ \vdots\\
\text{spin }210 &amp;: P(\text{elephant})=\frac47.
\end{aligned}
\]</span></p>
<p>The number <span class="math inline">\(210\)</span> and the probability <span class="math inline">\(\frac47\)</span> can now be combined because the relationship between them has been established. The number <span class="math inline">\(210\)</span> counts complete trials, while <span class="math inline">\(\frac47\)</span> describes the probability associated with each of those trials. The expression <span class="math inline">\(210\times\frac47\)</span> therefore does not arise merely because both numbers are present in the question. It arises because one probability model is repeatedly applied across a collection of 210 complete trials. One way to expose the structure compressed by multiplication is to expand it as repeated addition:</p>
<p><span class="math display">\[
\underbrace{
\frac47+\frac47+\cdots+\frac47
}_{210\text{ expected contributions}}.
\]</span></p>
<p>This expansion must be interpreted carefully. It does not claim that one observed spin produces <span class="math inline">\(\frac47\)</span> of an elephant outcome. A physical spin produces either an elephant result or a non-elephant result. The fraction <span class="math inline">\(\frac47\)</span> describes the expected contribution of one spin when the experiment is considered across repeated performances. Multiplication accumulates those expected contributions across the 210 trials. The complete relational path can now be represented as follows:</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    A["4 of 7 regions are elephants"] --&gt; B["Probability on one spin: 4/7"]
    B --&gt; C["Same model for every trial"]
    C --&gt; D["210 complete trials"]
    D --&gt; E["Accumulate expected contributions"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>The transformation of “210 times” into 210 complete probability trials is therefore not a cosmetic change in vocabulary. It assigns <span class="math inline">\(210\)</span> to the mathematical object upon which the probability model operates. Before this transformation, <span class="math inline">\(210\)</span> is merely a count of repeated actions. After it, <span class="math inline">\(210\)</span> represents a collection of trials, each governed by the same probability relationship. The short calculation $ 210$ is the final compression of this reasoning. Its conceptual foundation is the longer relational statement:</p>
<p><span class="math display">\[
\begin{aligned}
&amp;\text{Four of seven equally likely regions contain elephants}\\
&amp;\longrightarrow P(\text{elephant on one complete spin})=\frac47\\
&amp;\longrightarrow \text{the same probability governs each repeated spin}\\
&amp;\longrightarrow \text{there are 210 complete spins}\\
&amp;\longrightarrow \text{accumulate 210 expected contributions of }\frac47.
\end{aligned}
\]</span></p>
<p>Until these relationships have been constructed, <span class="math inline">\(210\)</span> and <span class="math inline">\(\frac47\)</span> are merely two quantities appearing in the same problem. Once their roles have been assigned and relationally integrated, their multiplication expresses a coherent probability model.</p>
</section>
<section id="determining-the-meaning-and-unit-of-the-answer" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="determining-the-meaning-and-unit-of-the-answer"><span class="header-section-number">2</span> Determining the Meaning and Unit of the Answer</h2>
<p>Once the relationship between <span class="math inline">\(210\)</span> and <span class="math inline">\(\frac47\)</span> has been constructed, the learner can understand why these quantities are multiplied. However, knowing why multiplication is required does not yet tell us what the product represents. The calculation</p>
<p><span class="math display">\[
210\times\frac47=120
\]</span></p>
<p>produces the number <span class="math inline">\(120\)</span>, but a number by itself does not identify the object or quantity that has been calculated. The same number could represent <span class="math inline">\(120\)</span> spins, <span class="math inline">\(120\)</span> elephant outcomes, <span class="math inline">\(120\)</span> regions, or <span class="math inline">\(120\)</span> groups. Its meaning depends upon the roles of the quantities from which it was produced and the relationship expressed by the multiplication. The next task is therefore not merely to calculate the numerical answer, but to determine what kind of quantity the calculation is capable of producing.</p>
<p>This question can be approached in the same way that units are considered in physics. Suppose a car travels at <span class="math inline">\(60\)</span> kilometres per hour for <span class="math inline">\(2\)</span> hours. The multiplication</p>
<p><span class="math display">\[
2\times60=120
\]</span></p>
<p>does not explain by itself what <span class="math inline">\(120\)</span> represents. The units preserve the relationship between the quantities:</p>
<p><span class="math display">\[
2\text{ hours}
\times
\frac{60\text{ kilometres}}{1\text{ hour}}
=
120\text{ kilometres}.
\]</span></p>
<p>The unit “hours” appears once as the quantity being acted upon and once in the denominator of the rate. These units cancel, leaving kilometres as the unit of the result. The cancellation is not simply a decorative addition to the arithmetic. It shows that multiplying duration by distance per unit of duration produces distance. If the resulting unit did not correspond to the quantity requested by the problem, that mismatch would reveal that the quantities had been related incorrectly.</p>
<p>Probability problems involve a similar need to preserve meaning, although the labels used in probability are not always physical units such as metres, seconds, or kilograms. The words <em>spin</em>, <em>trial</em>, <em>region</em>, and <em>elephant outcome</em> identify what is being counted and what role each count plays. These labels prevent the learner from treating every visible number as if it represented the same kind of object.</p>
<p>At the beginning of the problem, the probability is formed as</p>
<p><span class="math display">\[
P(\text{elephant})
=
\frac{4\text{ elephant regions}}
{7\text{ total regions}}
=
\frac47.
\]</span></p>
<p>Because both the numerator and denominator count regions, their physical counting unit cancels. For this reason, probability is numerically dimensionless. Nevertheless, the probability is not semantically empty. The value <span class="math inline">\(\frac47\)</span> retains the relationship from which it was constructed: it represents the proportion of the spinner’s equally likely outcomes that belong to the elephant category. It therefore tells us that one complete spin has a probability of <span class="math inline">\(\frac47\)</span> of producing an elephant result.</p>
<p>The number <span class="math inline">\(210\)</span>, on the other hand, counts complete spins:</p>
<p><span class="math display">\[
210\text{ spins}.
\]</span></p>
<p>If the learner now writes</p>
<p><span class="math display">\[
210\text{ spins}\times\frac47,
\]</span></p>
<p>the expression still does not visibly show how the unit “spins” becomes the unit “elephant outcomes.” The fraction <span class="math inline">\(\frac47\)</span> is numerically dimensionless, so a purely mechanical treatment of units might appear to leave the unit unchanged:</p>
<p><span class="math display">\[
210\text{ spins}\times\frac47
=
120\text{ spins}.
\]</span></p>
<p>This result is not entirely false, but it is incomplete. The calculation does identify <span class="math inline">\(120\)</span> of the <span class="math inline">\(210\)</span> spins. However, the problem is not asking for an unspecified subset of spins. It is asking for the spins expected to produce a particular result. The complete meaning of the answer is therefore</p>
<p><span class="math display">\[
120\text{ spins expected to land on an elephant}.
\]</span></p>
<p>This longer label reveals two connected aspects of the answer. The objects being counted are spins, while the condition used to select those spins is “lands on an elephant.” The answer can consequently be described either as “120 expected elephant outcomes” or as “120 spins expected to land on an elephant.” These descriptions refer to the same predicted events, but the second makes the connection to the original collection of 210 spins more explicit.</p>
<p>To make this transformation visible inside the expression, the probability must be interpreted through the expected contribution of one trial. Consider one complete spin. If it lands on an elephant, it contributes one elephant outcome to the final count. If it does not land on an elephant, it contributes zero elephant outcomes. We may represent these possibilities as</p>
<p><span class="math display">\[
\begin{aligned}
\text{elephant result} &amp;\longrightarrow 1\text{ elephant outcome},\\
\text{non-elephant result} &amp;\longrightarrow 0\text{ elephant outcomes}.
\end{aligned}
\]</span></p>
<p>The expected contribution of one spin is then determined by combining each possible contribution with its probability:</p>
<p><span class="math display">\[
\begin{aligned}
\text{expected elephant contribution from one spin}
&amp;=
1\left(\frac47\right)
+
0\left(\frac37\right)\\
&amp;=
\frac47.
\end{aligned}
\]</span></p>
<p>This calculation does not claim that an individual spin physically produces <span class="math inline">\(\frac47\)</span> of an elephant outcome. A particular spin produces either one elephant outcome or zero elephant outcomes. The value <span class="math inline">\(\frac47\)</span> describes the average contribution predicted for one trial when the same experiment is considered across many repetitions. It allows the probability to be expressed as an expected counting rate:</p>
<p><span class="math display">\[
\frac47
\text{ expected elephant outcomes per spin}.
\]</span></p>
<p>This interpretation has been derived from the original ratio of regions; it has not been created by silently changing the meaning of <span class="math inline">\(4\)</span> and <span class="math inline">\(7\)</span>. The number <span class="math inline">\(4\)</span> originally counts elephant regions and the number <span class="math inline">\(7\)</span> originally counts total regions. Because one spin selects one of those regions, their ratio determines the probability of an elephant result. Because an elephant result contributes one to the final elephant count, that probability also determines the expected elephant-count contribution of one spin. The complete relational path is therefore</p>
<p><span class="math display">\[
\frac{4\text{ elephant regions}}
{7\text{ total regions}}
\longrightarrow
P(\text{elephant on one spin})=\frac47
\longrightarrow
\frac47\text{ expected elephant outcomes per spin}.
\]</span></p>
<p>Only after this relationship has been established can the multiplication be written in a form resembling dimensional reasoning:</p>
<p><span class="math display">\[
210\text{ spins}
\times
\frac{\frac47\text{ expected elephant outcomes}}
{1\text{ spin}}
=
120\text{ expected elephant outcomes}.
\]</span></p>
<p>The unit “spin” now appears in both the total number of trials and the denominator of the expected contribution per trial. The calculation can therefore be read as</p>
<p><span class="math display">\[
\cancel{210\text{ spins}}
\times
\frac{\frac47\text{ expected elephant outcomes}}
{\cancel{1\text{ spin}}}
=
120\text{ expected elephant outcomes}.
\]</span></p>
<p>The notation above is intended to expose the semantic relationship, not to suggest that probability possesses a physical unit in precisely the same way as speed or distance. The spinner probability <span class="math inline">\(\frac47\)</span> remains a dimensionless number. The phrase “expected elephant outcomes per spin” records how that number functions when it is applied to repeated trials. It tells us what is contributed, on average, by each trial and therefore explains why multiplying by the number of trials produces an expected count of elephant outcomes.</p>
<p>The relationship between the quantities can be summarized as follows:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Quantity</th>
<th>What it counts or describes</th>
<th>Role in the multiplication</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(210\)</span> spins</td>
<td>The complete collection of trials</td>
<td>The quantity across which the probability model is applied</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\frac47\)</span></td>
<td>The probability of an elephant on one spin</td>
<td>The expected elephant-count contribution of each trial</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(120\)</span></td>
<td>The predicted selected part of the 210 spins</td>
<td>The expected number of spins that land on an elephant</td>
</tr>
</tbody>
</table>
<p>The final unit should therefore not be copied mechanically from the phrase “spin 210 times,” nor should the answer be written merely as <span class="math inline">\(120\)</span> without explanation. Its meaning must be derived from the target quantity of the problem. The problem asks how many of the 210 spins are predicted to satisfy the condition “lands on an elephant.” Therefore, the most complete form of the answer is</p>
<p><span class="math display">\[
\boxed{120\text{ spins are expected to land on an elephant}.}
\]</span></p>
<p>This wording is more precise than simply writing “120 times.” The word <em>times</em> indicates the number of occurrences, but it does not identify what is expected to occur. Writing “120 elephant outcomes” identifies the selected category, while writing “120 spins are expected to land on an elephant” preserves both the original trial unit and the condition defining the predicted subset.</p>
<p>The learner can verify this interpretation before performing the calculation by asking what the unknown quantity is intended to count. If we let <span class="math inline">\(N_E\)</span> represent the predicted number of elephant outcomes, then the structure of the problem is</p>
<p><span class="math display">\[
N_E
=
\text{total number of spins}
\times
\text{expected elephant contribution per spin}.
\]</span></p>
<p>Substituting the quantities gives</p>
<p><span class="math display">\[
N_E
=
210\text{ spins}
\times
\frac{\frac47\text{ expected elephant outcomes}}
{1\text{ spin}}
=
120\text{ expected elephant outcomes}.
\]</span></p>
<p>Naming the unknown before calculating performs an important explanatory function. It establishes the destination of the reasoning. The learner is no longer multiplying numbers and deciding afterward what the answer might mean. The desired quantity is identified first, and the multiplication is then constructed so that it produces that kind of quantity.</p>
<p>The unit also provides a coherence test. If the learner concluded that the result represented <span class="math inline">\(120\)</span> regions, the answer would not correspond to the question because no new regions are being created or counted. If the learner concluded that it represented <span class="math inline">\(120\)</span> groups, the meaning of a group would remain undefined. If the learner wrote only <span class="math inline">\(120\)</span> spins, the answer would fail to distinguish the predicted elephant spins from the original collection of all 210 spins. The description “120 spins expected to land on an elephant” passes the coherence test because it names both the objects being counted and the property that places them in the desired category.</p>
<p>This process shows that units and descriptive labels are not additions attached after the mathematics has been completed. They participate in the reasoning itself. They help determine what operation is appropriate, what kind of quantity the operation should produce, and whether the final result answers the original question. The numerical equation</p>
<p><span class="math display">\[
210\times\frac47=120
\]</span></p>
<p>records the arithmetic relationship, while the semantic equation</p>
<p><span class="math display">\[
210\text{ complete spins}
\times
\frac47\text{ expected elephant contribution per spin}
=
120\text{ expected elephant outcomes}
\]</span></p>
<p>records the meaning of that relationship. A complete understanding requires both.</p>
<p>The answer’s meaning has therefore been derived rather than guessed. The total quantity consists of 210 complete spins. The probability <span class="math inline">\(\frac47\)</span> identifies the expected elephant-producing part of that collection. The result <span class="math inline">\(120\)</span> counts the spins predicted to belong to that part. This meaning remains the same whether the multiplication is written as <span class="math inline">\(210\times\frac47\)</span> or <span class="math inline">\(\frac47\times210\)</span>, but the two arrangements may encourage the learner to construct the relationship in different ways. The distinction between an unchanged numerical product and the conceptual roles assigned to its factors leads to the next stage of the analysis.</p>
</section>
<section id="numerical-commutativity-and-the-conceptual-roles-of-the-factors" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="numerical-commutativity-and-the-conceptual-roles-of-the-factors"><span class="header-section-number">3</span> Numerical Commutativity and the Conceptual Roles of the Factors</h2>
<p>The previous section established that the expression</p>
<p><span class="math display">\[
210\times\frac47
\]</span></p>
<p>produces an expected count of elephant outcomes because <span class="math inline">\(210\)</span> represents the number of complete spins and <span class="math inline">\(\frac47\)</span> represents the expected elephant contribution associated with each spin. Since multiplication is commutative, the factors may also be written in the reverse order:</p>
<p><span class="math display">\[
\frac47\times210.
\]</span></p>
<p>Both arrangements produce the same numerical result:</p>
<p><span class="math display">\[
210\times\frac47
=
\frac47\times210
=
120.
\]</span></p>
<p>The equality of these products is guaranteed by the commutative law of multiplication. For any two numbers <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>,</p>
<p><span class="math display">\[
a\times b=b\times a.
\]</span></p>
<p>If <span class="math inline">\(a=210\)</span> and <span class="math inline">\(b=\frac47\)</span>, then changing their order cannot change the numerical product. The commutative law, however, makes a statement about numerical value. It does not claim that both factors have the same meaning, perform the same conceptual role, or encourage the learner to construct the multiplication through the same thought process.</p>
<p>This distinction is important because a mathematical expression operates at more than one level. At the formal level, <span class="math inline">\(210\)</span> and <span class="math inline">\(\frac47\)</span> are numbers, and multiplication treats them symmetrically. At the semantic level, they represent different elements of the probability model. The number <span class="math inline">\(210\)</span> represents the complete collection of trials, whereas <span class="math inline">\(\frac47\)</span> represents the proportional relationship used to identify the expected elephant-producing part of that collection.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Factor</th>
<th>Meaning in the problem</th>
<th>Conceptual role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(210\)</span></td>
<td>The total number of spins</td>
<td>The complete collection being considered</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\frac47\)</span></td>
<td>The probability of an elephant on one spin</td>
<td>The proportion used to predict the elephant-producing part</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(120\)</span></td>
<td>The expected elephant count</td>
<td>The predicted part selected from the complete collection</td>
</tr>
</tbody>
</table>
<p>The factors are therefore numerically interchangeable in position but semantically distinguishable in role. Reversing their written order does not turn <span class="math inline">\(\frac47\)</span> into the total number of trials, nor does it turn <span class="math inline">\(210\)</span> into the probability of an elephant. Their positions change; their references do not.</p>
<p>When the expression is written as</p>
<p><span class="math display">\[
\frac47\times210,
\]</span></p>
<p>it naturally supports the reading</p>
<blockquote class="blockquote">
<p>Find four-sevenths of 210 spins.</p>
</blockquote>
<p>In this reading, <span class="math inline">\(210\)</span> is the reference quantity: it represents the whole collection from which a proportional part is to be determined. The fraction <span class="math inline">\(\frac47\)</span> acts as a scaling or selection operator. It tells us what proportion of the reference collection is expected to satisfy the condition “lands on an elephant.”</p>
<p>The expression can therefore be interpreted as</p>
<p><span class="math display">\[
\frac47
\times
\underbrace{210\text{ spins}}_{\text{reference collection}}
=
\underbrace{120\text{ expected elephant spins}}_{\text{predicted part}}.
\]</span></p>
<p>The word <em>of</em> plays an important role in the verbal interpretation. In elementary fraction language, “four-sevenths of 210” is translated into multiplication:</p>
<p><span class="math display">\[
\frac47\text{ of }210
\longrightarrow
\frac47\times210.
\]</span></p>
<p>The fraction answers the question “what proportion?”, while <span class="math inline">\(210\)</span> answers the question “what complete quantity is that proportion being taken from?” This interpretation foregrounds the part–whole structure of the calculation.</p>
<p>When the expression is written in the original order,</p>
<p><span class="math display">\[
210\times\frac47,
\]</span></p>
<p>a different reading becomes more readily available:</p>
<blockquote class="blockquote">
<p>Accumulate an expected elephant contribution of <span class="math inline">\(\frac47\)</span> across 210 spins.</p>
</blockquote>
<p>Here, the number <span class="math inline">\(210\)</span> foregrounds repetition. It tells us how many complete trials contribute to the total, while <span class="math inline">\(\frac47\)</span> describes the expected contribution associated with each trial. The expression may be expanded conceptually as</p>
<p><span class="math display">\[
\underbrace{
\frac47+\frac47+\cdots+\frac47
}_{210\text{ expected contributions}}.
\]</span></p>
<p>This interpretation foregrounds repeated accumulation rather than proportional selection. It treats the product as a total formed by applying the same expected contribution across all 210 trials.</p>
<p>The two interpretations can be compared as follows:</p>
<p><span class="math display">\[
\begin{aligned}
\frac47\times210
&amp;=
\text{take the expected elephant proportion of 210 spins},\\
210\times\frac47
&amp;=
\text{accumulate }\frac47\text{ across 210 spins}.
\end{aligned}
\]</span></p>
<p>These are not two different probability models. They are two perspectives on the same multiplicative relationship. One begins with the whole collection and identifies a proportional part. The other begins with the contribution associated with one trial and accumulates that contribution across the collection. Because proportional selection and repeated scaling describe the same multiplication, they arrive at the same expected count.</p>
<p>The relationship can be represented as</p>
<p><span class="math display">\[
\begin{aligned}
\text{part of a whole:}\qquad
&amp;\frac47\text{ of }210=120,\\[4pt]
\text{repeated contribution:}\qquad
&amp;210\text{ contributions of }\frac47=120.
\end{aligned}
\]</span></p>
<p>The commutative law allows the mathematical system to preserve the equality of these perspectives:</p>
<p><span class="math display">\[
\frac47\times210
=
210\times\frac47.
\]</span></p>
<p>However, the learner must not infer from this equality that the semantic roles have also become identical. The value <span class="math inline">\(210\)</span> remains the number of trials in both expressions. The value <span class="math inline">\(\frac47\)</span> remains the probability or expected proportional contribution in both expressions. The value <span class="math inline">\(120\)</span> remains the expected number of elephant outcomes in both expressions.</p>
<p>This is similar to a simpler counting situation. Suppose there are three boxes containing five pencils each. The total number of pencils is</p>
<p><span class="math display">\[
3\text{ boxes}
\times
\frac{5\text{ pencils}}{1\text{ box}}
=
15\text{ pencils}.
\]</span></p>
<p>Numerically, the product may also be written as</p>
<p><span class="math display">\[
5\times3=15.
\]</span></p>
<p>The change of order does not change the total. Nevertheless, the number <span class="math inline">\(3\)</span> still represents boxes, and the number <span class="math inline">\(5\)</span> still represents the number of pencils in each box. The commutative law permits the numerical factors to exchange positions, but it does not exchange the objects to which those numbers refer. Three does not begin to mean pencils per box merely because it is written second, and five does not begin to mean the number of boxes merely because it is written first.</p>
<p>The same principle applies to the spinner problem:</p>
<p><span class="math display">\[
210\text{ spins}
\times
\frac{\frac47\text{ expected elephant outcomes}}
{1\text{ spin}}
=
120\text{ expected elephant outcomes}.
\]</span></p>
<p>At the numerical level, the multiplication may be reversed:</p>
<p><span class="math display">\[
\frac47\times210=210\times\frac47.
\]</span></p>
<p>At the semantic level, however, the full relationship must remain stable:</p>
<p><span class="math display">\[
\frac{\frac47\text{ expected elephant outcomes}}
{1\text{ spin}}
\times
210\text{ spins}
=
120\text{ expected elephant outcomes}.
\]</span></p>
<p>The unit or descriptive meaning of the result is therefore not altered by commutativity. Both arrangements produce the same expected elephant count. It would be incorrect to claim that the units of a valid multiplication disobey the commutative law. If reversing the factors appeared to change the result from elephant outcomes to some other kind of object, that change would reveal that the meanings of the factors had been reassigned during interpretation. The problem would not lie in commutativity; it would lie in a silent change of reference.</p>
<p>This distinction can be expressed by separating three properties of each factor:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Property</th>
<th><span class="math inline">\(210\)</span></th>
<th><span class="math inline">\(\frac47\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Numerical value</td>
<td>Two hundred and ten</td>
<td>Four-sevenths</td>
</tr>
<tr class="even">
<td>Referent</td>
<td>The collection of spins</td>
<td>The elephant probability associated with a spin</td>
</tr>
<tr class="odd">
<td>Relational role</td>
<td>The quantity being proportionally classified or the number of repetitions</td>
<td>The scaling proportion or expected contribution per trial</td>
</tr>
</tbody>
</table>
<p>Commutativity acts on the first row. It permits the numerical values to exchange positions without changing their product. It does not erase the second and third rows. The referent and relational role of each quantity come from the problem situation, not from the left-to-right position of the number in the expression.</p>
<p>This explains why two mathematically equivalent arrangements may differ in explanatory usefulness. For a learner who already understands fractions as operators, the expression</p>
<p><span class="math display">\[
\frac47\times210
\]</span></p>
<p>may be easier to interpret because it follows the familiar verbal structure “four-sevenths of 210.” The learner first identifies the complete collection and then takes the required proportion of it.</p>
<p>For a learner who is thinking in terms of repeated trials, the expression</p>
<p><span class="math display">\[
210\times\frac47
\]</span></p>
<p>may make the accumulation more visible. The learner sees 210 trials, each associated with the same expected contribution, and combines those contributions into one expected total.</p>
<p>Neither order is universally superior. The appropriate arrangement depends upon the mental model the explanation is attempting to support. What matters is that the explanation identifies the role of each factor and preserves that role when the symbols are rearranged.</p>
<p>A difficulty arises when formal rearrangement occurs without semantic tracking. A learner may be taught that multiplication is commutative and may therefore exchange the positions of the factors mechanically. The resulting arithmetic remains correct, but the learner may no longer know which number represents the complete collection, which represents the probability, or why the product represents elephant outcomes. The symbols have been transformed correctly while the connection to the problem has weakened.</p>
<p>An explanation designed around mathematical understanding must therefore coordinate the formal and semantic levels:</p>
<p><span class="math display">\[
\begin{aligned}
\text{formal relationship:}\qquad
&amp;210\times\frac47=\frac47\times210,\\[4pt]
\text{semantic relationship:}\qquad
&amp;\text{number of trials}\times
\text{expected elephant contribution per trial}\\
&amp;=\text{expected number of elephant outcomes}.
\end{aligned}
\]</span></p>
<p>The formal relationship tells us that the order of multiplication does not affect the product. The semantic relationship tells us why these particular quantities are being multiplied and what their product represents. A complete explanation must preserve both.</p>
<p>The phrase “take <span class="math inline">\(\frac47\)</span> of 210” also reveals an asymmetry that belongs to language and thought rather than to numerical multiplication. The fraction <span class="math inline">\(\frac47\)</span> specifies the proportional transformation, while <span class="math inline">\(210\)</span> specifies the quantity transformed. If we say “take 210 of <span class="math inline">\(\frac47\)</span>,” the sentence no longer expresses the intended relationship clearly, even though the numerical expression <span class="math inline">\(210\times\frac47\)</span> remains valid. Ordinary language distinguishes the operator from the object upon which it operates more strongly than multiplication notation does.</p>
<p>This is one reason learners may experience confusion when they are told only that multiplication is commutative. The statement is mathematically correct, but it can be overgeneralized. The learner may conclude that every aspect of the two factors is interchangeable. A more complete statement would be:</p>
<blockquote class="blockquote">
<p>Multiplication is commutative with respect to numerical value, but the quantities being multiplied may continue to represent different objects and perform different roles in the model.</p>
</blockquote>
<p>In the spinner problem, the expression</p>
<p><span class="math display">\[
\frac47\times210
\]</span></p>
<p>invites the learner to begin with a whole collection of 210 trials and identify its expected elephant-producing part. The expression</p>
<p><span class="math display">\[
210\times\frac47
\]</span></p>
<p>invites the learner to begin with 210 repeated trials and accumulate the expected contribution associated with each one. The numerical destination is identical:</p>
<p><span class="math display">\[
120\text{ expected elephant outcomes}.
\]</span></p>
<p>The conceptual route, however, need not be identical. Recognizing this distinction allows an explanation to use commutativity without allowing the references of the quantities to drift.</p>
<p>The analysis also prepares us to examine the simplification</p>
<p><span class="math display">\[
210\times\frac47
=
30\times4.
\]</span></p>
<p>At the formal level, the transition occurs because <span class="math inline">\(210\)</span> is divisible by <span class="math inline">\(7\)</span>. At the semantic level, a more difficult question appears: the denominator <span class="math inline">\(7\)</span> originally counts regions, whereas <span class="math inline">\(210\)</span> counts spins. What does it mean, then, to divide 210 spins by a number that entered the problem as seven regions? Answering this question requires us to preserve the original role of <span class="math inline">\(7\)</span>, derive its relationship to repeated trials, and distinguish an expected grouping from a guaranteed pattern of observed results.</p>
</section>
<section id="why-dividing-210-by-7-requires-an-explanation" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="why-dividing-210-by-7-requires-an-explanation"><span class="header-section-number">4</span> Why Dividing 210 by 7 Requires an Explanation</h2>
<p>The previous section ended with the simplification</p>
<p><span class="math display">\[
210\times\frac47
=
30\times4.
\]</span></p>
<p>A conventional solution usually reaches this intermediate expression by cancelling <span class="math inline">\(7\)</span> against <span class="math inline">\(210\)</span>:</p>
<p><span class="math display">\[
210\times\frac47
=
\cancelto{30}{210}\times\frac{4}{\cancel{7}}
=
30\times4.
\]</span></p>
<p>The symbolic transformation is valid, but the word <em>cancel</em> describes only what happens to the written numbers. It does not explain why dividing <span class="math inline">\(210\)</span> by <span class="math inline">\(7\)</span> is meaningful within the probability problem. The learner began with <span class="math inline">\(210\)</span> spins and a spinner containing <span class="math inline">\(7\)</span> regions. If the explanation now states that <span class="math inline">\(210\div7=30\)</span>, an immediate semantic difficulty appears: how can a number of spins be divided by a number of regions? The quantities initially count different objects, and an explanation that ignores this difference creates the impression that unlike objects may be combined merely because their numerical values permit simplification.</p>
<p>The first step toward resolving this difficulty is to distinguish the numerical value <span class="math inline">\(7\)</span> from the origin of that value. The denominator originates as a count of regions:</p>
<p><span class="math display">\[
\frac{4\text{ elephant regions}}
{7\text{ total regions}}.
\]</span></p>
<p>Because the numerator and denominator both count regions, their region units cancel when the ratio is formed. The resulting probability</p>
<p><span class="math display">\[
\frac47
\]</span></p>
<p>is dimensionless as a number. Therefore, the expression <span class="math inline">\(210\times\frac47\)</span> does not literally divide 210 spins by seven regions. It multiplies a number of spins by a dimensionless proportion whose denominator originated from the spinner’s seven-region possibility structure. The origin of the denominator remains semantically important, but the completed ratio is no longer a physical collection of regions.</p>
<p>This distinction prevents an invalid unit interpretation:</p>
<p><span class="math display">\[
\frac{210\text{ spins}}{7\text{ regions}}.
\]</span></p>
<p>The expression above would produce “spins per region,” which is not the quantity requested by the problem and is not the meaning of the calculation. The actual symbolic structure is</p>
<p><span class="math display">\[
210\text{ spins}\times
\left(
\frac{4\text{ elephant regions}}
{7\text{ total regions}}
\right).
\]</span></p>
<p>The fraction inside the parentheses is first interpreted as a probability. Only then does it operate upon the collection of spins:</p>
<p><span class="math display">\[
210\text{ spins}\times
\frac47
=
\frac47\text{ of }210\text{ spins}.
\]</span></p>
<p>The meaning of dividing <span class="math inline">\(210\)</span> by <span class="math inline">\(7\)</span> must therefore be derived from the fraction acting upon the whole collection. In fraction language, finding <span class="math inline">\(\frac47\)</span> of a quantity involves two connected operations. The denominator <span class="math inline">\(7\)</span> divides the reference quantity into seven equal shares, and the numerator <span class="math inline">\(4\)</span> selects four of those shares. Applied to the present problem, the complete collection is 210 spins:</p>
<p><span class="math display">\[
\underbrace{210\text{ spins}}_{\text{complete reference quantity}}.
\]</span></p>
<p>The denominator instructs us to determine the size of one-seventh of this collection:</p>
<p><span class="math display">\[
\frac17\text{ of }210\text{ spins}
=
210\text{ spins}\div7
=
30\text{ spins}.
\]</span></p>
<p>The result <span class="math inline">\(30\)</span> is the size of one proportional share. The numerator then tells us that the required proportion contains four such shares:</p>
<p><span class="math display">\[
4\times30\text{ spins}
=
120\text{ spins}.
\]</span></p>
<p>The fraction operation can therefore be reconstructed as</p>
<p><span class="math display">\[
\begin{aligned}
\frac47\text{ of }210\text{ spins}
&amp;=
4\times
\left(
\frac17\text{ of }210\text{ spins}
\right)\\
&amp;=
4\times
\left(
210\text{ spins}\div7
\right)\\
&amp;=
4\times30\text{ spins}\\
&amp;=
120\text{ spins expected to land on an elephant}.
\end{aligned}
\]</span></p>
<p>Under this interpretation, <span class="math inline">\(210\div7=30\)</span> does <strong>not</strong> mean that 210 spins have been arranged into 30 groups containing seven spins each. It means that the complete collection of 210 spins has been divided into seven equal proportional shares, with 30 spins in each share:</p>
<p><span class="math display">\[
210\text{ spins}
=
\underbrace{
30+30+30+30+30+30+30
}_{7\text{ equal shares}}.
\]</span></p>
<p>The numerator <span class="math inline">\(4\)</span> then selects four of these seven shares:</p>
<p><span class="math display">\[
\underbrace{
30+30+30+30
}_{4\text{ selected shares}}
=
120.
\]</span></p>
<p>This interpretation preserves the ordinary part–whole meaning of the fraction. The denominator <span class="math inline">\(7\)</span> tells us how many equal shares constitute the whole proportional structure, while the numerator <span class="math inline">\(4\)</span> tells us how many of those shares belong to the desired proportion. The seven shares do not correspond to the seven physical regions one by one. Each share contains 30 spins, whereas each spinner region is a spatial part of one spinner. The relationship between them is proportional rather than physical: four of seven spinner regions are elephant regions, so the model predicts that four-sevenths of the repeated spins will produce elephant outcomes.</p>
<p>The relational movement is therefore</p>
<p><span class="math display">\[
\begin{aligned}
&amp;4\text{ of }7\text{ equally likely regions are elephant regions}\\
&amp;\longrightarrow P(\text{elephant})=\frac47\\
&amp;\longrightarrow \text{the expected elephant proportion of the trials is }\frac47\\
&amp;\longrightarrow \text{divide the collection of trials into }7\text{ equal proportional shares}\\
&amp;\longrightarrow \text{select }4\text{ of those shares}.
\end{aligned}
\]</span></p>
<p>The learner is not entitled to move directly from “seven spinner regions” to “seven groups of spins.” The intermediate probability relationship is essential. It converts the spinner’s spatial composition into a predicted proportion of repeated outcomes. Once that conversion has been established, the denominator may guide the proportional partitioning of the 210 trials.</p>
<p>The algebra records the same reasoning more compactly:</p>
<p><span class="math display">\[
\begin{aligned}
210\times\frac47
&amp;=
210\times4\times\frac17\\
&amp;=
\left(210\times\frac17\right)\times4\\
&amp;=
\left(\frac{210}{7}\right)\times4\\
&amp;=
30\times4\\
&amp;=
120.
\end{aligned}
\]</span></p>
<p>The transition from the first line to the second uses the associative and commutative properties of multiplication. Since</p>
<p><span class="math display">\[
\frac47=4\times\frac17,
\]</span></p>
<p>multiplying by <span class="math inline">\(\frac47\)</span> means multiplying by <span class="math inline">\(\frac17\)</span> and by <span class="math inline">\(4\)</span>. Multiplication by <span class="math inline">\(\frac17\)</span> is equivalent to division by <span class="math inline">\(7\)</span>:</p>
<p><span class="math display">\[
210\times\frac17=\frac{210}{7}=30.
\]</span></p>
<p>The symbolic simplification is therefore not an isolated cancellation trick. It reflects the internal structure of the fraction: first determine one of the seven equal proportional shares, then take four such shares.</p>
<p>At this point, another interpretation must be distinguished from the seven-share interpretation. The equation</p>
<p><span class="math display">\[
210\div7=30
\]</span></p>
<p>can also answer the question:</p>
<blockquote class="blockquote">
<p>How many groups of seven spins can be formed from 210 spins?</p>
</blockquote>
<p>Under this reading, each group contains seven spins, so 210 spins form 30 groups:</p>
<p><span class="math display">\[
210\text{ spins}
=
\underbrace{
7\text{ spins}
+
7\text{ spins}
+
\cdots
+
7\text{ spins}
}_{30\text{ groups}}.
\]</span></p>
<p>This interpretation is numerically valid, but it uses a different meaning of division. In the seven-share interpretation, <span class="math inline">\(7\)</span> specifies the <strong>number of groups</strong>, and <span class="math inline">\(30\)</span> is the number of spins in each group:</p>
<p><span class="math display">\[
210\text{ spins}\div7\text{ groups}
=
30\text{ spins per group}.
\]</span></p>
<p>In the groups-of-seven interpretation, <span class="math inline">\(7\)</span> specifies the <strong>size of each group</strong>, and <span class="math inline">\(30\)</span> is the number of groups:</p>
<p><span class="math display">\[
210\text{ spins}\div
7\text{ spins per group}
=
30\text{ groups}.
\]</span></p>
<p>The same numerical equation supports two different mental organizations:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Interpretation of <span class="math inline">\(210\div7\)</span></th>
<th>Meaning of <span class="math inline">\(7\)</span></th>
<th>Meaning of <span class="math inline">\(30\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Divide 210 into seven equal shares</td>
<td>Number of equal shares</td>
<td>Spins in each share</td>
</tr>
<tr class="even">
<td>Form groups containing seven spins</td>
<td>Number of spins in each group</td>
<td>Number of groups</td>
</tr>
</tbody>
</table>
<p>This distinction is important because the expression <span class="math inline">\(210\div7=30\)</span> does not announce which interpretation is intended. The surrounding conceptual model supplies that meaning. If the explanation says only “divide 210 by 7,” the learner must determine whether seven is the number of groups or the size of each group. Failing to make this relationship explicit transfers avoidable interpretive work to the learner.</p>
<p>For understanding <span class="math inline">\(\frac47\)</span> as a fraction of 210, the seven-equal-shares interpretation is the most direct:</p>
<p><span class="math display">\[
210\text{ spins}
\longrightarrow
7\text{ equal shares of }30\text{ spins}
\longrightarrow
4\text{ shares}
\longrightarrow
120\text{ expected elephant spins}.
\]</span></p>
<p>The groups-of-seven interpretation provides a second route, but it requires an additional probabilistic argument. We cannot say that every group of seven actual spins contains exactly four elephant outcomes. The probability <span class="math inline">\(\frac47\)</span> does not guarantee such a pattern. A particular group of seven spins might contain no elephant outcomes, three elephant outcomes, four elephant outcomes, or even seven elephant outcomes. Probability predicts a long-run proportion or expected count; it does not prescribe the exact composition of each small group.</p>
<p>To use groups of seven spins correctly, we must first ask for the expected number of elephant outcomes in one such group. Since each spin has an expected elephant contribution of <span class="math inline">\(\frac47\)</span>, seven spins have an expected elephant count of</p>
<p><span class="math display">\[
7\times\frac47=4.
\]</span></p>
<p>Thus, one group of seven spins contributes an <strong>expected</strong> count of four elephant outcomes:</p>
<p><span class="math display">\[
7\text{ spins}
\longrightarrow
4\text{ expected elephant outcomes}.
\]</span></p>
<p>Because 210 spins contain 30 groups of seven spins,</p>
<p><span class="math display">\[
210\text{ spins}\div
7\text{ spins per group}
=
30\text{ groups}.
\]</span></p>
<p>The expected contribution of the 30 groups is then</p>
<p><span class="math display">\[
30\text{ groups}
\times
\frac{4\text{ expected elephant outcomes}}
{1\text{ group}}
=
120\text{ expected elephant outcomes}.
\]</span></p>
<p>The full reasoning is</p>
<p><span class="math display">\[
\begin{aligned}
210\times\frac47
&amp;=
\left(\frac{210}{7}\right)\times4\\
&amp;=
30\text{ groups of seven spins}
\times
4\text{ expected elephant outcomes per group}\\
&amp;=
120\text{ expected elephant outcomes}.
\end{aligned}
\]</span></p>
<p>This interpretation is legitimate only because the expected relationship</p>
<p><span class="math display">\[
7\text{ spins}
\longrightarrow
4\text{ expected elephant outcomes}
\]</span></p>
<p>has first been derived from the one-spin probability <span class="math inline">\(\frac47\)</span>. The number <span class="math inline">\(7\)</span> has not silently changed from regions to spins. Instead, a new seven-spin reference group has been constructed from the probability model:</p>
<p><span class="math display">\[
\begin{aligned}
\frac47
&amp;=
\text{probability of an elephant on one spin},\\
7\times\frac47
&amp;=
\text{expected elephant count across seven spins},\\
&amp;=4.
\end{aligned}
\]</span></p>
<p>The distinction between the two uses of <span class="math inline">\(7\)</span> can now be stated precisely. The first <span class="math inline">\(7\)</span> belongs to the spinner’s outcome space:</p>
<p><span class="math display">\[
7\text{ equally likely regions}.
\]</span></p>
<p>The second <span class="math inline">\(7\)</span> belongs to a deliberately chosen batch of repeated trials:</p>
<p><span class="math display">\[
7\text{ spins in one reference batch}.
\]</span></p>
<p>These are not the same object. Their numerical equality allows the batch to reveal the proportional relationship particularly clearly, but probability provides the bridge between them:</p>
<p><span class="math display">\[
\begin{aligned}
4\text{ elephant regions out of }7\text{ regions}
&amp;\longrightarrow P(\text{elephant})=\frac47,\\
P(\text{elephant})=\frac47
&amp;\longrightarrow 4\text{ expected elephants in }7\text{ spins}.
\end{aligned}
\]</span></p>
<p>The first statement concerns the composition of the spinner. The second concerns the expected results of repeated trials. Moving from one statement to the other requires reasoning; it is not a simple replacement of the word “regions” with the word “spins.”</p>
<p>Both interpretations of the intermediate result <span class="math inline">\(30\)</span> eventually produce the same answer, but they organize the reasoning differently:</p>
<p><span class="math display">\[
\begin{aligned}
\text{Part--whole route:}\qquad
&amp;7\text{ shares of }30\text{ spins};\text{ select }4\text{ shares}\\
&amp;=4\times30=120,\\[6pt]
\text{Expected-batch route:}\qquad
&amp;30\text{ groups of }7\text{ spins};\text{ expect }4\text{ elephants per group}\\
&amp;=30\times4=120.
\end{aligned}
\]</span></p>
<p>In the part–whole route, <span class="math inline">\(30\)</span> represents the size of one-seventh of the complete collection. In the expected-batch route, <span class="math inline">\(30\)</span> represents the number of seven-spin batches. The number is the same, but its role is different. This provides another example of why a numerical result cannot determine its own meaning. Meaning comes from the relational structure in which the result was produced.</p>
<p>The expression</p>
<p><span class="math display">\[
30\times4
\]</span></p>
<p>is therefore not self-explanatory. It may mean four proportional shares containing 30 spins each, or it may mean 30 seven-spin batches with an expected contribution of four elephant outcomes per batch. Both readings are mathematically coherent, but an explanation must identify which one it is using rather than requiring the learner to reconstruct the intended interpretation.</p>
<p>The common instruction “cancel the 7 with 210” hides all of these relationships. It tells the learner how to transform the notation but not how to preserve the meaning of the quantities during that transformation. Cancellation is useful as a computational abbreviation only after the learner understands that</p>
<p><span class="math display">\[
210\times\frac47
=
\left(\frac{210}{7}\right)\times4
\]</span></p>
<p>can be interpreted as determining one-seventh of the reference collection and taking four such shares, or equivalently as determining how many seven-spin batches are present and assigning an expected count of four elephant outcomes to each batch.</p>
<p>The learner should therefore not be taught merely to search for a denominator that divides the whole number. The deeper question is:</p>
<blockquote class="blockquote">
<p>What relationship does the denominator express, and how does that relationship become applicable to the complete quantity being acted upon?</p>
</blockquote>
<p>In this problem, the denominator first expresses the number of equally likely regions in the possibility structure of one spin. That structure produces the probability <span class="math inline">\(\frac47\)</span>. The probability then becomes a proportional operator acting upon the complete collection of 210 trials. Only at that stage does dividing <span class="math inline">\(210\)</span> by <span class="math inline">\(7\)</span> acquire a coherent meaning inside the solution.</p>
<p>The simplification</p>
<p><span class="math display">\[
210\times\frac47
=
30\times4
\]</span></p>
<p>is therefore the visible surface of a much richer transformation. Beneath it, the learner must preserve the distinction between regions and spins, understand how a region ratio becomes a one-spin probability, understand how that probability becomes a predicted proportion of repeated outcomes, determine which interpretation of division is being used, and remember that the resulting count is expected rather than guaranteed.</p>
<p>Once these relationships are established, cancellation no longer appears as a mysterious permission to remove matching numbers. It becomes a compact record of proportional reasoning. The denominator identifies one-seventh of the reference quantity, the division determines the size or number of relevant groups, and the numerator determines how many expected contributions must be accumulated. The final section will make that accumulation fully visible by interpreting multiplication as the broadcasting of the expected contribution <span class="math inline">\(\frac47\)</span> across all 210 complete trials.</p>
</section>
<section id="fractional-scaling-as-broadcasting-across-the-210-trials" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="fractional-scaling-as-broadcasting-across-the-210-trials"><span class="header-section-number">5</span> Fractional Scaling as Broadcasting Across the 210 Trials</h2>
<p>The previous section explained the simplification</p>
<p><span class="math display">\[
210\times\frac47
=
30\times4
=
120
\]</span></p>
<p>through proportional shares and expected groups. Although this interpretation explains why dividing by <span class="math inline">\(7\)</span> is meaningful, the compact expression still hides another relationship: the probability <span class="math inline">\(\frac47\)</span> does not apply to the collection only once in an undifferentiated manner. The same probability model governs every one of the 210 complete trials. The multiplication may therefore be understood as accumulating the expected contributions produced when <span class="math inline">\(\frac47\)</span> is applied across all 210 spins.</p>
<p>To make this relationship visible, begin with a single trial. One spin can contribute only one of two values to the final elephant count:</p>
<p><span class="math display">\[
\begin{aligned}
1, &amp;\qquad \text{if the spin lands on an elephant},\\
0, &amp;\qquad \text{if the spin does not land on an elephant}.
\end{aligned}
\]</span></p>
<p>If the contribution of the <span class="math inline">\(i\)</span>th spin is represented by <span class="math inline">\(X_i\)</span>, then</p>
<p><span class="math display">\[
X_i=
\begin{cases}
1, &amp; \text{if spin }i\text{ lands on an elephant},\\
0, &amp; \text{otherwise}.
\end{cases}
\]</span></p>
<p>The probability that <span class="math inline">\(X_i=1\)</span> is <span class="math inline">\(\frac47\)</span>, while the probability that <span class="math inline">\(X_i=0\)</span> is <span class="math inline">\(\frac37\)</span>. The expected contribution of the spin is therefore</p>
<p><span class="math display">\[
\begin{aligned}
E[X_i]
&amp;=
1\left(\frac47\right)
+
0\left(\frac37\right)\\
&amp;=
\frac47.
\end{aligned}
\]</span></p>
<p>The value <span class="math inline">\(\frac47\)</span> must not be confused with the result of an actual spin. An observed spin never produces <span class="math inline">\(\frac47\)</span> of an elephant outcome. It produces either one elephant outcome or zero elephant outcomes. The fraction represents the expected contribution of the trial before its result is known. It describes the average contribution that trials governed by this probability model would produce across repeated performances of the experiment.</p>
<p>This distinction separates the observed level from the expected level:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Level</th>
<th>Contribution of one spin</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Observed result</td>
<td>Either <span class="math inline">\(0\)</span> or <span class="math inline">\(1\)</span></td>
</tr>
<tr class="even">
<td>Expected contribution</td>
<td><span class="math inline">\(\frac47\)</span></td>
</tr>
<tr class="odd">
<td>Meaning of <span class="math inline">\(\frac47\)</span></td>
<td>Average predicted elephant-count contribution per trial</td>
</tr>
</tbody>
</table>
<p>The expected contribution <span class="math inline">\(\frac47\)</span> applies to the first spin. Because the second spin is governed by the same spinner and the same probability model, it also has an expected contribution of <span class="math inline">\(\frac47\)</span>. The same is true for every spin through the 210th trial:</p>
<p><span class="math display">\[
\begin{aligned}
E[X_1]&amp;=\frac47,\\
E[X_2]&amp;=\frac47,\\
E[X_3]&amp;=\frac47,\\
&amp;\ \vdots\\
E[X_{210}]&amp;=\frac47.
\end{aligned}
\]</span></p>
<p>The total number of observed elephant outcomes is obtained by adding the contributions of all the spins:</p>
<p><span class="math display">\[
X_1+X_2+\cdots+X_{210}.
\]</span></p>
<p>Before the spins are performed, the exact values of the individual <span class="math inline">\(X_i\)</span> are unknown. Some will become <span class="math inline">\(1\)</span>, while others will become <span class="math inline">\(0\)</span>. Although the exact total cannot be known in advance, its expected value can be determined by adding the expected contribution of every trial:</p>
<p><span class="math display">\[
\begin{aligned}
E[X_1+X_2+\cdots+X_{210}]
&amp;=
E[X_1]+E[X_2]+\cdots+E[X_{210}]\\
&amp;=
\underbrace{
\frac47+\frac47+\cdots+\frac47
}_{210\text{ expected contributions}}.
\end{aligned}
\]</span></p>
<p>Repeated addition of the same quantity is represented by multiplication. Therefore,</p>
<p><span class="math display">\[
\underbrace{
\frac47+\frac47+\cdots+\frac47
}_{210\text{ terms}}
=
210\times\frac47
=
120.
\]</span></p>
<p>The expression <span class="math inline">\(210\times\frac47\)</span> can thus be understood as a compressed representation of 210 expected contributions. The number <span class="math inline">\(210\)</span> tells us how many trials contribute, while <span class="math inline">\(\frac47\)</span> tells us the expected contribution associated with each trial. Their product gives the expected total:</p>
<p><span class="math display">\[
\underbrace{210\text{ trials}}_{\text{number of contributions}}
\times
\underbrace{\frac47\text{ expected elephant outcome per trial}}_{\text{size of each expected contribution}}
=
\underbrace{120\text{ expected elephant outcomes}}_{\text{expected accumulated count}}.
\]</span></p>
<p>This interpretation also clarifies the relationship between multiplication and broadcasting. In vector-based computation, broadcasting commonly refers to applying one value or operation across every element of a collection. For example, if a vector contains several values,</p>
<p><span class="math display">\[
\begin{bmatrix}
a_1\\
a_2\\
a_3
\end{bmatrix},
\]</span></p>
<p>then multiplying the vector by a scalar <span class="math inline">\(c\)</span> applies that same scalar to every component:</p>
<p><span class="math display">\[
c
\begin{bmatrix}
a_1\\
a_2\\
a_3
\end{bmatrix}
=
\begin{bmatrix}
ca_1\\
ca_2\\
ca_3
\end{bmatrix}.
\]</span></p>
<p>The scalar is written only once, but its operation is distributed across the complete collection. The compact notation hides the repeated application:</p>
<p><span class="math display">\[
a_1\longrightarrow ca_1,\qquad
a_2\longrightarrow ca_2,\qquad
a_3\longrightarrow ca_3.
\]</span></p>
<p>A similar mental model can be used for the probability problem. The 210 complete trials may be represented as a vector of 210 entries. Before considering probability, each entry can be written as <span class="math inline">\(1\)</span> to represent one complete opportunity for an elephant outcome:</p>
<p><span class="math display">\[
\mathbf{t}
=
\begin{bmatrix}
1\\
1\\
1\\
\vdots\\
1
\end{bmatrix}
\qquad
\text{with 210 entries}.
\]</span></p>
<p>The value <span class="math inline">\(1\)</span> does not mean that every trial will produce an elephant. It means that each position represents one complete trial capable of contributing either zero or one elephant outcome. The probability <span class="math inline">\(\frac47\)</span> is then applied across all entries:</p>
<p><span class="math display">\[
\frac47\mathbf{t}
=
\frac47
\begin{bmatrix}
1\\
1\\
1\\
\vdots\\
1
\end{bmatrix}
=
\begin{bmatrix}
\frac47\\
\frac47\\
\frac47\\
\vdots\\
\frac47
\end{bmatrix}.
\]</span></p>
<p>The resulting vector does not represent the observed outcomes of the spins. It represents their expected contributions. Every component is <span class="math inline">\(\frac47\)</span> because every trial is governed by the same probability model. Adding the components gives the expected total:</p>
<p><span class="math display">\[
\begin{aligned}
\frac47+\frac47+\cdots+\frac47
&amp;=
210\times\frac47\\
&amp;=
120.
\end{aligned}
\]</span></p>
<p>The broadcasting analogy therefore produces the following relational structure:</p>
<p><span class="math display">\[
\begin{aligned}
\text{collection of 210 complete trials}
&amp;\longrightarrow
\begin{bmatrix}
1&amp;1&amp;1&amp;\cdots&amp;1
\end{bmatrix},\\[4pt]
\text{broadcast the probability }\frac47
&amp;\longrightarrow
\begin{bmatrix}
\frac47&amp;\frac47&amp;\frac47&amp;\cdots&amp;\frac47
\end{bmatrix},\\[4pt]
\text{sum the expected contributions}
&amp;\longrightarrow
210\times\frac47=120.
\end{aligned}
\]</span></p>
<p>This analogy is useful because it makes visible the repeated application hidden by the scalar expression. However, broadcasting is an analogy for the organization of the reasoning; it is not the probability principle that justifies the calculation. The justification still comes from the fact that every spin is a complete trial governed by the same elephant probability <span class="math inline">\(\frac47\)</span>. Broadcasting provides a way to visualize how that one-trial probability is applied across the complete collection.</p>
<p>The analogy also requires a distinction between the vector of expected contributions and the vector of actual outcomes. Before the experiment, the expected-contribution vector is</p>
<p><span class="math display">\[
\begin{bmatrix}
\frac47&amp;
\frac47&amp;
\frac47&amp;
\cdots&amp;
\frac47
\end{bmatrix}.
\]</span></p>
<p>After the experiment, the observed-outcome vector might look like</p>
<p><span class="math display">\[
\begin{bmatrix}
1&amp;
0&amp;
1&amp;
1&amp;
0&amp;
\cdots
\end{bmatrix},
\]</span></p>
<p>where <span class="math inline">\(1\)</span> represents an elephant result and <span class="math inline">\(0\)</span> represents a non-elephant result. The actual sequence is not known in advance, and its sum is not guaranteed to equal <span class="math inline">\(120\)</span>. The expected vector describes the average prediction made before observing the outcomes, whereas the observed vector records what actually happened.</p>
<p>The difference can be expressed as</p>
<p><span class="math display">\[
\begin{aligned}
\text{expected total}
&amp;=
\sum_{i=1}^{210}E[X_i]
=
120,\\
\text{observed total}
&amp;=
\sum_{i=1}^{210}X_i
=
\text{the number actually obtained}.
\end{aligned}
\]</span></p>
<p>The observed total may be smaller than, equal to, or larger than <span class="math inline">\(120\)</span>. The prediction of <span class="math inline">\(120\)</span> does not claim that probability controls the experiment so that exactly 120 spins must land on elephants. It states that if the same 210-spin experiment were performed repeatedly, the average elephant count across those performances would approach 120.</p>
<p>The broadcasting model therefore does not broadcast a predetermined elephant result across every trial. It broadcasts the same <strong>probability relationship</strong> across every trial. Each trial retains uncertainty:</p>
<p><span class="math display">\[
X_i=
\begin{cases}
1 &amp; \text{with probability }\frac47,\\
0 &amp; \text{with probability }\frac37.
\end{cases}
\]</span></p>
<p>What remains constant across the vector is not the observed value of <span class="math inline">\(X_i\)</span>, but its expected value:</p>
<p><span class="math display">\[
E[X_i]=\frac47.
\]</span></p>
<p>This distinction is essential. If the learner imagines that <span class="math inline">\(\frac47\)</span> is a physical part removed from each spin, the model becomes difficult to reconcile with the fact that each spin produces a complete categorical result. By interpreting <span class="math inline">\(\frac47\)</span> as the expected contribution of each trial, the fractional representation and the discrete observed outcomes can coexist without contradiction.</p>
<p>The complete thought process behind the multiplication can now be reconstructed. The spinner contains four elephant regions among seven equally likely regions, producing the probability</p>
<p><span class="math display">\[
P(\text{elephant})=\frac47.
\]</span></p>
<p>Each complete spin is governed by this probability and therefore has an expected elephant contribution of <span class="math inline">\(\frac47\)</span>. The problem contains 210 complete spins, so there are 210 such expected contributions. Adding them produces</p>
<p><span class="math display">\[
\underbrace{
\frac47+\frac47+\cdots+\frac47
}_{210\text{ expected contributions}}
=
210\times\frac47
=
120.
\]</span></p>
<p>The compact multiplication is therefore not an unexplained command to combine the two numbers supplied by the question. It is a compressed representation of a repeated relational structure:</p>
<p><span class="math display">\[
\begin{aligned}
&amp;\text{one trial}
\longrightarrow
\frac47\text{ expected elephant contribution},\\
&amp;\text{210 trials}
\longrightarrow
210\text{ applications of that contribution},\\
&amp;\text{accumulation}
\longrightarrow
120\text{ expected elephant outcomes}.
\end{aligned}
\]</span></p>
<p>The learner is rarely shown this structure. Instead, the probability is usually calculated, multiplied by the number of trials, and converted into a final answer without explaining what multiplication is doing between these two quantities. The completed equation is presented as if its meaning were already visible:</p>
<p><span class="math display">\[
210\times\frac47=120.
\]</span></p>
<p>For an expert, the expression may immediately activate the ideas of repeated trials, constant probability, expected contribution, proportional scaling, and accumulated count. For a beginner, these relationships may not yet exist as one organized mental structure. The learner may therefore reproduce the equation while remaining unable to explain why <span class="math inline">\(\frac47\)</span> applies to all 210 trials or why its application produces an expected count.</p>
<p>The broadcasting analogy helps expose the organization hidden by the notation. It shows that the probability <span class="math inline">\(\frac47\)</span> belongs to each complete trial, that the same expected relationship is extended across the collection, and that multiplication accumulates the resulting expected contributions. What appears symbolically as one multiplication is mentally reconstructed as a coordinated system of 210 related trials.</p>
<p>The expression</p>
<p><span class="math display">\[
210\times\frac47
\]</span></p>
<p>can now be read at several connected levels:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Level</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fractional</td>
<td>Find <span class="math inline">\(\frac47\)</span> of 210 complete trials</td>
</tr>
<tr class="even">
<td>Repeated addition</td>
<td>Add <span class="math inline">\(\frac47\)</span> a total of 210 times</td>
</tr>
<tr class="odd">
<td>Expected contribution</td>
<td>Accumulate the expected elephant contribution of every trial</td>
</tr>
<tr class="even">
<td>Vector broadcasting</td>
<td>Apply the one-trial expected contribution across all 210 trial positions</td>
</tr>
<tr class="odd">
<td>Probability</td>
<td>Predict the total elephant count generated by repeated trials</td>
</tr>
</tbody>
</table>
<p>These interpretations do not compete with one another. Each makes a different part of the same mathematical structure visible. The fractional interpretation emphasizes the relationship between a whole collection and its predicted part. Repeated addition emphasizes accumulation. Expected contribution explains why a fractional value may be associated with a trial that produces a discrete result. Broadcasting exposes how one relationship is applied across an entire collection. Probability connects all these representations to the uncertainty of the physical experiment.</p>
<p>The final result</p>
<p><span class="math display">\[
\boxed{120\text{ expected elephant outcomes}}
\]</span></p>
<p>is therefore supported by a complete relational model. The spinner’s regions determine the probability of one outcome. That probability determines the expected contribution of one trial. The same contribution is associated with every repeated trial. Multiplication accumulates those contributions across the collection. The number <span class="math inline">\(120\)</span> is the expected total produced by that accumulation, not a guaranteed arrangement of observed results.</p>
<p>By expanding the compact expression into this structure, the explanation does not replace elementary arithmetic with unnecessary advanced notation. Rather, it makes visible the ideas that the elementary notation has compressed. Once these relationships have been constructed, the learner can return to the short calculation</p>
<p><span class="math display">\[
210\times\frac47=120
\]</span></p>
<p>and perceive within it not merely three numbers and two operators, but an organized probability model.</p>
</section>
<section id="conclusion" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>The probability problem examined in this article appears to require only two computational steps. The learner first identifies the probability of landing on an elephant,</p>
<p><span class="math display">\[
P(\text{elephant})=\frac47,
\]</span></p>
<p>and then multiplies this probability by the number of spins:</p>
<p><span class="math display">\[
210\times\frac47=120.
\]</span></p>
<p>Nothing in the arithmetic is particularly difficult. The numbers divide evenly, the multiplication is familiar, and the completed solution occupies only a few lines. Yet the apparent simplicity of the calculation is produced by compression. The expression <span class="math inline">\(210\times\frac47\)</span> hides a network of roles, references, transformations, and relationships that an experienced solver may recover automatically but that a beginner may never have been helped to construct.</p>
<p>The reasoning begins before multiplication. The number <span class="math inline">\(7\)</span> initially counts the equally likely regions of the spinner, while <span class="math inline">\(4\)</span> counts the regions containing elephants. These quantities belong to the internal possibility structure of one spin. The number <span class="math inline">\(210\)</span> belongs to a different structure: it counts how many times the probability experiment is repeated. Since regions and spins are different objects, their numbers cannot be combined merely because they appear in the same problem. They become related through a chain of reasoning:</p>
<p><span class="math display">\[
\begin{aligned}
&amp;4\text{ of the }7\text{ equally likely regions contain elephants}\\
&amp;\longrightarrow P(\text{elephant on one spin})=\frac47\\
&amp;\longrightarrow \text{each repeated spin is governed by the same probability}\\
&amp;\longrightarrow \text{the probability applies across 210 complete trials}\\
&amp;\longrightarrow \text{the expected elephant count is }210\times\frac47.
\end{aligned}
\]</span></p>
<p>This chain is the relational structure compressed by the conventional solution. If any transition is omitted, the learner must reconstruct it independently. The learner must determine that one spin is one complete probability trial, understand that every new trial reintroduces the spinner’s complete possibility structure, recognize that <span class="math inline">\(\frac47\)</span> becomes a probability because one spin selects one of the seven equally likely regions, and then infer that this one-trial probability can be extended across the complete collection of 210 trials. What appears to the expert as one direct multiplication may therefore require several acts of interpretation from the beginner.</p>
<p>The first major realization was that the phrase “spin 210 times” must be reorganized as 210 complete probability trials. In the language of fractions, these trials may be regarded as 210 wholes, provided that the meaning of <em>whole</em> is carefully preserved. Each whole is one complete instance of the experiment, not one region of the spinner and not a trial in which all seven outcomes occur. Every spin begins with seven possible regions and ends with one observed result. Representing 210 as a collection of complete trials gives the probability <span class="math inline">\(\frac47\)</span> a coherent object across which it can operate.</p>
<p>The second realization concerned the meaning of the answer. The calculation does not produce an unclassified number <span class="math inline">\(120\)</span>. It produces a predicted count of the spins satisfying the condition “lands on an elephant.” The most complete statement of the result is therefore</p>
<p><span class="math display">\[
\boxed{120\text{ spins are expected to land on an elephant}.}
\]</span></p>
<p>The descriptive unit cannot be attached as an afterthought. It helps determine what the calculation is intended to produce. The total quantity consists of 210 spins, while the probability identifies the expected elephant-producing part of that collection. The answer retains the trial as the object being counted and adds the elephant result as the condition defining the selected part. Tracking these meanings performs a function similar to dimensional reasoning in physics: it allows the learner to test whether the result is the kind of quantity requested by the problem.</p>
<p>The third realization was that numerical commutativity does not erase conceptual roles. Formally,</p>
<p><span class="math display">\[
210\times\frac47
=
\frac47\times210.
\]</span></p>
<p>Both expressions produce the same numerical answer and the same expected unit. Nevertheless, they may organize the learner’s thought differently. The expression</p>
<p><span class="math display">\[
\frac47\times210
\]</span></p>
<p>naturally supports the part–whole reading “take four-sevenths of 210 spins.” The expression</p>
<p><span class="math display">\[
210\times\frac47
\]</span></p>
<p>more readily supports the repeated-contribution reading “accumulate an expected contribution of four-sevenths across 210 spins.” The factors may exchange positions without exchanging meanings. The number <span class="math inline">\(210\)</span> continues to represent the collection of trials, and <span class="math inline">\(\frac47\)</span> continues to represent the elephant probability associated with each trial.</p>
<p>This distinction shows why formal properties alone do not determine the most useful explanatory order. Multiplication is commutative at the level of numerical value, but language and mental modeling may distinguish the quantity being transformed from the proportion that transforms it. An explanation should therefore preserve the references of the factors even when algebra permits their written positions to change.</p>
<p>The fourth realization concerned the intermediate result</p>
<p><span class="math display">\[
210\times\frac47
=
30\times4.
\]</span></p>
<p>The familiar instruction “cancel the 7 with 210” describes a symbolic transformation without explaining its semantic foundation. The denominator <span class="math inline">\(7\)</span> first counts spinner regions, whereas <span class="math inline">\(210\)</span> counts spins. Dividing spins directly by regions would produce an incoherent unit. The division becomes meaningful only after the region ratio has been transformed into the dimensionless probability <span class="math inline">\(\frac47\)</span> and that probability has become a proportional operator acting upon the collection of trials.</p>
<p>From the part–whole perspective, the denominator divides the reference collection into seven equal proportional shares:</p>
<p><span class="math display">\[
210\text{ spins}\div7
=
30\text{ spins in each share}.
\]</span></p>
<p>The numerator then selects four shares:</p>
<p><span class="math display">\[
4\times30\text{ spins}
=
120\text{ expected elephant spins}.
\]</span></p>
<p>A second interpretation organizes 210 spins into 30 batches containing seven spins each. This interpretation is also valid, but only after establishing that seven spins have an expected elephant count of four:</p>
<p><span class="math display">\[
7\times\frac47=4.
\]</span></p>
<p>It does not claim that every observed group of seven spins will contain exactly four elephant outcomes. The group contributes four elephants in expectation. The two interpretations produce the same arithmetic but assign different roles to the intermediate number <span class="math inline">\(30\)</span>. In the first, it is the size of one of seven equal shares; in the second, it is the number of seven-spin batches. This again demonstrates that numerical value alone does not determine meaning.</p>
<p>The fifth realization exposed the repeated structure hidden inside multiplication. Every spin contributes either <span class="math inline">\(1\)</span> to the elephant count if it lands on an elephant or <span class="math inline">\(0\)</span> if it does not. Before the outcome is observed, its expected contribution is</p>
<p><span class="math display">\[
1\left(\frac47\right)+0\left(\frac37\right)=\frac47.
\]</span></p>
<p>Applying the same probability model to all 210 trials produces 210 expected contributions:</p>
<p><span class="math display">\[
\underbrace{
\frac47+\frac47+\cdots+\frac47
}_{210\text{ expected contributions}}
=
210\times\frac47
=
120.
\]</span></p>
<p>The broadcasting analogy provides a visual model for this repeated application. The scalar probability <span class="math inline">\(\frac47\)</span> can be imagined as being applied across a vector containing 210 trial positions. This creates a vector of expected contributions, each equal to <span class="math inline">\(\frac47\)</span>, whose sum is <span class="math inline">\(120\)</span>. The analogy does not imply that an actual spin produces a fractional elephant outcome. Observed outcomes remain discrete: every trial contributes either <span class="math inline">\(0\)</span> or <span class="math inline">\(1\)</span>. What is broadcast across the collection is the common probability relationship, not a predetermined result.</p>
<p>These five realizations reveal that understanding the solution requires coordination among several mathematical worlds. The spinner supplies a spatial structure of regions. Fractions express a favorable-to-total relationship within that structure. Probability interprets the fraction as uncertainty concerning the result of one trial. Repeated trials extend that one-trial relationship across a collection. Expected value converts uncertain individual contributions into a predicted total. Multiplication compresses the accumulation, and units or descriptive labels preserve what the resulting number counts.</p>
<p>The complete model may be summarized as follows:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Stage</th>
<th>Object being considered</th>
<th>Relationship constructed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Spinner structure</td>
<td>Seven equally likely regions</td>
<td>Four regions belong to the elephant category</td>
</tr>
<tr class="even">
<td>One-trial probability</td>
<td>One complete spin</td>
<td>The elephant probability is <span class="math inline">\(\frac47\)</span></td>
</tr>
<tr class="odd">
<td>Repeated experiment</td>
<td>210 complete spins</td>
<td>The same probability governs every trial</td>
</tr>
<tr class="even">
<td>Expected contribution</td>
<td>One trial</td>
<td>The expected elephant contribution is <span class="math inline">\(\frac47\)</span></td>
</tr>
<tr class="odd">
<td>Accumulation</td>
<td>210 expected contributions</td>
<td>Their expected sum is <span class="math inline">\(120\)</span></td>
</tr>
<tr class="even">
<td>Final interpretation</td>
<td>Predicted selected trials</td>
<td>120 spins are expected to land on an elephant</td>
</tr>
</tbody>
</table>
<p>This table contains no new computational information. Every number was already present in the short solution. What it contributes is organization. It makes explicit which object is being considered at each stage and which relationship allows reasoning to move to the next stage. In doing so, it transforms a sequence of symbols into a mental model.</p>
<p>The central educational problem is not that conventional instruction uses the compact expression <span class="math inline">\(210\times\frac47\)</span>. Mathematical notation must compress relationships; without such compression, even simple reasoning would become unnecessarily cumbersome. The problem is that learners are often shown only the compressed form and are then expected to recover the structure it represents. They are taught that the probability is <span class="math inline">\(\frac47\)</span>, that the number of trials should be multiplied by the probability, and that the denominator may be cancelled against <span class="math inline">\(210\)</span>. They may not be taught why these actions belong together, what changes when the reasoning moves from regions to trials, or how the unit of the final result is determined.</p>
<p>As a result, a learner may successfully reproduce the procedure without developing a transferable understanding. If the numbers change slightly, if the denominator no longer divides the number of trials evenly, or if the problem is expressed through a different context, the remembered sequence of operations may no longer be sufficient. A relational mental model is more durable because it does not depend upon the surface appearance of this particular example. It tells the learner to identify the probability structure of one trial, determine the collection across which that structure is repeated, preserve the meanings of the quantities, and construct an operation whose result has the type requested by the question.</p>
<p>The purpose of a developed explanation is not to remove all intellectual work from the learner. The learner should still compare representations, recognize proportional relationships, test interpretations, and construct connections. The purpose is to ensure that this work is directed toward the probability model rather than toward repairing unexplained changes in reference. Asking the learner to understand why a region ratio becomes a probability is productive mathematical work. Requiring the learner to guess why a denominator that counted regions has suddenly been treated as if it counted spins is avoidable interpretive repair.</p>
<p>A mathematically correct explanation is therefore not automatically an explanation designed for understanding. Correctness ensures that the formal transformations preserve numerical truth. Explanatory design must additionally ensure that the roles of the quantities remain visible, that changes of interpretation are justified, that corresponding ideas are coordinated across language and notation, and that the learner can reconstruct the intended mental model without having to supply its essential relationships alone.</p>
<p>The final equation remains as short as it was at the beginning:</p>
<p><span class="math display">\[
210\times\frac47=120.
\]</span></p>
<p>Its appearance has not changed. What has changed is what can now be perceived within it. The number <span class="math inline">\(210\)</span> is no longer an isolated count; it represents 210 complete probability trials. The fraction <span class="math inline">\(\frac47\)</span> is no longer merely two numbers arranged vertically; it carries the spinner’s favorable-to-total relationship into the probability of one trial. Multiplication is no longer an unexplained instruction; it scales the complete collection, accumulates expected contributions, and predicts the selected part. The number <span class="math inline">\(120\)</span> is no longer a bare answer; it is the expected number of spins that land on an elephant.</p>
<p>The mathematical expression was always correct. Understanding emerges when the relationships compressed inside it become available for thought.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/hafizarslanamjad\.github\.io\/mathematical-understanding\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Articles by Hafiz Arslan Amjad</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://github.com/hafizarslanamjad/mathematical-understanding">
<p>Source</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>