<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="A chapter about transforming unrestricted numerical scores into nonnegative normalized weights through part-to-whole reasoning, exponentiation, softmax, temperature, and numerically stable computation.">

<title>Chapter 13 — From Scores to Shares – Mathematical Understanding</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../">
<script src="../../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../site_libs/bootstrap/bootstrap-e3adbaa939bcd423dddc8c8a834270b4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../../index.html">
    <span class="navbar-title">Mathematical Understanding</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../index.html"> 
<span class="menu-text">Articles</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../books/mathematical-programming/index.html"> 
<span class="menu-text">Mathematical Programming</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/hafizarslanamjad/mathematical-understanding"> <i class="bi bi-github" role="img" aria-label="GitHub repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#scores-are-not-yet-shares" id="toc-scores-are-not-yet-shares" class="nav-link active" data-scroll-target="#scores-are-not-yet-shares">13.1 Scores Are Not Yet Shares</a>
  <ul class="collapse">
  <li><a href="#a-score-expresses-strength-without-yet-expressing-a-fraction-of-the-whole" id="toc-a-score-expresses-strength-without-yet-expressing-a-fraction-of-the-whole" class="nav-link" data-scroll-target="#a-score-expresses-strength-without-yet-expressing-a-fraction-of-the-whole">A score expresses strength without yet expressing a fraction of the whole</a></li>
  <li><a href="#why-raw-scores-cannot-automatically-be-used-as-weights" id="toc-why-raw-scores-cannot-automatically-be-used-as-weights" class="nav-link" data-scroll-target="#why-raw-scores-cannot-automatically-be-used-as-weights">Why raw scores cannot automatically be used as weights</a></li>
  <li><a href="#scores-may-be-negative" id="toc-scores-may-be-negative" class="nav-link" data-scroll-target="#scores-may-be-negative">Scores may be negative</a></li>
  <li><a href="#summing-to-one-is-necessary-but-not-sufficient" id="toc-summing-to-one-is-necessary-but-not-sufficient" class="nav-link" data-scroll-target="#summing-to-one-is-necessary-but-not-sufficient">Summing to one is necessary but not sufficient</a></li>
  <li><a href="#accidentally-satisfying-the-constraints-does-not-determine-meaning" id="toc-accidentally-satisfying-the-constraints-does-not-determine-meaning" class="nav-link" data-scroll-target="#accidentally-satisfying-the-constraints-does-not-determine-meaning">Accidentally satisfying the constraints does not determine meaning</a></li>
  <li><a href="#scores-live-in-a-different-mathematical-space" id="toc-scores-live-in-a-different-mathematical-space" class="nav-link" data-scroll-target="#scores-live-in-a-different-mathematical-space">Scores live in a different mathematical space</a></li>
  <li><a href="#a-share-is-relational-rather-than-isolated" id="toc-a-share-is-relational-rather-than-isolated" class="nav-link" data-scroll-target="#a-share-is-relational-rather-than-isolated">A share is relational rather than isolated</a></li>
  <li><a href="#hard-selection-and-soft-allocation-answer-different-questions" id="toc-hard-selection-and-soft-allocation-answer-different-questions" class="nav-link" data-scroll-target="#hard-selection-and-soft-allocation-answer-different-questions">Hard selection and soft allocation answer different questions</a></li>
  <li><a href="#what-should-a-score-to-weight-transformation-preserve" id="toc-what-should-a-score-to-weight-transformation-preserve" class="nav-link" data-scroll-target="#what-should-a-score-to-weight-transformation-preserve">What should a score-to-weight transformation preserve?</a></li>
  <li><a href="#the-machine-learning-meaning-of-a-score" id="toc-the-machine-learning-meaning-of-a-score" class="nav-link" data-scroll-target="#the-machine-learning-meaning-of-a-score">The machine-learning meaning of a score</a></li>
  <li><a href="#from-unconstrained-evidence-to-constrained-allocation" id="toc-from-unconstrained-evidence-to-constrained-allocation" class="nav-link" data-scroll-target="#from-unconstrained-evidence-to-constrained-allocation">From unconstrained evidence to constrained allocation</a></li>
  </ul></li>
  <li><a href="#normalization-as-division-by-a-total" id="toc-normalization-as-division-by-a-total" class="nav-link" data-scroll-target="#normalization-as-division-by-a-total">13.2 Normalization as Division by a Total</a>
  <ul class="collapse">
  <li><a href="#constructing-shares-from-amounts" id="toc-constructing-shares-from-amounts" class="nav-link" data-scroll-target="#constructing-shares-from-amounts">Constructing shares from amounts</a></li>
  <li><a href="#why-the-normalized-values-sum-to-one" id="toc-why-the-normalized-values-sum-to-one" class="nav-link" data-scroll-target="#why-the-normalized-values-sum-to-one">Why the normalized values sum to one</a></li>
  <li><a href="#why-nonnegative-inputs-produce-nonnegative-shares" id="toc-why-nonnegative-inputs-produce-nonnegative-shares" class="nav-link" data-scroll-target="#why-nonnegative-inputs-produce-nonnegative-shares">Why nonnegative inputs produce nonnegative shares</a></li>
  <li><a href="#normalization-removes-units" id="toc-normalization-removes-units" class="nav-link" data-scroll-target="#normalization-removes-units">Normalization removes units</a></li>
  <li><a href="#normalization-preserves-ratios" id="toc-normalization-preserves-ratios" class="nav-link" data-scroll-target="#normalization-preserves-ratios">Normalization preserves ratios</a></li>
  <li><a href="#scale-invariance" id="toc-scale-invariance" class="nav-link" data-scroll-target="#scale-invariance">Scale invariance</a></li>
  <li><a href="#normalization-is-not-invariant-to-addition" id="toc-normalization-is-not-invariant-to-addition" class="nav-link" data-scroll-target="#normalization-is-not-invariant-to-addition">Normalization is not invariant to addition</a></li>
  <li><a href="#normalization-is-idempotent" id="toc-normalization-is-idempotent" class="nav-link" data-scroll-target="#normalization-is-idempotent">Normalization is idempotent</a></li>
  <li><a href="#normalizing-strengths-before-constructing-a-weighted-result" id="toc-normalizing-strengths-before-constructing-a-weighted-result" class="nav-link" data-scroll-target="#normalizing-strengths-before-constructing-a-weighted-result">Normalizing strengths before constructing a weighted result</a></li>
  <li><a href="#implementing-ordinary-normalization" id="toc-implementing-ordinary-normalization" class="nav-link" data-scroll-target="#implementing-ordinary-normalization">Implementing ordinary normalization</a></li>
  <li><a href="#failure-when-the-total-is-zero" id="toc-failure-when-the-total-is-zero" class="nav-link" data-scroll-target="#failure-when-the-total-is-zero">Failure when the total is zero</a></li>
  <li><a href="#negative-values-may-produce-negative-weights" id="toc-negative-values-may-produce-negative-weights" class="nav-link" data-scroll-target="#negative-values-may-produce-negative-weights">Negative values may produce negative weights</a></li>
  <li><a href="#a-negative-total-can-reverse-the-ordering" id="toc-a-negative-total-can-reverse-the-ordering" class="nav-link" data-scroll-target="#a-negative-total-can-reverse-the-ordering">A negative total can reverse the ordering</a></li>
  <li><a href="#cancellation-creates-extreme-instability" id="toc-cancellation-creates-extreme-instability" class="nav-link" data-scroll-target="#cancellation-creates-extreme-instability">Cancellation creates extreme instability</a></li>
  <li><a href="#dividing-by-absolute-magnitude-solves-a-different-problem" id="toc-dividing-by-absolute-magnitude-solves-a-different-problem" class="nav-link" data-scroll-target="#dividing-by-absolute-magnitude-solves-a-different-problem">Dividing by absolute magnitude solves a different problem</a></li>
  <li><a href="#normalization-is-not-the-same-as-standardization" id="toc-normalization-is-not-the-same-as-standardization" class="nav-link" data-scroll-target="#normalization-is-not-the-same-as-standardization">Normalization is not the same as standardization</a></li>
  <li><a href="#why-shifting-the-scores-is-not-a-complete-solution" id="toc-why-shifting-the-scores-is-not-a-complete-solution" class="nav-link" data-scroll-target="#why-shifting-the-scores-is-not-a-complete-solution">Why shifting the scores is not a complete solution</a></li>
  <li><a href="#the-exact-achievement-and-limitation-of-ordinary-normalization" id="toc-the-exact-achievement-and-limitation-of-ordinary-normalization" class="nav-link" data-scroll-target="#the-exact-achievement-and-limitation-of-ordinary-normalization">The exact achievement and limitation of ordinary normalization</a></li>
  </ul></li>
  <li><a href="#why-exponentiation-precedes-normalization" id="toc-why-exponentiation-precedes-normalization" class="nav-link" data-scroll-target="#why-exponentiation-precedes-normalization">13.3 Why Exponentiation Precedes Normalization</a>
  <ul class="collapse">
  <li><a href="#the-first-requirement-every-transformed-strength-must-be-positive" id="toc-the-first-requirement-every-transformed-strength-must-be-positive" class="nav-link" data-scroll-target="#the-first-requirement-every-transformed-strength-must-be-positive">The first requirement: every transformed strength must be positive</a></li>
  <li><a href="#exponentiation-preserves-the-ordering-of-scores" id="toc-exponentiation-preserves-the-ordering-of-scores" class="nav-link" data-scroll-target="#exponentiation-preserves-the-ordering-of-scores">Exponentiation preserves the ordering of scores</a></li>
  <li><a href="#why-absolute-value-is-not-sufficient" id="toc-why-absolute-value-is-not-sufficient" class="nav-link" data-scroll-target="#why-absolute-value-is-not-sufficient">Why absolute value is not sufficient</a></li>
  <li><a href="#why-squaring-is-not-sufficient" id="toc-why-squaring-is-not-sufficient" class="nav-link" data-scroll-target="#why-squaring-is-not-sufficient">Why squaring is not sufficient</a></li>
  <li><a href="#why-clipping-is-not-sufficient" id="toc-why-clipping-is-not-sufficient" class="nav-link" data-scroll-target="#why-clipping-is-not-sufficient">Why clipping is not sufficient</a></li>
  <li><a href="#why-an-arbitrary-shift-is-not-sufficient" id="toc-why-an-arbitrary-shift-is-not-sufficient" class="nav-link" data-scroll-target="#why-an-arbitrary-shift-is-not-sufficient">Why an arbitrary shift is not sufficient</a></li>
  <li><a href="#the-deeper-requirement-relative-weights-should-depend-on-score-differences" id="toc-the-deeper-requirement-relative-weights-should-depend-on-score-differences" class="nav-link" data-scroll-target="#the-deeper-requirement-relative-weights-should-depend-on-score-differences">The deeper requirement: relative weights should depend on score differences</a></li>
  <li><a href="#exponentiation-converts-differences-into-ratios" id="toc-exponentiation-converts-differences-into-ratios" class="nav-link" data-scroll-target="#exponentiation-converts-differences-into-ratios">Exponentiation converts differences into ratios</a></li>
  <li><a href="#why-the-exponential-arises-from-the-difference-requirement" id="toc-why-the-exponential-arises-from-the-difference-requirement" class="nav-link" data-scroll-target="#why-the-exponential-arises-from-the-difference-requirement">Why the exponential arises from the difference requirement</a></li>
  <li><a href="#common-score-shifts-disappear" id="toc-common-score-shifts-disappear" class="nav-link" data-scroll-target="#common-score-shifts-disappear">Common score shifts disappear</a></li>
  <li><a href="#a-complete-numerical-example" id="toc-a-complete-numerical-example" class="nav-link" data-scroll-target="#a-complete-numerical-example">A complete numerical example</a></li>
  <li><a href="#equal-scores-produce-uniform-weights" id="toc-equal-scores-produce-uniform-weights" class="nav-link" data-scroll-target="#equal-scores-produce-uniform-weights">Equal scores produce uniform weights</a></li>
  <li><a href="#exponentiation-accentuates-score-differences" id="toc-exponentiation-accentuates-score-differences" class="nav-link" data-scroll-target="#exponentiation-accentuates-score-differences">Exponentiation accentuates score differences</a></li>
  <li><a href="#why-the-base-is-usually-e" id="toc-why-the-base-is-usually-e" class="nav-link" data-scroll-target="#why-the-base-is-usually-e">Why the base is usually (e)</a></li>
  <li><a href="#implementing-the-two-stages-directly" id="toc-implementing-the-two-stages-directly" class="nav-link" data-scroll-target="#implementing-the-two-stages-directly">Implementing the two stages directly</a></li>
  <li><a href="#what-exponentiation-contributes" id="toc-what-exponentiation-contributes" class="nav-link" data-scroll-target="#what-exponentiation-contributes">What exponentiation contributes</a></li>
  </ul></li>
  <li><a href="#softmax-as-a-smooth-allocation-mechanism" id="toc-softmax-as-a-smooth-allocation-mechanism" class="nav-link" data-scroll-target="#softmax-as-a-smooth-allocation-mechanism">13.4 Softmax as a Smooth Allocation Mechanism</a>
  <ul class="collapse">
  <li><a href="#from-hard-selection-to-soft-selection" id="toc-from-hard-selection-to-soft-selection" class="nav-link" data-scroll-target="#from-hard-selection-to-soft-selection">From hard selection to soft selection</a></li>
  <li><a href="#why-smooth-allocation-matters" id="toc-why-smooth-allocation-matters" class="nav-link" data-scroll-target="#why-smooth-allocation-matters">Why smooth allocation matters</a></li>
  <li><a href="#softmax-creates-competition-through-a-shared-denominator" id="toc-softmax-creates-competition-through-a-shared-denominator" class="nav-link" data-scroll-target="#softmax-creates-competition-through-a-shared-denominator">Softmax creates competition through a shared denominator</a></li>
  <li><a href="#the-derivative-exposes-the-competitive-structure" id="toc-the-derivative-exposes-the-competitive-structure" class="nav-link" data-scroll-target="#the-derivative-exposes-the-competitive-structure">The derivative exposes the competitive structure</a></li>
  <li><a href="#equal-scores-close-scores-and-separated-scores" id="toc-equal-scores-close-scores-and-separated-scores" class="nav-link" data-scroll-target="#equal-scores-close-scores-and-separated-scores">Equal scores, close scores, and separated scores</a></li>
  <li><a href="#temperature-controls-the-concentration-of-the-allocation" id="toc-temperature-controls-the-concentration-of-the-allocation" class="nav-link" data-scroll-target="#temperature-controls-the-concentration-of-the-allocation">Temperature controls the concentration of the allocation</a></li>
  <li><a href="#why-the-direct-implementation-can-overflow" id="toc-why-the-direct-implementation-can-overflow" class="nav-link" data-scroll-target="#why-the-direct-implementation-can-overflow">Why the direct implementation can overflow</a></li>
  <li><a href="#shift-invariance-produces-numerical-stability" id="toc-shift-invariance-produces-numerical-stability" class="nav-link" data-scroll-target="#shift-invariance-produces-numerical-stability">Shift invariance produces numerical stability</a></li>
  <li><a href="#stable-softmax-with-temperature" id="toc-stable-softmax-with-temperature" class="nav-link" data-scroll-target="#stable-softmax-with-temperature">Stable softmax with temperature</a></li>
  <li><a href="#softmax-across-a-batch" id="toc-softmax-across-a-batch" class="nav-link" data-scroll-target="#softmax-across-a-batch">Softmax across a batch</a></li>
  <li><a href="#softmax-in-multiclass-classification" id="toc-softmax-in-multiclass-classification" class="nav-link" data-scroll-target="#softmax-in-multiclass-classification">Softmax in multiclass classification</a></li>
  <li><a href="#probability-shaped-output-is-not-automatically-trustworthy-probability" id="toc-probability-shaped-output-is-not-automatically-trustworthy-probability" class="nav-link" data-scroll-target="#probability-shaped-output-is-not-automatically-trustworthy-probability">Probability-shaped output is not automatically trustworthy probability</a></li>
  <li><a href="#softmax-in-attention" id="toc-softmax-in-attention" class="nav-link" data-scroll-target="#softmax-in-attention">Softmax in attention</a></li>
  <li><a href="#what-softmax-preserves-and-what-it-discards" id="toc-what-softmax-preserves-and-what-it-discards" class="nav-link" data-scroll-target="#what-softmax-preserves-and-what-it-discards">What softmax preserves and what it discards</a></li>
  <li><a href="#chapter-conclusion" id="toc-chapter-conclusion" class="nav-link" data-scroll-target="#chapter-conclusion">Chapter conclusion</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Chapter 13 — From Scores to Shares</h1>
<p class="subtitle lead">Normalization, Exponentiation, and Softmax</p>
</div>

<div>
  <div class="description">
    A chapter about transforming unrestricted numerical scores into nonnegative normalized weights through part-to-whole reasoning, exponentiation, softmax, temperature, and numerically stable computation.
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="scores-are-not-yet-shares" class="level2">
<h2 class="anchored" data-anchor-id="scores-are-not-yet-shares">13.1 Scores Are Not Yet Shares</h2>
<p>Chapter 12 studied computations of the form</p>
<p><span class="math display">\[
C=\sum_{i=1}^{n}w_iA_i,
\]</span></p>
<p>where each <span class="math inline">\(A_i\)</span> is an alternative and each <span class="math inline">\(w_i\)</span> determines how strongly that alternative contributes to the result. When the weights satisfy</p>
<p><span class="math display">\[
w_i\geq 0
\qquad\text{and}\qquad
\sum_{i=1}^{n}w_i=1,
\]</span></p>
<p>they divide one unit of total contribution among the alternatives. This interpretation gives the weights a specific mathematical role. They are not merely numbers placed beside the alternatives. They are shares of a conserved whole. Suppose three alternatives receive the weights</p>
<p><span class="math display">\[
\mathbf{w}
=
\begin{bmatrix}
0.2\\
0.5\\
0.3
\end{bmatrix}.
\]</span></p>
<p>The first alternative receives <span class="math inline">\(20\%\)</span> of the total influence, the second receives <span class="math inline">\(50\%\)</span>, and the third receives <span class="math inline">\(30\%\)</span>. Since</p>
<p><span class="math display">\[
0.2+0.5+0.3=1,
\]</span></p>
<p>the complete unit of influence has been allocated. A computational system, however, rarely begins by directly producing these shares. It commonly begins with numbers such as</p>
<p><span class="math display">\[
\mathbf{s}
=
\begin{bmatrix}
2\\
5\\
3
\end{bmatrix}.
\]</span></p>
<p>These numbers may indicate that the second alternative is supported more strongly than the third and that the third is supported more strongly than the first i.e <span class="math inline">\(s_2&gt;s_3&gt;s_1.\)</span> They provide an ordering, but they do not yet explain how a total contribution should be divided. The vector</p>
<p><span class="math display">\[
\begin{bmatrix}
2\\
5\\
3
\end{bmatrix}
\]</span></p>
<p>contains scores. The vector</p>
<p><span class="math display">\[
\begin{bmatrix}
0.2\\
0.5\\
0.3
\end{bmatrix}
\]</span></p>
<p>contains shares. Their numerical resemblance should not conceal their different mathematical roles.</p>
<p><span class="math display">\[
\boxed{
\text{Scores compare alternatives; weights allocate contribution among alternatives.}
}
\]</span></p>
<section id="a-score-expresses-strength-without-yet-expressing-a-fraction-of-the-whole" class="level3">
<h3 class="anchored" data-anchor-id="a-score-expresses-strength-without-yet-expressing-a-fraction-of-the-whole">A score expresses strength without yet expressing a fraction of the whole</h3>
<p>Suppose a system must evaluate three possible explanations for an observation. After examining the input, it assigns the scores</p>
<p><span class="math display">\[
s_1=2,\qquad s_2=5,\qquad s_3=3.
\]</span></p>
<p>The score <span class="math inline">\(5\)</span> indicates stronger support than the score <span class="math inline">\(3\)</span>, while the score <span class="math inline">\(3\)</span> indicates stronger support than the score <span class="math inline">\(2\)</span>. The scores therefore provide a ranking:</p>
<p><span class="math display">\[
A_2 \succ A_3 \succ A_1.
\]</span></p>
<p>The symbol <span class="math inline">\(\succ\)</span> means “is preferred to” or “receives stronger support than.” This ranking is meaningful even before we decide what proportion of influence each alternative should receive. If the task requires a hard choice, the system can select the largest score:</p>
<p><span class="math display">\[
k=\operatorname*{arg\,max}_{i}s_i.
\]</span></p>
<p>For the present scores,</p>
<p><span class="math display">\[
\operatorname*{arg\,max}_{i}s_i=2,
\]</span></p>
<p>so the selected alternative is <span class="math inline">\(A_2\)</span>. This operation uses the scores comparatively. It asks which position contains the largest value. It does not require the scores to be probabilities or normalized weights. In Python, the hard selection can be implemented as follows:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>scores <span class="op">=</span> np.array([<span class="fl">2.0</span>, <span class="fl">5.0</span>, <span class="fl">3.0</span>])</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>selected_index <span class="op">=</span> np.argmax(scores)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(selected_index)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The output is</p>
<pre class="text"><code>1</code></pre>
<p>because Python uses zero-based indexing. Index <code>1</code> corresponds to the second mathematical position, whose score is <span class="math inline">\(5\)</span>. If the alternatives are stored explicitly, the selected alternative can be recovered from the same index:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>alternatives <span class="op">=</span> np.array([<span class="fl">20.0</span>, <span class="fl">50.0</span>, <span class="fl">80.0</span>])</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>selected_index <span class="op">=</span> np.argmax(scores)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>selected_alternative <span class="op">=</span> alternatives[selected_index]</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(selected_alternative)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The result is</p>
<pre class="text"><code>50.0</code></pre>
<p>The score vector has performed hard selection. Only the ordering matters. If the task instead requires a graded combination, the system must answer a different question. It must determine not merely which alternative is strongest, but how the total influence should be distributed:</p>
<p><span class="math display">\[
C=w_1A_1+w_2A_2+w_3A_3.
\]</span></p>
<p>The ranking</p>
<p><span class="math display">\[
s_2&gt;s_3&gt;s_1
\]</span></p>
<p>suggests that a reasonable transformation should produce</p>
<p><span class="math display">\[
w_2&gt;w_3&gt;w_1.
\]</span></p>
<p>But the ranking alone does not determine the numerical weights uniquely. All of the following weight vectors preserve the same ordering:</p>
<p><span class="math display">\[
\begin{bmatrix}
0.2\\
0.5\\
0.3
\end{bmatrix},
\qquad
\begin{bmatrix}
0.05\\
0.80\\
0.15
\end{bmatrix},
\qquad
\begin{bmatrix}
0.30\\
0.36\\
0.34
\end{bmatrix}.
\]</span></p>
<p>Each vector assigns the greatest weight to the second alternative, the next greatest weight to the third, and the smallest weight to the first. Nevertheless, they describe very different allocations. The first allocation moderately favors <span class="math inline">\(A_2\)</span>. The second strongly concentrates the contribution on <span class="math inline">\(A_2\)</span>. The third distributes the contribution almost evenly. Therefore, a score-to-weight transformation must determine more than order. It must also determine how score differences control the concentration of the resulting shares.</p>
</section>
<section id="why-raw-scores-cannot-automatically-be-used-as-weights" class="level3">
<h3 class="anchored" data-anchor-id="why-raw-scores-cannot-automatically-be-used-as-weights">Why raw scores cannot automatically be used as weights</h3>
<p>Consider alternatives</p>
<p><span class="math display">\[
A_1=20,\qquad A_2=50,\qquad A_3=80
\]</span></p>
<p>and scores</p>
<p><span class="math display">\[
s_1=2,\qquad s_2=5,\qquad s_3=3.
\]</span></p>
<p>If the scores are inserted directly into a weighted sum, the result is</p>
<p><span class="math display">\[
2(20)+5(50)+3(80)
=
40+250+240
=
530.
\]</span></p>
<p>This calculation is mathematically valid as a weighted sum:</p>
<p><span class="math display">\[
S=\sum_{i=1}^{3}s_iA_i.
\]</span></p>
<p>But it is not a weighted average because</p>
<p><span class="math display">\[
2+5+3=10\neq 1.
\]</span></p>
<p>The coefficients allocate ten units of total contribution rather than one. Consequently, the result is not constrained to remain between the smallest and largest alternatives:</p>
<p><span class="math display">\[
20\leq C\leq 80.
\]</span></p>
<p>Indeed,</p>
<p><span class="math display">\[
530&gt;80.
\]</span></p>
<p>Nothing is wrong with the arithmetic. The problem is interpretive. The numbers <span class="math inline">\(2\)</span>, <span class="math inline">\(5\)</span>, and <span class="math inline">\(3\)</span> have been used as though they were shares even though they do not satisfy the structure required of shares. This distinction resembles the difference between an amount and a proportion. Suppose three containers contain</p>
<p><span class="math display">\[
2,\qquad 5,\qquad 3
\]</span></p>
<p>litres of water. These amounts sum to</p>
<p><span class="math display">\[
2+5+3=10\text{ litres}.
\]</span></p>
<p>The first container holds <span class="math inline">\(2\)</span> litres, but its share of the total water is</p>
<p><span class="math display">\[
\frac{2}{10}=0.2.
\]</span></p>
<p>Similarly, the second and third shares are</p>
<p><span class="math display">\[
\frac{5}{10}=0.5
\qquad\text{and}\qquad
\frac{3}{10}=0.3.
\]</span></p>
<p>The amounts and the shares contain related information, but they are not the same objects:</p>
<p><span class="math display">\[
\boxed{
\text{share of an amount}
=
\frac{\text{individual amount}}{\text{total amount}}.
}
\]</span></p>
<p>The vector</p>
<p><span class="math display">\[
\begin{bmatrix}
2\\
5\\
3
\end{bmatrix}
\]</span></p>
<p>describes how much is present in each position. The vector</p>
<p><span class="math display">\[
\begin{bmatrix}
0.2\\
0.5\\
0.3
\end{bmatrix}
\]</span></p>
<p>describes how the whole is divided among those positions. This suggests division by a total, which will be developed carefully in Section 13.2. Before adopting that construction, however, we must understand why arbitrary scores create additional difficulties.</p>
</section>
<section id="scores-may-be-negative" class="level3">
<h3 class="anchored" data-anchor-id="scores-may-be-negative">Scores may be negative</h3>
<p>Many computational scoring mechanisms produce negative values. A linear model, for example, may calculate a score from an input vector <span class="math inline">\(\mathbf{x}\)</span> using</p>
<p><span class="math display">\[
s_i=\mathbf{a}_i^\mathsf{T}\mathbf{x}+b_i.
\]</span></p>
<p>Because dot products and biases can produce any real number, the result may be</p>
<p><span class="math display">\[
\mathbf{s}
=
\begin{bmatrix}
-2\\
1\\
3
\end{bmatrix}.
\]</span></p>
<p>These scores remain meaningful as comparative assessments:</p>
<p><span class="math display">\[
3&gt;1&gt;-2.
\]</span></p>
<p>The third alternative receives the strongest support, while the first receives the weakest. But the negative score cannot directly represent a nonnegative share. If we attempted to use the scores as mixture proportions, we would obtain</p>
<p><span class="math display">\[
-2A_1+1A_2+3A_3.
\]</span></p>
<p>The coefficient <span class="math inline">\(-2\)</span> would mean that the first alternative contributes negative two units of the mixture. Such coefficients may be perfectly meaningful in a general linear combination, where subtraction is allowed, but they do not describe an ordinary allocation of a positive whole. This reveals a hierarchy of mathematical structures:</p>
<p><span class="math display">\[
\boxed{
\begin{aligned}
\text{linear combination:}\quad
&amp;C=\sum_i a_iA_i,
&amp;&amp;a_i\in\mathbb{R},\\[4pt]
\text{affine combination:}\quad
&amp;C=\sum_i a_iA_i,
&amp;&amp;\sum_i a_i=1,\\[4pt]
\text{convex combination:}\quad
&amp;C=\sum_i w_iA_i,
&amp;&amp;w_i\geq 0,\quad \sum_iw_i=1.
\end{aligned}
}
\]</span></p>
<p>Every convex combination is an affine combination, and every affine combination is a linear combination. The reverse implications do not generally hold. Scores may serve as coefficients in a linear combination, but this does not make them valid coefficients for a convex combination. To become shares, they must satisfy the stronger convex conditions.</p>
</section>
<section id="summing-to-one-is-necessary-but-not-sufficient" class="level3">
<h3 class="anchored" data-anchor-id="summing-to-one-is-necessary-but-not-sufficient">Summing to one is necessary but not sufficient</h3>
<p>It might appear that the only problem is the total. If the coefficients sum to one, perhaps they can always be interpreted as shares. Consider</p>
<p><span class="math display">\[
\mathbf{s}
=
\begin{bmatrix}
2\\
-1\\
0
\end{bmatrix}.
\]</span></p>
<p>The entries satisfy</p>
<p><span class="math display">\[
2+(-1)+0=1.
\]</span></p>
<p>Yet the vector does not represent an ordinary division of one whole because one component is negative and another exceeds the whole:</p>
<p><span class="math display">\[
s_2=-1&lt;0,
\qquad
s_1=2&gt;1.
\]</span></p>
<p>The equation</p>
<p><span class="math display">\[
2A_1-A_2
\]</span></p>
<p>is an affine combination, but not a convex combination. For a finite collection of weights, the two essential conditions are therefore</p>
<p><span class="math display">\[
\sum_iw_i=1
\]</span></p>
<p>and</p>
<p><span class="math display">\[
w_i\geq 0
\quad\text{for every }i.
\]</span></p>
<p>Together, these conditions also imply</p>
<p><span class="math display">\[
0\leq w_i\leq 1.
\]</span></p>
<p>To see why, suppose some weight <span class="math inline">\(w_k\)</span> exceeded one. Since all the other weights are nonnegative,</p>
<p><span class="math display">\[
\sum_iw_i
\geq w_k
&gt;1,
\]</span></p>
<p>which would contradict</p>
<p><span class="math display">\[
\sum_iw_i=1.
\]</span></p>
<p>Thus, the upper bound does not need to be imposed separately. Nonnegativity and a unit total already guarantee it.</p>
</section>
<section id="accidentally-satisfying-the-constraints-does-not-determine-meaning" class="level3">
<h3 class="anchored" data-anchor-id="accidentally-satisfying-the-constraints-does-not-determine-meaning">Accidentally satisfying the constraints does not determine meaning</h3>
<p>Suppose a scoring system produces</p>
<p><span class="math display">\[
\mathbf{s}
=
\begin{bmatrix}
0.2\\
0.5\\
0.3
\end{bmatrix}.
\]</span></p>
<p>Numerically, this vector is already nonnegative and sums to one. It therefore belongs to the simplex and can mathematically serve as a weight vector. But its numerical form does not by itself prove that the system intended its values to be probabilities or shares. A score is defined not only by its current values but also by the process that produced it and the role it plays in the model. The next input might produce</p>
<p><span class="math display">\[
\begin{bmatrix}
1.7\\
-0.4\\
2.1
\end{bmatrix}.
\]</span></p>
<p>If the scoring mechanism has no rule guaranteeing nonnegativity and a unit total, then its outputs are not generally normalized weights. The first output merely happened to satisfy the constraints.</p>
<p>This is the same distinction that appears throughout mathematical modeling: observing that an object possesses a property in one example is different from constructing a mechanism that guarantees the property in every permitted case. A proper score-to-weight transformation must provide a guarantee:</p>
<p><span class="math display">\[
\boxed{
\text{For every permitted score vector, the output must be a valid weight vector.}
}
\]</span></p>
</section>
<section id="scores-live-in-a-different-mathematical-space" class="level3">
<h3 class="anchored" data-anchor-id="scores-live-in-a-different-mathematical-space">Scores live in a different mathematical space</h3>
<p>An unrestricted score vector has the form</p>
<p><span class="math display">\[
\mathbf{s}
=
(s_1,s_2,\ldots,s_n)
\in\mathbb{R}^n.
\]</span></p>
<p>Every coordinate may independently take any real value. Geometrically, the vector may occupy any point in <span class="math inline">\(n\)</span>-dimensional real space. A valid weight vector belongs to the simplex</p>
<p><span class="math display">\[
\Delta^{n-1}
=
\left\{
\mathbf{w}\in\mathbb{R}^n:
w_i\geq 0,\;
\sum_{i=1}^{n}w_i=1
\right\}.
\]</span></p>
<p>For three alternatives, the score vector belongs to <span class="math inline">\(\mathbb{R}^3\)</span>, while the weight vector belongs to</p>
<p><span class="math display">\[
\Delta^2
=
\left\{
(w_1,w_2,w_3):
w_i\geq 0,\;
w_1+w_2+w_3=1
\right\}.
\]</span></p>
<p>Although the weight vector has three coordinates, only two coordinates can be chosen independently. Once <span class="math inline">\(w_1\)</span> and <span class="math inline">\(w_2\)</span> are known, the third is determined:</p>
<p><span class="math display">\[
w_3=1-w_1-w_2.
\]</span></p>
<p>The unit-sum condition removes one degree of freedom. This is why the set is denoted by <span class="math inline">\(\Delta^2\)</span> rather than <span class="math inline">\(\Delta^3\)</span>. A normalization mechanism is therefore a function</p>
<p><span class="math display">\[
N:\mathbb{R}^n\longrightarrow\Delta^{n-1}.
\]</span></p>
<p>It receives an unrestricted vector and returns a constrained vector:</p>
<p><span class="math display">\[
\mathbf{w}=N(\mathbf{s}).
\]</span></p>
<p>This transformation does not merely rescale isolated numbers. It creates a relationship among all positions. The weight assigned to one alternative depends not only on its own score but also on the scores assigned to the competing alternatives. This dependence is unavoidable because every weight is a share of a common total.</p>
</section>
<section id="a-share-is-relational-rather-than-isolated" class="level3">
<h3 class="anchored" data-anchor-id="a-share-is-relational-rather-than-isolated">A share is relational rather than isolated</h3>
<p>Suppose the first alternative has score</p>
<p><span class="math display">\[
s_1=2.
\]</span></p>
<p>Can we determine its weight from this number alone? The answer is no. Consider two score vectors:</p>
<p><span class="math display">\[
\mathbf{s}^{(a)}
=
\begin{bmatrix}
2\\
1\\
1
\end{bmatrix},
\qquad
\mathbf{s}^{(b)}
=
\begin{bmatrix}
2\\
10\\
10
\end{bmatrix}.
\]</span></p>
<p>The first score is <span class="math inline">\(2\)</span> in both vectors. Nevertheless, its relative position has changed. In the first vector, the score <span class="math inline">\(2\)</span> is the largest:</p>
<p><span class="math display">\[
2&gt;1.
\]</span></p>
<p>In the second vector, it is the smallest:</p>
<p><span class="math display">\[
2&lt;10.
\]</span></p>
<p>A sensible allocation mechanism should not assign the same weight to the first alternative in both cases merely because its individual score remained <span class="math inline">\(2\)</span>. Its contribution must be interpreted relative to the entire collection. This is the defining nature of a share. A share does not describe an isolated amount; it describes an amount in relation to a whole. If</p>
<p><span class="math display">\[
w_i=\frac{a_i}{\sum_ja_j},
\]</span></p>
<p>then changing some other amount <span class="math inline">\(a_k\)</span> changes the denominator and therefore changes <span class="math inline">\(w_i\)</span>, even when <span class="math inline">\(a_i\)</span> remains fixed. The alternatives are coupled through the shared total.</p>
<p><span class="math display">\[
\boxed{
\text{Normalization turns independently stated strengths into mutually dependent shares.}
}
\]</span></p>
<p>Increasing the share of one alternative must be balanced by decreases elsewhere because the total remains fixed:</p>
<p><span class="math display">\[
\sum_iw_i=1.
\]</span></p>
<p>If the weights change from <span class="math inline">\(\mathbf{w}\)</span> to <span class="math inline">\(\mathbf{w}+\Delta\mathbf{w}\)</span>, then</p>
<p><span class="math display">\[
\sum_i(w_i+\Delta w_i)=1.
\]</span></p>
<p>Since</p>
<p><span class="math display">\[
\sum_iw_i=1,
\]</span></p>
<p>it follows that</p>
<p><span class="math display">\[
\sum_i\Delta w_i=0.
\]</span></p>
<p>The total change across all weights must be zero. Weight cannot be created in one position without being removed, directly or indirectly, from other positions.</p>
</section>
<section id="hard-selection-and-soft-allocation-answer-different-questions" class="level3">
<h3 class="anchored" data-anchor-id="hard-selection-and-soft-allocation-answer-different-questions">Hard selection and soft allocation answer different questions</h3>
<p>Given scores</p>
<p><span class="math display">\[
s_1,s_2,\ldots,s_n,
\]</span></p>
<p>hard selection asks</p>
<p><span class="math display">\[
k=\operatorname*{arg\,max}_i s_i.
\]</span></p>
<p>The result is an index. It identifies the winning alternative. This decision can be represented by a one-hot vector:</p>
<p><span class="math display">\[
I_i=
\begin{cases}
1, &amp; i=k,\\
0, &amp; i\neq k.
\end{cases}
\]</span></p>
<p>The selected result is then</p>
<p><span class="math display">\[
C_{\text{hard}}
=
\sum_{i=1}^{n}I_iA_i
=
A_k.
\]</span></p>
<p>Soft allocation instead constructs graded weights:</p>
<p><span class="math display">\[
w_i\geq 0,
\qquad
\sum_iw_i=1,
\]</span></p>
<p>and produces</p>
<p><span class="math display">\[
C_{\text{soft}}
=
\sum_{i=1}^{n}w_iA_i.
\]</span></p>
<p>Hard selection preserves only the identity of the largest score. It discards the sizes of the differences among the scores. For example, consider</p>
<p><span class="math display">\[
\mathbf{s}^{(a)}
=
\begin{bmatrix}
5.0\\
4.9\\
1.0
\end{bmatrix}
\]</span></p>
<p>and</p>
<p><span class="math display">\[
\mathbf{s}^{(b)}
=
\begin{bmatrix}
50\\
1\\
0
\end{bmatrix}.
\]</span></p>
<p>In both cases,</p>
<p><span class="math display">\[
\operatorname*{arg\,max}_i s_i=1.
\]</span></p>
<p>Hard selection treats both vectors identically: the first alternative wins. But the relationships among the scores are very different. In the first vector, the first and second alternatives are nearly tied:</p>
<p><span class="math display">\[
5.0-4.9=0.1.
\]</span></p>
<p>In the second vector, the first alternative dominates the second:</p>
<p><span class="math display">\[
50-1=49.
\]</span></p>
<p>A soft transformation can preserve information about these differences by producing a diffuse allocation for the near tie and a concentrated allocation for the decisive separation. This is one reason soft weighting is useful in machine learning. It allows the system to express degrees of comparative support rather than immediately collapsing every competition into a single winner.</p>
</section>
<section id="what-should-a-score-to-weight-transformation-preserve" class="level3">
<h3 class="anchored" data-anchor-id="what-should-a-score-to-weight-transformation-preserve">What should a score-to-weight transformation preserve?</h3>
<p>We can now derive the basic requirements of a transformation</p>
<p><span class="math display">\[
N:\mathbb{R}^n\longrightarrow\Delta^{n-1}.
\]</span></p>
<p>Let</p>
<p><span class="math display">\[
\mathbf{w}=N(\mathbf{s}).
\]</span></p>
<p>The first requirement is <strong>nonnegativity</strong>:</p>
<p><span class="math display">\[
w_i\geq 0
\qquad\text{for every }i.
\]</span></p>
<p>Without this condition, the output cannot represent ordinary shares, probabilities, mixture proportions, or nonnegative contribution strengths. The second requirement is <strong>unit total</strong>:</p>
<p><span class="math display">\[
\sum_{i=1}^{n}w_i=1.
\]</span></p>
<p>This converts the collection into an allocation of one whole. The third requirement is <strong>order preservation</strong>. If one score is larger than another,</p>
<p><span class="math display">\[
s_i&gt;s_j,
\]</span></p>
<p>then the resulting weight should ordinarily satisfy</p>
<p><span class="math display">\[
w_i&gt;w_j.
\]</span></p>
<p>A transformation that assigned less weight to the more strongly supported alternative would reverse the meaning of the score ordering. The fourth requirement is <strong>equal treatment of equal scores</strong>. If</p>
<p><span class="math display">\[
s_i=s_j,
\]</span></p>
<p>then there is no score-based reason to favor one of the two positions. We therefore expect</p>
<p><span class="math display">\[
w_i=w_j.
\]</span></p>
<p>More generally, if all scores are equal,</p>
<p><span class="math display">\[
s_1=s_2=\cdots=s_n,
\]</span></p>
<p>symmetry requires uniform weights:</p>
<p><span class="math display">\[
w_1=w_2=\cdots=w_n=\frac{1}{n}.
\]</span></p>
<p>The fifth requirement is <strong>continuity</strong>. A small change in the scores should usually produce a small change in the weights. If tiny measurement noise caused the allocation to jump abruptly from one extreme to another, the transformation would behave like hard selection rather than soft allocation. Symbolically, if</p>
<p><span class="math display">\[
\mathbf{s}'\approx\mathbf{s},
\]</span></p>
<p>then we want</p>
<p><span class="math display">\[
N(\mathbf{s}')\approx N(\mathbf{s}).
\]</span></p>
<p>The sixth requirement is <strong>permutation consistency</strong>. The numerical position of an alternative should not give it special treatment. If we reorder the scores, apply the transformation, and then restore the original order, we should recover the same corresponding weights.</p>
<p>If <span class="math inline">\(P\)</span> is a permutation matrix, this requirement can be written as</p>
<p><span class="math display">\[
N(P\mathbf{s})=PN(\mathbf{s}).
\]</span></p>
<p>The transformation follows the alternatives when they are reordered. A further desirable property is that the weights depend on relative evidence rather than on an arbitrary shared baseline. If the same constant <span class="math inline">\(c\)</span> is added to every score, the comparisons remain unchanged:</p>
<p><span class="math display">\[
(s_i+c)-(s_j+c)=s_i-s_j.
\]</span></p>
<p>This suggests the invariance</p>
<p><span class="math display">\[
N(\mathbf{s}+c\mathbf{1})=N(\mathbf{s}),
\]</span></p>
<p>where</p>
<p><span class="math display">\[
\mathbf{1}
=
\begin{bmatrix}
1\\
\vdots\\
1
\end{bmatrix}.
\]</span></p>
<p>Softmax will satisfy this property exactly. Its significance will become clearer when we derive the transformation in later sections. The desired behavior can be summarized as follows:</p>
<p><span class="math display">\[
\boxed{
\begin{aligned}
\mathbf{s}\in\mathbb{R}^n
\quad\longmapsto\quad
\mathbf{w}\in\Delta^{n-1}
\end{aligned}
}
\]</span></p>
<p>such that the output is nonnegative, sums to one, respects score ordering, treats equal scores equally, changes smoothly, and does not depend on the arbitrary ordering of the alternatives.</p>
</section>
<section id="the-machine-learning-meaning-of-a-score" class="level3">
<h3 class="anchored" data-anchor-id="the-machine-learning-meaning-of-a-score">The machine-learning meaning of a score</h3>
<p>In a multiclass machine-learning model, the final layer may produce one score for each possible class:</p>
<p><span class="math display">\[
\mathbf{s}
=
\begin{bmatrix}
s_1\\
s_2\\
\vdots\\
s_n
\end{bmatrix}.
\]</span></p>
<p>These raw class scores are often called <strong>logits</strong>. A logit is not automatically a probability. It is an unrestricted real number produced before the final normalization step. For example, an image classifier might produce</p>
<p><span class="math display">\[
\mathbf{s}
=
\begin{bmatrix}
-1.2\\
2.4\\
0.7
\end{bmatrix}
\]</span></p>
<p>for the classes</p>
<p><span class="math display">\[
\text{cat},\qquad
\text{dog},\qquad
\text{bird}.
\]</span></p>
<p>The ordering</p>
<p><span class="math display">\[
2.4&gt;0.7&gt;-1.2
\]</span></p>
<p>shows that the model currently gives the strongest support to <code>dog</code>, followed by <code>bird</code>, and then <code>cat</code>. The prediction can be obtained through</p>
<p><span class="math display">\[
\operatorname*{arg\,max}_i s_i,
\]</span></p>
<p>but the scores themselves should not be displayed as class probabilities:</p>
<p><span class="math display">\[
-1.2,\qquad 2.4,\qquad 0.7.
\]</span></p>
<p>A negative probability would be invalid, and a probability greater than one would also be invalid. Furthermore,</p>
<p><span class="math display">\[
-1.2+2.4+0.7=1.9\neq 1.
\]</span></p>
<p>The scores must first be transformed into a point on the simplex. This distinction prevents a common conceptual error:</p>
<p><span class="math display">\[
\boxed{
\text{A model score measures comparative support; it is not yet a probability assigned to an event.}
}
\]</span></p>
<p>After a normalization such as softmax, the output may have the mathematical form of a probability distribution. Even then, interpreting it as a trustworthy estimate of real-world uncertainty requires further assumptions and empirical calibration. Normalization guarantees mathematical validity; it does not by itself guarantee that the model’s confidence corresponds to reality.</p>
</section>
<section id="from-unconstrained-evidence-to-constrained-allocation" class="level3">
<h3 class="anchored" data-anchor-id="from-unconstrained-evidence-to-constrained-allocation">From unconstrained evidence to constrained allocation</h3>
<p>The complete problem can now be stated. We begin with unrestricted scores:</p>
<p><span class="math display">\[
\mathbf{s}\in\mathbb{R}^n.
\]</span></p>
<p>These scores may be positive, zero, or negative. They may have any total. Their primary role is to express relative support among alternatives. We require a transformation that produces</p>
<p><span class="math display">\[
\mathbf{w}=N(\mathbf{s}),
\]</span></p>
<p>where</p>
<p><span class="math display">\[
\mathbf{w}\in\Delta^{n-1}.
\]</span></p>
<p>The resulting weights can then participate in the weighted combination</p>
<p><span class="math display">\[
C=\sum_{i=1}^{n}w_iA_i.
\]</span></p>
<p>The computational journey is therefore</p>
<p><span class="math display">\[
\boxed{
\text{alternatives}
\longrightarrow
\text{comparative scores}
\longrightarrow
\text{normalized shares}
\longrightarrow
\text{weighted result}.
}
\]</span></p>
<p>The first arrow evaluates the alternatives. The second converts unrestricted evaluations into a valid allocation. The third uses that allocation to construct an output. Chapter 12 studied the final arrow. The present chapter studies the middle arrow. The most immediate way to construct a share is to divide an individual amount by a total amount:</p>
<p><span class="math display">\[
\text{share}
=
\frac{\text{individual amount}}
{\text{total amount}}.
\]</span></p>
<p>Applied to a collection of nonnegative quantities, this suggests</p>
<p><span class="math display">\[
w_i
=
\frac{s_i}{\sum_js_j}.
\]</span></p>
<p>This formula appears simple, but its simplicity hides several assumptions. What happens if the total is zero? What happens if some scores are negative? What happens if positive and negative scores cancel one another? Which properties does division preserve, and which problems does it fail to solve? These questions lead to ordinary normalization, the subject of the next section.</p>
</section>
</section>
<section id="normalization-as-division-by-a-total" class="level2">
<h2 class="anchored" data-anchor-id="normalization-as-division-by-a-total">13.2 Normalization as Division by a Total</h2>
<p>Section 13.1 established that a score and a share are different mathematical objects. A score expresses the strength assigned to an alternative, while a share expresses that alternative’s contribution relative to a whole. If the alternatives receive nonnegative amounts</p>
<p><span class="math display">\[
a_1,a_2,\ldots,a_n,
\]</span></p>
<p>then their total amount is</p>
<p><span class="math display">\[
T=\sum_{j=1}^{n}a_j.
\]</span></p>
<p>Provided that</p>
<p><span class="math display">\[
T&gt;0,
\]</span></p>
<p>the share belonging to alternative <span class="math inline">\(i\)</span> is</p>
<p><span class="math display">\[
\boxed{
w_i=\frac{a_i}{T}
=
\frac{a_i}{\sum_{j=1}^{n}a_j}.
}
\]</span></p>
<p>This equation is not an arbitrary mathematical convention. It follows directly from the meaning of a share. The numerator identifies the amount belonging to one alternative, while the denominator identifies the total amount across all alternatives. Division asks how much of the total is accounted for by the selected part:</p>
<p><span class="math display">\[
\boxed{
\text{share}
=
\frac{\text{part}}{\text{whole}}.
}
\]</span></p>
<p>Normalization by a total converts absolute amounts into relative amounts. The original values answer the question, “How much does each alternative possess?” The normalized values answer the question, “What fraction of everything belongs to each alternative?”</p>
<section id="constructing-shares-from-amounts" class="level3">
<h3 class="anchored" data-anchor-id="constructing-shares-from-amounts">Constructing shares from amounts</h3>
<p>Suppose three alternatives receive the positive strengths</p>
<p><span class="math display">\[
a_1=2,\qquad a_2=5,\qquad a_3=3.
\]</span></p>
<p>Their total strength is</p>
<p><span class="math display">\[
T=2+5+3=10.
\]</span></p>
<p>The normalized weights are therefore</p>
<p><span class="math display">\[
w_1=\frac{2}{10}=0.2,
\]</span></p>
<p><span class="math display">\[
w_2=\frac{5}{10}=0.5,
\]</span></p>
<p>and</p>
<p><span class="math display">\[
w_3=\frac{3}{10}=0.3.
\]</span></p>
<p>Thus,</p>
<p><span class="math display">\[
\begin{bmatrix}
2\\
5\\
3
\end{bmatrix}
\longrightarrow
\begin{bmatrix}
0.2\\
0.5\\
0.3
\end{bmatrix}.
\]</span></p>
<p>The transformation has not changed which alternative is strongest. It has changed the numerical language in which the strengths are expressed. Before normalization, the second alternative has strength <span class="math inline">\(5\)</span>. After normalization, it possesses one-half of the total strength:</p>
<p><span class="math display">\[
\frac{5}{10}=0.5.
\]</span></p>
<p>Similarly, the first alternative possesses one-fifth of the total:</p>
<p><span class="math display">\[
\frac{2}{10}=0.2,
\]</span></p>
<p>while the third possesses three-tenths:</p>
<p><span class="math display">\[
\frac{3}{10}=0.3.
\]</span></p>
<p>The original values describe amounts measured against zero. The normalized values describe proportions measured against their collective total. In vector notation, let</p>
<p><span class="math display">\[
\mathbf{a}
=
\begin{bmatrix}
a_1\\
a_2\\
\vdots\\
a_n
\end{bmatrix}.
\]</span></p>
<p>If <span class="math inline">\(\mathbf{1}\)</span> denotes the vector of ones,</p>
<p><span class="math display">\[
\mathbf{1}
=
\begin{bmatrix}
1\\
1\\
\vdots\\
1
\end{bmatrix},
\]</span></p>
<p>then the total is</p>
<p><span class="math display">\[
T=\mathbf{1}^{\mathsf T}\mathbf{a}.
\]</span></p>
<p>Normalization can therefore be written as</p>
<p><span class="math display">\[
\boxed{
\mathbf{w}
=
\frac{\mathbf{a}}
{\mathbf{1}^{\mathsf T}\mathbf{a}}.
}
\]</span></p>
<p>Division by the scalar total is applied to every coordinate of the vector.</p>
</section>
<section id="why-the-normalized-values-sum-to-one" class="level3">
<h3 class="anchored" data-anchor-id="why-the-normalized-values-sum-to-one">Why the normalized values sum to one</h3>
<p>The unit-sum property is not something that must be checked independently after normalization. It follows algebraically from the construction. Starting with</p>
<p><span class="math display">\[
w_i=\frac{a_i}{\sum_ja_j},
\]</span></p>
<p>we sum all normalized values:</p>
<p><span class="math display">\[
\sum_{i=1}^{n}w_i
=
\sum_{i=1}^{n}
\frac{a_i}{\sum_{j=1}^{n}a_j}.
\]</span></p>
<p>The denominator is the same for every term, so it can be placed beneath the sum of the numerators:</p>
<p><span class="math display">\[
\sum_{i=1}^{n}w_i
=
\frac{\sum_{i=1}^{n}a_i}
{\sum_{j=1}^{n}a_j}.
\]</span></p>
<p>The letters <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> are merely indexing symbols. Both sums represent the same total. Therefore,</p>
<p><span class="math display">\[
\sum_{i=1}^{n}w_i
=
\frac{T}{T}
=
1,
\]</span></p>
<p>provided that</p>
<p><span class="math display">\[
T\neq 0.
\]</span></p>
<p>Thus,</p>
<p><span class="math display">\[
\boxed{
\sum_i
\frac{a_i}{\sum_ja_j}
=
1.
}
\]</span></p>
<p>The denominator does not merely make the values smaller. It makes their total equal to one because every numerator is being measured against the same complete total. This is a general pattern in mathematics:</p>
<p><span class="math display">\[
\boxed{
\frac{\text{part}_1}{\text{whole}}
+
\frac{\text{part}_2}{\text{whole}}
+\cdots+
\frac{\text{part}_n}{\text{whole}}
=
\frac{\text{whole}}{\text{whole}}
=
1.
}
\]</span></p>
<p>Normalization succeeds because the numerators collectively reconstruct the denominator.</p>
</section>
<section id="why-nonnegative-inputs-produce-nonnegative-shares" class="level3">
<h3 class="anchored" data-anchor-id="why-nonnegative-inputs-produce-nonnegative-shares">Why nonnegative inputs produce nonnegative shares</h3>
<p>Suppose</p>
<p><span class="math display">\[
a_i\geq 0
\qquad\text{for every }i
\]</span></p>
<p>and at least one <span class="math inline">\(a_i\)</span> is strictly positive. Then</p>
<p><span class="math display">\[
T=\sum_ia_i&gt;0.
\]</span></p>
<p>Each normalized value is therefore a nonnegative numerator divided by a positive denominator:</p>
<p><span class="math display">\[
w_i=\frac{a_i}{T}\geq 0.
\]</span></p>
<p>Together with</p>
<p><span class="math display">\[
\sum_iw_i=1,
\]</span></p>
<p>this proves that</p>
<p><span class="math display">\[
\mathbf{w}\in\Delta^{n-1}.
\]</span></p>
<p>Consequently, ordinary normalization is guaranteed to produce a valid convex weight vector when its inputs satisfy</p>
<p><span class="math display">\[
\boxed{
a_i\geq 0
\quad\text{for every }i,
\qquad
\sum_ia_i&gt;0.
}
\]</span></p>
<p>The second condition excludes the all-zero vector. If every amount equals zero, no part possesses any proportion of a positive whole because no positive whole exists. This establishes the exact domain on which division by the total works naturally:</p>
<p><span class="math display">\[
N:
\mathbb{R}_{\geq 0}^{n}\setminus\{\mathbf{0}\}
\longrightarrow
\Delta^{n-1}.
\]</span></p>
<p>It does not yet define a valid score-to-weight transformation over all of <span class="math inline">\(\mathbb{R}^n\)</span>.</p>
</section>
<section id="normalization-removes-units" class="level3">
<h3 class="anchored" data-anchor-id="normalization-removes-units">Normalization removes units</h3>
<p>Suppose the amounts are measured in litres:</p>
<p><span class="math display">\[
a_1=2\text{ L},
\qquad
a_2=5\text{ L},
\qquad
a_3=3\text{ L}.
\]</span></p>
<p>The total is</p>
<p><span class="math display">\[
T=10\text{ L}.
\]</span></p>
<p>The first share is</p>
<p><span class="math display">\[
w_1
=
\frac{2\text{ L}}{10\text{ L}}
=
0.2.
\]</span></p>
<p>The unit appears in both the numerator and denominator, so it cancels:</p>
<p><span class="math display">\[
\frac{\text{L}}{\text{L}}=1.
\]</span></p>
<p>The normalized value is dimensionless. It no longer expresses an amount of liquid. It expresses a proportion of the total liquid. The same reasoning applies whether the original quantities are measured in litres, kilograms, counts, monetary units, or arbitrary positive strength units:</p>
<p><span class="math display">\[
\frac{\text{amount unit}}{\text{same amount unit}}
=
\text{dimensionless share}.
\]</span></p>
<p>This is one reason normalized weights can multiply quantities of another kind. In</p>
<p><span class="math display">\[
C=\sum_iw_iA_i,
\]</span></p>
<p>the dimensionless weight <span class="math inline">\(w_i\)</span> changes the amount of contribution without changing the unit carried by <span class="math inline">\(A_i\)</span>. If <span class="math inline">\(A_i\)</span> is measured in degrees Celsius, then</p>
<p><span class="math display">\[
w_iA_i
\]</span></p>
<p>is also measured in degrees Celsius. If <span class="math inline">\(\mathbf{A}_i\)</span> is a feature vector, then <span class="math inline">\(w_i\mathbf{A}_i\)</span> remains a feature vector of the same type.</p>
</section>
<section id="normalization-preserves-ratios" class="level3">
<h3 class="anchored" data-anchor-id="normalization-preserves-ratios">Normalization preserves ratios</h3>
<p>For two positive amounts <span class="math inline">\(a_i\)</span> and <span class="math inline">\(a_j\)</span>, their normalized weights are</p>
<p><span class="math display">\[
w_i=\frac{a_i}{T}
\qquad\text{and}\qquad
w_j=\frac{a_j}{T}.
\]</span></p>
<p>Their ratio is</p>
<p><span class="math display">\[
\frac{w_i}{w_j}
=
\frac{a_i/T}{a_j/T}.
\]</span></p>
<p>The common denominator <span class="math inline">\(T\)</span> cancels:</p>
<p><span class="math display">\[
\frac{w_i}{w_j}
=
\frac{a_i}{a_j}.
\]</span></p>
<p>Therefore,</p>
<p><span class="math display">\[
\boxed{
\frac{w_i}{w_j}
=
\frac{a_i}{a_j}.
}
\]</span></p>
<p>Ordinary normalization preserves the proportional relationships among the original amounts.</p>
<p>For</p>
<p><span class="math display">\[
\mathbf{a}
=
\begin{bmatrix}
2\\
5\\
3
\end{bmatrix},
\]</span></p>
<p>the second amount is</p>
<p><span class="math display">\[
\frac{5}{2}=2.5
\]</span></p>
<p>times the first amount. After normalization,</p>
<p><span class="math display">\[
\frac{0.5}{0.2}=2.5.
\]</span></p>
<p>The ratio remains unchanged. Similarly,</p>
<p><span class="math display">\[
\frac{a_3}{a_1}
=
\frac{3}{2}
=
1.5
\]</span></p>
<p>and</p>
<p><span class="math display">\[
\frac{w_3}{w_1}
=
\frac{0.3}{0.2}
=
1.5.
\]</span></p>
<p>Normalization changes the scale of the vector but preserves its internal proportions. Geometrically, all positive scalar multiples of a vector lie on the same ray from the origin:</p>
<p><span class="math display">\[
\mathbf{a},\qquad
2\mathbf{a},\qquad
10\mathbf{a},\qquad
c\mathbf{a}.
\]</span></p>
<p>Normalization maps every point on that positive ray to the same point on the simplex.</p>
</section>
<section id="scale-invariance" class="level3">
<h3 class="anchored" data-anchor-id="scale-invariance">Scale invariance</h3>
<p>Suppose every amount is multiplied by the same positive constant <span class="math inline">\(c\)</span>:</p>
<p><span class="math display">\[
a_i'=ca_i,
\qquad c&gt;0.
\]</span></p>
<p>The new total is</p>
<p><span class="math display">\[
T'
=
\sum_i a_i'
=
\sum_i ca_i
=
c\sum_i a_i
=
cT.
\]</span></p>
<p>The new normalized weight is</p>
<p><span class="math display">\[
w_i'
=
\frac{a_i'}{T'}
=
\frac{ca_i}{cT}
=
\frac{a_i}{T}
=
w_i.
\]</span></p>
<p>Therefore,</p>
<p><span class="math display">\[
\boxed{
N(c\mathbf{a})=N(\mathbf{a}),
\qquad c&gt;0.
}
\]</span></p>
<p>This property is called scale invariance. For example,</p>
<p><span class="math display">\[
\begin{bmatrix}
2\\
5\\
3
\end{bmatrix},
\qquad
\begin{bmatrix}
20\\
50\\
30
\end{bmatrix},
\qquad
\begin{bmatrix}
200\\
500\\
300
\end{bmatrix}
\]</span></p>
<p>all normalize to</p>
<p><span class="math display">\[
\begin{bmatrix}
0.2\\
0.5\\
0.3
\end{bmatrix}.
\]</span></p>
<p>The absolute magnitudes differ, but their proportions are identical. This is appropriate when only relative allocation matters. Two litres, five litres, and three litres describe the same composition as twenty millilitres, fifty millilitres, and thirty millilitres. Changing the unit or multiplying every amount by a common factor changes the total amount but not the division of that amount. Scale invariance also reveals what normalization deliberately discards. The vectors</p>
<p><span class="math display">\[
\begin{bmatrix}
2\\
5\\
3
\end{bmatrix}
\]</span></p>
<p>and</p>
<p><span class="math display">\[
\begin{bmatrix}
200\\
500\\
300
\end{bmatrix}
\]</span></p>
<p>carry different information about total magnitude, but normalization maps them to the same result. Once only the shares are retained, the original total cannot be recovered unless it was stored separately. Normalization therefore performs a controlled loss of information:</p>
<p><span class="math display">\[
\boxed{
\text{amount vector}
\longrightarrow
\text{relative composition},
}
\]</span></p>
<p>while discarding the common scale.</p>
</section>
<section id="normalization-is-not-invariant-to-addition" class="level3">
<h3 class="anchored" data-anchor-id="normalization-is-not-invariant-to-addition">Normalization is not invariant to addition</h3>
<p>Multiplication by a common positive constant preserves proportions, but addition of a common constant generally does not. Start with</p>
<p><span class="math display">\[
\mathbf{a}
=
\begin{bmatrix}
2\\
5\\
3
\end{bmatrix}.
\]</span></p>
<p>Its normalized form is</p>
<p><span class="math display">\[
N(\mathbf{a})
=
\begin{bmatrix}
0.2\\
0.5\\
0.3
\end{bmatrix}.
\]</span></p>
<p>Now add <span class="math inline">\(10\)</span> to every value:</p>
<p><span class="math display">\[
\mathbf{a}'
=
\begin{bmatrix}
12\\
15\\
13
\end{bmatrix}.
\]</span></p>
<p>The new total is</p>
<p><span class="math display">\[
12+15+13=40.
\]</span></p>
<p>The normalized result becomes</p>
<p><span class="math display">\[
N(\mathbf{a}')
=
\begin{bmatrix}
12/40\\
15/40\\
13/40
\end{bmatrix}
=
\begin{bmatrix}
0.300\\
0.375\\
0.325
\end{bmatrix}.
\]</span></p>
<p>Thus,</p>
<p><span class="math display">\[
N(\mathbf{a}+10\mathbf{1})
\neq
N(\mathbf{a}).
\]</span></p>
<p>Although the pairwise differences remain unchanged,</p>
<p><span class="math display">\[
(5+10)-(2+10)=5-2=3,
\]</span></p>
<p>the ratios do not:</p>
<p><span class="math display">\[
\frac{5}{2}=2.5,
\]</span></p>
<p>while</p>
<p><span class="math display">\[
\frac{15}{12}=1.25.
\]</span></p>
<p>Adding a large common baseline makes the values proportionally more similar, so the normalized shares move toward a uniform distribution.</p>
<p>This distinction is fundamental:</p>
<p><span class="math display">\[
\boxed{
\begin{aligned}
\text{ordinary normalization preserves ratios},\\
\text{but it does not preserve differences}.
\end{aligned}
}
\]</span></p>
<p>If the original values are genuine amounts measured from a meaningful zero, ratio preservation is natural. Ten litres is twice five litres because zero litres means the absence of liquid.</p>
<p>For arbitrary model scores, however, the zero point may not represent an absolute absence of support. Adding the same constant to all scores may leave every comparison unchanged. In such a setting, allowing the common baseline to change the normalized output may be undesirable.</p>
<p>This limitation will become important when ordinary normalization is compared with softmax.</p>
</section>
<section id="normalization-is-idempotent" class="level3">
<h3 class="anchored" data-anchor-id="normalization-is-idempotent">Normalization is idempotent</h3>
<p>Suppose a vector is already normalized:</p>
<p><span class="math display">\[
w_i\geq 0
\qquad\text{and}\qquad
\sum_iw_i=1.
\]</span></p>
<p>Applying ordinary normalization again gives</p>
<p><span class="math display">\[
N(\mathbf{w})_i
=
\frac{w_i}{\sum_jw_j}
=
\frac{w_i}{1}
=
w_i.
\]</span></p>
<p>Therefore,</p>
<p><span class="math display">\[
\boxed{
N(N(\mathbf{a}))=N(\mathbf{a}).
}
\]</span></p>
<p>A transformation with this property is called idempotent. Once the vector has reached the simplex, repeating the same normalization does not move it.</p>
<p>This makes sense semantically. If the entries already describe shares of one whole, dividing each share by their total of one leaves the shares unchanged.</p>
</section>
<section id="normalizing-strengths-before-constructing-a-weighted-result" class="level3">
<h3 class="anchored" data-anchor-id="normalizing-strengths-before-constructing-a-weighted-result">Normalizing strengths before constructing a weighted result</h3>
<p>Suppose</p>
<p><span class="math display">\[
A_1=20,\qquad A_2=50,\qquad A_3=80
\]</span></p>
<p>and the positive strengths are</p>
<p><span class="math display">\[
a_1=2,\qquad a_2=5,\qquad a_3=3.
\]</span></p>
<p>The weighted average may be calculated in two equivalent ways.</p>
<p>First, normalize the strengths:</p>
<p><span class="math display">\[
w_1=0.2,\qquad w_2=0.5,\qquad w_3=0.3,
\]</span></p>
<p>and then form the weighted combination:</p>
<p><span class="math display">\[
C
=
0.2(20)+0.5(50)+0.3(80)
=
53.
\]</span></p>
<p>Alternatively, substitute the normalization formula directly:</p>
<p><span class="math display">\[
C
=
\sum_i
\frac{a_i}{\sum_ja_j}A_i.
\]</span></p>
<p>Because the denominator is common to every term,</p>
<p><span class="math display">\[
C
=
\frac{\sum_i a_iA_i}
{\sum_j a_j}.
\]</span></p>
<p>For the present values,</p>
<p><span class="math display">\[
C
=
\frac{2(20)+5(50)+3(80)}
{2+5+3}
=
\frac{530}{10}
=
53.
\]</span></p>
<p>Thus,</p>
<p><span class="math display">\[
\boxed{
\sum_iw_iA_i
=
\frac{\sum_i a_iA_i}{\sum_i a_i},
\qquad
w_i=\frac{a_i}{\sum_ja_j}.
}
\]</span></p>
<p>The raw weighted sum accumulates the weighted contributions, while division by the total strength returns the result to the scale of the alternatives.</p>
<p>This connects the current chapter directly to Chapter 12. Normalization is the operation that converts raw positive coefficients into the convex weights required by a weighted average.</p>
</section>
<section id="implementing-ordinary-normalization" class="level3">
<h3 class="anchored" data-anchor-id="implementing-ordinary-normalization">Implementing ordinary normalization</h3>
<p>For a valid collection of nonnegative strengths, normalization can be implemented directly:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>strengths <span class="op">=</span> np.array([<span class="fl">2.0</span>, <span class="fl">5.0</span>, <span class="fl">3.0</span>])</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>total <span class="op">=</span> np.<span class="bu">sum</span>(strengths)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>weights <span class="op">=</span> strengths <span class="op">/</span> total</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(weights)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(np.<span class="bu">sum</span>(weights))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The output is</p>
<pre class="text"><code>[0.2 0.5 0.3]
1.0</code></pre>
<p>A reusable implementation should make its assumptions explicit:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> normalize_nonnegative(strengths):</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    strengths <span class="op">=</span> np.asarray(strengths, dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> strengths.ndim <span class="op">!=</span> <span class="dv">1</span>:</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"strengths must be a one-dimensional array"</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> np.<span class="bu">any</span>(strengths <span class="op">&lt;</span> <span class="dv">0</span>):</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"strengths must be nonnegative"</span>)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    total <span class="op">=</span> np.<span class="bu">sum</span>(strengths)</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> total <span class="op">&lt;=</span> <span class="dv">0</span>:</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">ValueError</span>(</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>            <span class="st">"at least one strength must be positive"</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> strengths <span class="op">/</span> total</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Using the function:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>strengths <span class="op">=</span> np.array([<span class="fl">2.0</span>, <span class="fl">5.0</span>, <span class="fl">3.0</span>])</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>weights <span class="op">=</span> normalize_nonnegative(strengths)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(weights)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>produces</p>
<pre class="text"><code>[0.2 0.5 0.3]</code></pre>
<p>The validation is not incidental programming machinery. It expresses the mathematical domain of the operation:</p>
<p><span class="math display">\[
\mathbf{a}
\in
\mathbb{R}_{\geq 0}^{n}\setminus\{\mathbf{0}\}.
\]</span></p>
<p>The code refuses inputs for which the intended interpretation has not been mathematically defined.</p>
</section>
<section id="failure-when-the-total-is-zero" class="level3">
<h3 class="anchored" data-anchor-id="failure-when-the-total-is-zero">Failure when the total is zero</h3>
<p>Consider</p>
<p><span class="math display">\[
\mathbf{s}
=
\begin{bmatrix}
0\\
0\\
0
\end{bmatrix}.
\]</span></p>
<p>The total is</p>
<p><span class="math display">\[
T=0+0+0=0.
\]</span></p>
<p>Ordinary normalization would require</p>
<p><span class="math display">\[
w_i=\frac{0}{0},
\]</span></p>
<p>which is undefined.</p>
<p>The problem is not merely a limitation of computer arithmetic. A zero total contains no positive amount to distribute. The question</p>
<blockquote class="blockquote">
<p>What fraction of the total belongs to each alternative?</p>
</blockquote>
<p>cannot be answered by part-to-whole division when both every part and the whole are zero.</p>
<p>A separate modeling decision is required. One system might assign uniform weights,</p>
<p><span class="math display">\[
w_i=\frac{1}{n},
\]</span></p>
<p>because no alternative has received more strength than another. Another system might treat the all-zero vector as an error because no allocation has been justified. The formula itself cannot choose between these meanings.</p>
<p>Now consider a score vector containing both positive and negative values:</p>
<p><span class="math display">\[
\mathbf{s}
=
\begin{bmatrix}
2\\
-3\\
1
\end{bmatrix}.
\]</span></p>
<p>Its total is also zero:</p>
<p><span class="math display">\[
2-3+1=0.
\]</span></p>
<p>Again, division by the total is undefined:</p>
<p><span class="math display">\[
\frac{\mathbf{s}}{\sum_i s_i}
=
\frac{\mathbf{s}}{0}.
\]</span></p>
<p>In this case, the zero total does not mean that every score is absent. It results from cancellation between positive and negative values. A large amount of comparative information is present, but signed addition has destroyed the denominator needed by ordinary normalization.</p>
</section>
<section id="negative-values-may-produce-negative-weights" class="level3">
<h3 class="anchored" data-anchor-id="negative-values-may-produce-negative-weights">Negative values may produce negative weights</h3>
<p>Consider</p>
<p><span class="math display">\[
\mathbf{s}
=
\begin{bmatrix}
2\\
-1\\
3
\end{bmatrix}.
\]</span></p>
<p>The total is</p>
<p><span class="math display">\[
T=2-1+3=4.
\]</span></p>
<p>Dividing by the total gives</p>
<p><span class="math display">\[
\frac{\mathbf{s}}{T}
=
\begin{bmatrix}
2/4\\
-1/4\\
3/4
\end{bmatrix}
=
\begin{bmatrix}
0.5\\
-0.25\\
0.75
\end{bmatrix}.
\]</span></p>
<p>The entries sum to one:</p>
<p><span class="math display">\[
0.5-0.25+0.75=1.
\]</span></p>
<p>But the second entry is negative:</p>
<p><span class="math display">\[
-0.25&lt;0.
\]</span></p>
<p>The result is an affine coefficient vector, not a convex weight vector. It cannot represent an ordinary probability distribution or a division of a positive whole.</p>
<p>This example shows that the unit-sum condition alone is insufficient. Division by a nonzero total guarantees</p>
<p><span class="math display">\[
\sum_iw_i=1,
\]</span></p>
<p>but it does not guarantee</p>
<p><span class="math display">\[
w_i\geq 0.
\]</span></p>
</section>
<section id="a-negative-total-can-reverse-the-ordering" class="level3">
<h3 class="anchored" data-anchor-id="a-negative-total-can-reverse-the-ordering">A negative total can reverse the ordering</h3>
<p>Suppose every score is negative:</p>
<p><span class="math display">\[
\mathbf{s}
=
\begin{bmatrix}
-2\\
-1\\
-3
\end{bmatrix}.
\]</span></p>
<p>The score ordering is</p>
<p><span class="math display">\[
-1&gt;-2&gt;-3.
\]</span></p>
<p>Thus, the second alternative has the largest score, the first has the next largest score, and the third has the smallest score.</p>
<p>The total is</p>
<p><span class="math display">\[
T=-2-1-3=-6.
\]</span></p>
<p>Dividing by the total gives</p>
<p><span class="math display">\[
\mathbf{w}
=
\begin{bmatrix}
(-2)/(-6)\\
(-1)/(-6)\\
(-3)/(-6)
\end{bmatrix}
=
\begin{bmatrix}
1/3\\
1/6\\
1/2
\end{bmatrix}.
\]</span></p>
<p>These values are nonnegative and sum to one. Nevertheless, they reverse the intended ordering:</p>
<p><span class="math display">\[
\frac{1}{2}&gt;\frac{1}{3}&gt;\frac{1}{6}.
\]</span></p>
<p>The most negative score, <span class="math inline">\(-3\)</span>, receives the largest weight, while the greatest score, <span class="math inline">\(-1\)</span>, receives the smallest weight.</p>
<p>The reversal occurs because division by a negative number reverses inequalities. If</p>
<p><span class="math display">\[
s_i&gt;s_j
\]</span></p>
<p>and</p>
<p><span class="math display">\[
T&lt;0,
\]</span></p>
<p>then</p>
<p><span class="math display">\[
\frac{s_i}{T}
&lt;
\frac{s_j}{T}.
\]</span></p>
<p>Therefore, obtaining nonnegative values that sum to one is not enough. The transformation must also preserve the comparative meaning of the scores.</p>
</section>
<section id="cancellation-creates-extreme-instability" class="level3">
<h3 class="anchored" data-anchor-id="cancellation-creates-extreme-instability">Cancellation creates extreme instability</h3>
<p>The problem becomes even more severe when positive and negative scores nearly cancel.</p>
<p>Consider</p>
<p><span class="math display">\[
\mathbf{s}
=
\begin{bmatrix}
1\\
-0.99
\end{bmatrix}.
\]</span></p>
<p>The total is</p>
<p><span class="math display">\[
T=1-0.99=0.01.
\]</span></p>
<p>Ordinary division produces</p>
<p><span class="math display">\[
\mathbf{w}
=
\begin{bmatrix}
1/0.01\\
-0.99/0.01
\end{bmatrix}
=
\begin{bmatrix}
100\\
-99
\end{bmatrix}.
\]</span></p>
<p>The entries technically sum to one:</p>
<p><span class="math display">\[
100-99=1.
\]</span></p>
<p>But they are not shares in the ordinary sense. The first coefficient is one hundred units of contribution, and the second removes ninety-nine units.</p>
<p>A very small change in the second score can cause an enormous change in the result. If</p>
<p><span class="math display">\[
-0.99
\]</span></p>
<p>is replaced by</p>
<p><span class="math display">\[
-0.999,
\]</span></p>
<p>then the total becomes</p>
<p><span class="math display">\[
0.001,
\]</span></p>
<p>and the normalized vector becomes</p>
<p><span class="math display">\[
\begin{bmatrix}
1000\\
-999
\end{bmatrix}.
\]</span></p>
<p>As the denominator approaches zero, the magnitudes of the coefficients grow without bound.</p>
<p>Therefore, ordinary normalization is unstable near a zero signed total:</p>
<p><span class="math display">\[
\sum_i s_i\approx 0.
\]</span></p>
<p>The original scores may be moderate, but cancellation makes their normalized coefficients arbitrarily large.</p>
</section>
<section id="dividing-by-absolute-magnitude-solves-a-different-problem" class="level3">
<h3 class="anchored" data-anchor-id="dividing-by-absolute-magnitude-solves-a-different-problem">Dividing by absolute magnitude solves a different problem</h3>
<p>One possible reaction is to divide by the sum of absolute values:</p>
<p><span class="math display">\[
\widetilde{w}_i
=
\frac{s_i}
{\sum_j|s_j|}.
\]</span></p>
<p>For</p>
<p><span class="math display">\[
\mathbf{s}
=
\begin{bmatrix}
2\\
-1\\
3
\end{bmatrix},
\]</span></p>
<p>the absolute total is</p>
<p><span class="math display">\[
|2|+|-1|+|3|
=
2+1+3
=
6.
\]</span></p>
<p>This gives</p>
<p><span class="math display">\[
\widetilde{\mathbf{w}}
=
\begin{bmatrix}
2/6\\
-1/6\\
3/6
\end{bmatrix}.
\]</span></p>
<p>The absolute magnitudes satisfy</p>
<p><span class="math display">\[
\sum_i|\widetilde{w}_i|=1.
\]</span></p>
<p>This is called normalization by the <span class="math inline">\(L^1\)</span> norm. It is useful when the goal is to constrain the total absolute magnitude of a vector.</p>
<p>But the signed entries themselves satisfy</p>
<p><span class="math display">\[
\sum_i\widetilde{w}_i
=
\frac{2-1+3}{6}
=
\frac{4}{6},
\]</span></p>
<p>not one. A negative coefficient also remains negative.</p>
<p>Therefore, <span class="math inline">\(L^1\)</span> normalization does not generally map a signed vector to the probability simplex:</p>
<p><span class="math display">\[
\frac{\mathbf{s}}{\sum_i|s_i|}
\notin
\Delta^{n-1}.
\]</span></p>
<p>It solves a different mathematical problem. It controls vector magnitude while preserving signs; it does not convert arbitrary signed scores into nonnegative shares.</p>
<p>This illustrates why the word <em>normalization</em> must always be interpreted through the constraint being imposed.</p>
</section>
<section id="normalization-is-not-the-same-as-standardization" class="level3">
<h3 class="anchored" data-anchor-id="normalization-is-not-the-same-as-standardization">Normalization is not the same as standardization</h3>
<p>The term <em>normalization</em> is used broadly in programming and machine learning. Different operations called normalization produce different mathematical objects.</p>
<p>Division by a total constructs shares:</p>
<p><span class="math display">\[
w_i
=
\frac{a_i}{\sum_ja_j}.
\]</span></p>
<p>Normalization by a vector norm may create a unit-length vector:</p>
<p><span class="math display">\[
\widehat{\mathbf{x}}
=
\frac{\mathbf{x}}{\|\mathbf{x}\|_2},
\]</span></p>
<p>so that</p>
<p><span class="math display">\[
\|\widehat{\mathbf{x}}\|_2=1.
\]</span></p>
<p>Min–max normalization maps values into a selected interval, often <span class="math inline">\([0,1]\)</span>:</p>
<p><span class="math display">\[
x_i'
=
\frac{x_i-\min_jx_j}
{\max_jx_j-\min_jx_j}.
\]</span></p>
<p>Standardization subtracts a mean and divides by a standard deviation:</p>
<p><span class="math display">\[
z_i
=
\frac{x_i-\mu}{\sigma}.
\]</span></p>
<p>The standardized values generally do not lie between zero and one, do not sum to one, and are not probabilities. Their purpose is to express displacement from the mean in units of standard deviation.</p>
<p>These operations should not be treated as interchangeable merely because they all modify numerical scale.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Transformation</th>
<th>Constraint produced</th>
<th>Main purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Division by total</td>
<td><span class="math inline">\(\sum_iw_i=1\)</span> for a nonzero total</td>
<td>Convert positive amounts into shares</td>
</tr>
<tr class="even">
<td><span class="math inline">\(L^1\)</span> normalization</td>
<td><span class="math inline">\(\sum_i|x_i'|=1\)</span></td>
<td>Control total absolute magnitude</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(L^2\)</span> normalization</td>
<td><span class="math inline">\(\sum_i(x_i')^2=1\)</span></td>
<td>Create a unit-length vector</td>
</tr>
<tr class="even">
<td>Min–max normalization</td>
<td>Usually <span class="math inline">\(x_i'\in[0,1]\)</span></td>
<td>Place data inside a fixed interval</td>
</tr>
<tr class="odd">
<td>Standardization</td>
<td>Mean <span class="math inline">\(0\)</span>, standard deviation <span class="math inline">\(1\)</span></td>
<td>Express values relative to mean and spread</td>
</tr>
</tbody>
</table>
<p>The relevant operation must be chosen from the meaning required by the computation. In the present chapter, the objective is specifically to create nonnegative weights whose total is one.</p>
</section>
<section id="why-shifting-the-scores-is-not-a-complete-solution" class="level3">
<h3 class="anchored" data-anchor-id="why-shifting-the-scores-is-not-a-complete-solution">Why shifting the scores is not a complete solution</h3>
<p>If negative values prevent ordinary normalization, one might try to add a constant to every score until all values become nonnegative.</p>
<p>Given</p>
<p><span class="math display">\[
\mathbf{s}
=
\begin{bmatrix}
-2\\
1\\
3
\end{bmatrix},
\]</span></p>
<p>adding <span class="math inline">\(2\)</span> produces</p>
<p><span class="math display">\[
\mathbf{s}+2\mathbf{1}
=
\begin{bmatrix}
0\\
3\\
5
\end{bmatrix}.
\]</span></p>
<p>These values can be normalized:</p>
<p><span class="math display">\[
\mathbf{w}
=
\begin{bmatrix}
0/8\\
3/8\\
5/8
\end{bmatrix}
=
\begin{bmatrix}
0\\
0.375\\
0.625
\end{bmatrix}.
\]</span></p>
<p>However, adding <span class="math inline">\(3\)</span> instead produces</p>
<p><span class="math display">\[
\mathbf{s}+3\mathbf{1}
=
\begin{bmatrix}
1\\
4\\
6
\end{bmatrix},
\]</span></p>
<p>which normalizes to</p>
<p><span class="math display">\[
\begin{bmatrix}
1/11\\
4/11\\
6/11
\end{bmatrix}
\approx
\begin{bmatrix}
0.091\\
0.364\\
0.545
\end{bmatrix}.
\]</span></p>
<p>Both shifts preserve the score ordering:</p>
<p><span class="math display">\[
s_3&gt;s_2&gt;s_1.
\]</span></p>
<p>Yet they produce different allocations.</p>
<p>As the added constant becomes larger, the entries become proportionally more similar, and the normalized weights move toward uniformity. The result therefore depends on an arbitrary choice of baseline.</p>
<p>Subtracting the minimum is one possible rule, but it forces the smallest score to receive exactly zero weight:</p>
<p><span class="math display">\[
s_i-\min_js_j=0
\]</span></p>
<p>for at least one position. Whether the weakest alternative should be completely eliminated is a modeling decision, not a consequence of ranking alone.</p>
<p>Adding a small positive constant after subtracting the minimum avoids a zero weight, but then the result depends on the chosen constant. The underlying problem has merely been moved into another parameter.</p>
<p>A more principled transformation should make every score positive while responding consistently to score differences. This is the role exponentiation will play.</p>
</section>
<section id="the-exact-achievement-and-limitation-of-ordinary-normalization" class="level3">
<h3 class="anchored" data-anchor-id="the-exact-achievement-and-limitation-of-ordinary-normalization">The exact achievement and limitation of ordinary normalization</h3>
<p>Ordinary normalization is mathematically complete when its inputs are nonnegative amounts with a positive total:</p>
<p><span class="math display">\[
a_i\geq 0,
\qquad
\sum_i a_i&gt;0.
\]</span></p>
<p>Under these assumptions,</p>
<p><span class="math display">\[
w_i
=
\frac{a_i}{\sum_ja_j}
\]</span></p>
<p>guarantees:</p>
<p><span class="math display">\[
w_i\geq 0,
\]</span></p>
<p><span class="math display">\[
\sum_iw_i=1,
\]</span></p>
<p><span class="math display">\[
\frac{w_i}{w_j}
=
\frac{a_i}{a_j},
\]</span></p>
<p>and</p>
<p><span class="math display">\[
N(c\mathbf{a})=N(\mathbf{a})
\qquad(c&gt;0).
\]</span></p>
<p>It converts amounts into shares, preserves their ratios, removes their common scale, and places the result on the simplex.</p>
<p>What it does not do is convert arbitrary real scores into valid weights. For unrestricted scores, the denominator may be zero, negative values may remain negative, a negative total may reverse the ordering, and cancellation may produce unbounded coefficients.</p>
<p>The distinction can therefore be stated precisely:</p>
<p><span class="math display">\[
\boxed{
\text{Division by a total normalizes positive strengths, not arbitrary real scores.}
}
\]</span></p>
<p>To handle arbitrary scores</p>
<p><span class="math display">\[
s_i\in\mathbb{R},
\]</span></p>
<p>we require an intermediate transformation</p>
<p><span class="math display">\[
a_i=g(s_i)
\]</span></p>
<p>that produces positive strengths:</p>
<p><span class="math display">\[
g(s_i)&gt;0.
\]</span></p>
<p>Only after this transformation should division by the total be applied:</p>
<p><span class="math display">\[
w_i
=
\frac{g(s_i)}
{\sum_jg(s_j)}.
\]</span></p>
<p>The next question is therefore not whether normalization should divide by a total. That part has already been justified. The next question is what function <span class="math inline">\(g\)</span> should convert unrestricted scores into positive quantities while preserving their comparative structure.</p>
<p>Softmax answers this question with</p>
<p><span class="math display">\[
g(s)=e^s.
\]</span></p>
<p>The reasons for choosing exponentiation are the subject of the next section.</p>
</section>
</section>
<section id="why-exponentiation-precedes-normalization" class="level2">
<h2 class="anchored" data-anchor-id="why-exponentiation-precedes-normalization">13.3 Why Exponentiation Precedes Normalization</h2>
<p>Section 13.2 showed that division by a total converts nonnegative amounts into shares:</p>
<p><span class="math display">\[
w_i=\frac{a_i}{\sum_ja_j}.
\]</span></p>
<p>This construction works when the inputs already satisfy <span class="math inline">\(a_i\geq 0\)</span> and at least one amount is positive. An unrestricted score, however, may be any real number <span class="math inline">\(s_i\in\mathbb{R}.\)</span> We therefore need an intermediate function <span class="math inline">\(g:\mathbb{R}\longrightarrow\mathbb{R}_{&gt;0}\)</span></p>
<p>that converts each score into a positive strength <span class="math inline">\(a_i=g(s_i).\)</span> The positive strengths can then be normalized:</p>
<p><span class="math display">\[
w_i
=
\frac{g(s_i)}
{\sum_jg(s_j)}.
\]</span></p>
<p>The complete construction has two distinct stages:</p>
<p><span class="math display">\[
\boxed{
s_i
\overset{g}{\longrightarrow}
a_i&gt;0
\overset{\text{normalize}}{\longrightarrow}
w_i
=
\frac{a_i}{\sum_ja_j}.
}
\]</span></p>
<p>Softmax chooses <span class="math inline">\(g(s)=e^s,\)</span> which gives</p>
<p><span class="math display">\[
\boxed{
w_i
=
\frac{e^{s_i}}
{\sum_{j=1}^{n}e^{s_j}}.
}
\]</span></p>
<p>At first, exponentiation may appear to be an arbitrary technique inserted merely to remove negative values. It certainly does make every transformed value positive, but positivity alone does not explain why the exponential function is especially suitable. Many other functions can produce nonnegative values. The deeper reason is that exponentiation preserves score ordering while converting additive score differences into multiplicative relationships among positive strengths.</p>
<section id="the-first-requirement-every-transformed-strength-must-be-positive" class="level3">
<h3 class="anchored" data-anchor-id="the-first-requirement-every-transformed-strength-must-be-positive">The first requirement: every transformed strength must be positive</h3>
<p>A valid normalized weight must satisfy <span class="math inline">\(w_i\geq 0.\)</span> If we use</p>
<p><span class="math display">\[
w_i
=
\frac{g(s_i)}
{\sum_jg(s_j)},
\]</span></p>
<p>the simplest way to guarantee this condition is to require</p>
<p><span class="math display">\[
g(s)&gt;0
\qquad
\text{for every }s\in\mathbb{R}.
\]</span></p>
<p>The exponential function satisfies this requirement:</p>
<p><span class="math display">\[
e^s&gt;0
\qquad
\text{for every real }s.
\]</span></p>
<p>This remains true for positive, zero, and negative scores:</p>
<p><span class="math display">\[
e^3&gt;0,
\qquad
e^0=1&gt;0,
\qquad
e^{-3}&gt;0.
\]</span></p>
<p>A negative exponent does not produce a negative result. It produces a positive reciprocal:</p>
<p><span class="math display">\[
e^{-s}=\frac{1}{e^s}.
\]</span></p>
<p>For example,</p>
<p><span class="math display">\[
e^{-2}
=
\frac{1}{e^2}
\approx 0.1353.
\]</span></p>
<p>Thus, exponentiation converts the entire real line into the positive real line:</p>
<p><span class="math display">\[
\boxed{
\exp:\mathbb{R}\longrightarrow\mathbb{R}_{&gt;0}.
}
\]</span></p>
<p>Because every transformed strength is strictly positive, their total is also strictly positive:</p>
<p><span class="math display">\[
\sum_je^{s_j}&gt;0.
\]</span></p>
<p>The denominator can never become zero for a finite score vector. Consequently,</p>
<p><span class="math display">\[
w_i
=
\frac{e^{s_i}}{\sum_je^{s_j}}
\]</span></p>
<p>is well-defined for every finite real score vector. This immediately solves two failures of ordinary score normalization. Negative scores no longer produce negative weights, and positive and negative scores cannot cancel in the denominator.</p>
</section>
<section id="exponentiation-preserves-the-ordering-of-scores" class="level3">
<h3 class="anchored" data-anchor-id="exponentiation-preserves-the-ordering-of-scores">Exponentiation preserves the ordering of scores</h3>
<p>Producing positive values is not sufficient. The transformation must also preserve the comparative meaning of the scores. If <span class="math inline">\(s_i&gt;s_j,\)</span> then alternative <span class="math inline">\(i\)</span> has received greater support than alternative <span class="math inline">\(j\)</span>. We therefore want the transformed strengths to satisfy <span class="math inline">\(g(s_i)&gt;g(s_j).\)</span> The exponential function is strictly increasing:</p>
<p><span class="math display">\[
s_i&gt;s_j
\quad\Longrightarrow\quad
e^{s_i}&gt;e^{s_j}.
\]</span></p>
<p>Since the same positive denominator is used for every normalized weight,</p>
<p><span class="math display">\[
\sum_ke^{s_k}&gt;0,
\]</span></p>
<p>division preserves the inequality:</p>
<p><span class="math display">\[
\frac{e^{s_i}}{\sum_ke^{s_k}}
&gt;
\frac{e^{s_j}}{\sum_ke^{s_k}}.
\]</span></p>
<p>Therefore,</p>
<p><span class="math display">\[
\boxed{
s_i&gt;s_j
\quad\Longrightarrow\quad
w_i&gt;w_j.
}
\]</span></p>
<p>Similarly,</p>
<p><span class="math display">\[
s_i=s_j
\quad\Longrightarrow\quad
e^{s_i}=e^{s_j}
\quad\Longrightarrow\quad
w_i=w_j.
\]</span></p>
<p>Softmax neither reverses score order nor arbitrarily breaks ties. This gives an important relationship between hard and soft selection:</p>
<p><span class="math display">\[
\operatorname*{arg\,max}_i s_i
=
\operatorname*{arg\,max}_i e^{s_i}
=
\operatorname*{arg\,max}_i w_i.
\]</span></p>
<p>Exponentiation and normalization change the numerical representation of the comparison, but they do not change which alternative has the greatest score.</p>
</section>
<section id="why-absolute-value-is-not-sufficient" class="level3">
<h3 class="anchored" data-anchor-id="why-absolute-value-is-not-sufficient">Why absolute value is not sufficient</h3>
<p>The absolute-value function also produces nonnegative quantities <span class="math inline">\(g(s)=|s|.\)</span> However, it does not preserve score ordering across negative values. Consider</p>
<p><span class="math display">\[
s_1=-5
\qquad\text{and}\qquad
s_2=-1.
\]</span></p>
<p>The original ordering is <span class="math inline">\(-1&gt;-5,\)</span> so the second alternative has the greater score. After applying absolute value,</p>
<p><span class="math display">\[
|-5|=5
\qquad\text{and}\qquad
|-1|=1.
\]</span></p>
<p>The ordering is reversed <span class="math inline">\(5&gt;1.\)</span> The weaker score would receive the larger normalized weight. Absolute value also treats opposite scores identically <span class="math inline">\(|-3|=|3|=3.\)</span> If the sign carries comparative meaning, this transformation destroys it.</p>
</section>
<section id="why-squaring-is-not-sufficient" class="level3">
<h3 class="anchored" data-anchor-id="why-squaring-is-not-sufficient">Why squaring is not sufficient</h3>
<p>Squaring also produces nonnegative quantities:</p>
<p><span class="math display">\[
g(s)=s^2.
\]</span></p>
<p>But it has the same ordering problem:</p>
<p><span class="math display">\[
(-5)^2=25,
\qquad
(-1)^2=1.
\]</span></p>
<p>The more negative score becomes the larger positive strength. Squaring also merges positive and negative values of equal magnitude:</p>
<p><span class="math display">\[
(-3)^2=3^2=9.
\]</span></p>
<p>It therefore loses information that the scoring system may have intended to preserve.</p>
</section>
<section id="why-clipping-is-not-sufficient" class="level3">
<h3 class="anchored" data-anchor-id="why-clipping-is-not-sufficient">Why clipping is not sufficient</h3>
<p>Another possibility is to replace negative scores with zero:</p>
<p><span class="math display">\[
g(s)=\max(0,s).
\]</span></p>
<p>This is the rectified linear unit, commonly written as</p>
<p><span class="math display">\[
\operatorname{ReLU}(s)=\max(0,s).
\]</span></p>
<p>For</p>
<p><span class="math display">\[
\mathbf{s}
=
\begin{bmatrix}
-2\\
1\\
3
\end{bmatrix},
\]</span></p>
<p>ReLU produces</p>
<p><span class="math display">\[
\begin{bmatrix}
0\\
1\\
3
\end{bmatrix}.
\]</span></p>
<p>These values can be normalized to</p>
<p><span class="math display">\[
\begin{bmatrix}
0\\
1/4\\
3/4
\end{bmatrix}.
\]</span></p>
<p>However, every negative score is collapsed to the same strength:</p>
<p><span class="math display">\[
\operatorname{ReLU}(-1)
=
\operatorname{ReLU}(-10)
=
0.
\]</span></p>
<p>The distinction between different negative scores disappears. The corresponding alternatives receive exactly zero weight and no longer contribute. The all-negative vector creates an even more direct failure:</p>
<p><span class="math display">\[
\mathbf{s}
=
\begin{bmatrix}
-2\\
-1\\
-3
\end{bmatrix}
\quad\Longrightarrow\quad
\operatorname{ReLU}(\mathbf{s})
=
\begin{bmatrix}
0\\
0\\
0
\end{bmatrix}.
\]</span></p>
<p>The transformed total is zero, so normalization is undefined. ReLU is valuable for other computational purposes, but it does not define a positive, order-preserving normalization for every real score vector.</p>
</section>
<section id="why-an-arbitrary-shift-is-not-sufficient" class="level3">
<h3 class="anchored" data-anchor-id="why-an-arbitrary-shift-is-not-sufficient">Why an arbitrary shift is not sufficient</h3>
<p>We could add a constant <span class="math inline">\(c\)</span> large enough to make every score nonnegative:</p>
<p><span class="math display">\[
g(s)=s+c.
\]</span></p>
<p>For a particular finite vector, choosing</p>
<p><span class="math display">\[
c&gt;-\min_i s_i
\]</span></p>
<p>makes every transformed value positive. However, the resulting weights depend on the arbitrary choice of <span class="math inline">\(c\)</span>. Starting with</p>
<p><span class="math display">\[
\mathbf{s}
=
\begin{bmatrix}
-2\\
1\\
3
\end{bmatrix},
\]</span></p>
<p>adding <span class="math inline">\(3\)</span> gives</p>
<p><span class="math display">\[
\begin{bmatrix}
1\\
4\\
6
\end{bmatrix},
\]</span></p>
<p>which normalizes to</p>
<p><span class="math display">\[
\begin{bmatrix}
1/11\\
4/11\\
6/11
\end{bmatrix}.
\]</span></p>
<p>Adding <span class="math inline">\(10\)</span> gives</p>
<p><span class="math display">\[
\begin{bmatrix}
8\\
11\\
13
\end{bmatrix},
\]</span></p>
<p>which normalizes to</p>
<p><span class="math display">\[
\begin{bmatrix}
8/32\\
11/32\\
13/32
\end{bmatrix}.
\]</span></p>
<p>Both shifts preserve every pairwise difference:</p>
<p><span class="math display">\[
(s_i+c)-(s_j+c)=s_i-s_j,
\]</span></p>
<p>yet they produce different weight vectors. If scores express relative preference, their arbitrary common baseline should not determine the allocation. We therefore seek a transformation under which a common score shift cancels naturally during normalization.</p>
</section>
<section id="the-deeper-requirement-relative-weights-should-depend-on-score-differences" class="level3">
<h3 class="anchored" data-anchor-id="the-deeper-requirement-relative-weights-should-depend-on-score-differences">The deeper requirement: relative weights should depend on score differences</h3>
<p>Suppose alternatives <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> receive scores <span class="math inline">\(s_i\)</span> and <span class="math inline">\(s_j\)</span>. After applying a positive transformation <span class="math inline">\(g\)</span> and normalizing, their weights are</p>
<p><span class="math display">\[
w_i
=
\frac{g(s_i)}{\sum_kg(s_k)}
\]</span></p>
<p>and</p>
<p><span class="math display">\[
w_j
=
\frac{g(s_j)}{\sum_kg(s_k)}.
\]</span></p>
<p>The ratio between these weights is</p>
<p><span class="math display">\[
\frac{w_i}{w_j}
=
\frac{g(s_i)}{g(s_j)}.
\]</span></p>
<p>The normalization denominator cancels. Thus, the relative allocation between two alternatives is determined by the ratio of their transformed strengths. If scores have only relative meaning, then this ratio should depend on how far apart the scores are, not on their shared baseline. In other words, we want a function <span class="math inline">\(R\)</span> such that</p>
<p><span class="math display">\[
\frac{g(s_i)}{g(s_j)}
=
R(s_i-s_j).
\]</span></p>
<p>This requirement states:</p>
<p><span class="math display">\[
\boxed{
\text{Equal score differences should produce equal weight ratios.}
}
\]</span></p>
<p>Consider two pairs of scores:</p>
<p><span class="math display">\[
(5,3)
\qquad\text{and}\qquad
(12,10).
\]</span></p>
<p>Both pairs have difference</p>
<p><span class="math display">\[
5-3=2
\]</span></p>
<p>and</p>
<p><span class="math display">\[
12-10=2.
\]</span></p>
<p>If only relative score separation matters, then the stronger alternative should have the same multiplicative advantage in both pairs:</p>
<p><span class="math display">\[
\frac{g(5)}{g(3)}
=
\frac{g(12)}{g(10)}.
\]</span></p>
<p>Ordinary positive shifting does not satisfy this requirement. For example,</p>
<p><span class="math display">\[
\frac{5+10}{3+10}
=
\frac{15}{13},
\]</span></p>
<p>while</p>
<p><span class="math display">\[
\frac{12+10}{10+10}
=
\frac{22}{20}.
\]</span></p>
<p>The ratios differ even though the score differences are equal. Exponentiation behaves differently:</p>
<p><span class="math display">\[
\frac{e^5}{e^3}
=
e^{5-3}
=
e^2,
\]</span></p>
<p>and</p>
<p><span class="math display">\[
\frac{e^{12}}{e^{10}}
=
e^{12-10}
=
e^2.
\]</span></p>
<p>The common baseline disappears. Only the difference remains.</p>
</section>
<section id="exponentiation-converts-differences-into-ratios" class="level3">
<h3 class="anchored" data-anchor-id="exponentiation-converts-differences-into-ratios">Exponentiation converts differences into ratios</h3>
<p>For softmax weights,</p>
<p><span class="math display">\[
w_i
=
\frac{e^{s_i}}{\sum_ke^{s_k}}
\]</span></p>
<p>and</p>
<p><span class="math display">\[
w_j
=
\frac{e^{s_j}}{\sum_ke^{s_k}}.
\]</span></p>
<p>Their ratio is</p>
<p><span class="math display">\[
\frac{w_i}{w_j}
=
\frac{
e^{s_i}/\sum_ke^{s_k}
}{
e^{s_j}/\sum_ke^{s_k}
}.
\]</span></p>
<p>The common normalization denominator cancels:</p>
<p><span class="math display">\[
\frac{w_i}{w_j}
=
\frac{e^{s_i}}{e^{s_j}}.
\]</span></p>
<p>Using the exponent law</p>
<p><span class="math display">\[
\frac{e^a}{e^b}=e^{a-b},
\]</span></p>
<p>we obtain</p>
<p><span class="math display">\[
\boxed{
\frac{w_i}{w_j}
=
e^{s_i-s_j}.
}
\]</span></p>
<p>This is one of the central meanings of softmax. A difference in score becomes a ratio of weight. If <span class="math inline">\(s_i-s_j=0,\)</span> then</p>
<p><span class="math display">\[
\frac{w_i}{w_j}
=
e^0
=
1,
\]</span></p>
<p>so <span class="math inline">\(w_i=w_j.\)</span></p>
<p>If</p>
<p><span class="math display">\[
s_i-s_j=1,
\]</span></p>
<p>then</p>
<p><span class="math display">\[
\frac{w_i}{w_j}
=
e
\approx 2.718.
\]</span></p>
<p>The first alternative receives approximately <span class="math inline">\(2.718\)</span> times the weight of the second. If <span class="math inline">\(s_i-s_j=2,\)</span> then</p>
<p><span class="math display">\[
\frac{w_i}{w_j}
=
e^2
\approx 7.389.
\]</span></p>
<p>If <span class="math inline">\(s_i-s_j=-1,\)</span> then</p>
<p><span class="math display">\[
\frac{w_i}{w_j}
=
e^{-1}
=
\frac{1}{e}
\approx 0.368.
\]</span></p>
<p>This means that <span class="math inline">\(w_j\)</span> is approximately <span class="math inline">\(2.718\)</span> times <span class="math inline">\(w_i\)</span>. The direction and magnitude of the score difference are both preserved. Positive differences produce ratios greater than one, zero differences produce a ratio of one, and negative differences produce ratios between zero and one.</p>
</section>
<section id="why-the-exponential-arises-from-the-difference-requirement" class="level3">
<h3 class="anchored" data-anchor-id="why-the-exponential-arises-from-the-difference-requirement">Why the exponential arises from the difference requirement</h3>
<p>The exponential function does more than happen to satisfy the desired relationship. Under ordinary regularity assumptions, the requirement that differences determine ratios leads naturally to an exponential family. Suppose <span class="math inline">\(g\)</span> is positive and satisfies</p>
<p><span class="math display">\[
\frac{g(x)}{g(y)}
=
R(x-y)
\]</span></p>
<p>for some function <span class="math inline">\(R\)</span>. Set</p>
<p><span class="math display">\[
y=0.
\]</span></p>
<p>Then</p>
<p><span class="math display">\[
\frac{g(x)}{g(0)}
=
R(x).
\]</span></p>
<p>Therefore,</p>
<p><span class="math display">\[
R(x)=\frac{g(x)}{g(0)}.
\]</span></p>
<p>Now write</p>
<p><span class="math display">\[
x=u+v
\qquad\text{and}\qquad
y=v.
\]</span></p>
<p>The score difference is</p>
<p><span class="math display">\[
x-y=(u+v)-v=u.
\]</span></p>
<p>The ratio requirement gives</p>
<p><span class="math display">\[
\frac{g(u+v)}{g(v)}
=
R(u)
=
\frac{g(u)}{g(0)}.
\]</span></p>
<p>Rearranging,</p>
<p><span class="math display">\[
g(u+v)
=
\frac{g(u)g(v)}{g(0)}.
\]</span></p>
<p>Define a rescaled function</p>
<p><span class="math display">\[
f(x)=\frac{g(x)}{g(0)}.
\]</span></p>
<p>Then</p>
<p><span class="math display">\[
f(0)=1
\]</span></p>
<p>and</p>
<p><span class="math display">\[
f(u+v)=f(u)f(v).
\]</span></p>
<p>This equation says that the function converts addition in the score space into multiplication in the positive-strength space:</p>
<p><span class="math display">\[
\boxed{
f(u+v)=f(u)f(v).
}
\]</span></p>
<p>For continuous positive functions, the solutions have the form</p>
<p><span class="math display">\[
f(x)=e^{kx}
\]</span></p>
<p>for some constant <span class="math inline">\(k\)</span>. Consequently,</p>
<p><span class="math display">\[
g(x)=g(0)e^{kx}.
\]</span></p>
<p>The common positive factor <span class="math inline">\(g(0)\)</span> disappears during normalization:</p>
<p><span class="math display">\[
\frac{g(0)e^{ks_i}}
{\sum_jg(0)e^{ks_j}}
=
\frac{e^{ks_i}}
{\sum_je^{ks_j}}.
\]</span></p>
<p>Thus, the relevant family of normalized transformations is</p>
<p><span class="math display">\[
w_i
=
\frac{e^{ks_i}}
{\sum_je^{ks_j}}.
\]</span></p>
<p>If the transformation must preserve ordering, then <span class="math inline">\(k&gt;0.\)</span> The usual softmax chooses <span class="math inline">\(k=1,\)</span> giving</p>
<p><span class="math display">\[
w_i
=
\frac{e^{s_i}}
{\sum_je^{s_j}}.
\]</span></p>
<p>The parameter <span class="math inline">\(k\)</span> controls how strongly score differences are expressed in the weights. This parameter will be examined through the equivalent concept of temperature in Section 13.4.</p>
<p>This derivation reveals the philosophical reason exponentiation appears:</p>
<p><span class="math display">\[
\boxed{
\text{Scores are compared through subtraction, while positive shares are compared through division.}
}
\]</span></p>
<p>The exponential function provides the bridge because it transforms subtraction into division:</p>
<p><span class="math display">\[
e^{s_i-s_j}
=
\frac{e^{s_i}}{e^{s_j}}.
\]</span></p>
</section>
<section id="common-score-shifts-disappear" class="level3">
<h3 class="anchored" data-anchor-id="common-score-shifts-disappear">Common score shifts disappear</h3>
<p>Suppose the same constant <span class="math inline">\(c\)</span> is added to every score:</p>
<p><span class="math display">\[
s_i'=s_i+c.
\]</span></p>
<p>The softmax weight becomes</p>
<p><span class="math display">\[
w_i'
=
\frac{e^{s_i+c}}
{\sum_je^{s_j+c}}.
\]</span></p>
<p>Using</p>
<p><span class="math display">\[
e^{s_i+c}=e^{s_i}e^c,
\]</span></p>
<p>we obtain</p>
<p><span class="math display">\[
w_i'
=
\frac{e^{s_i}e^c}
{\sum_je^{s_j}e^c}.
\]</span></p>
<p>The common factor <span class="math inline">\(e^c\)</span> can be factored from the denominator:</p>
<p><span class="math display">\[
w_i'
=
\frac{e^{s_i}e^c}
{e^c\sum_je^{s_j}}.
\]</span></p>
<p>It cancels:</p>
<p><span class="math display">\[
w_i'
=
\frac{e^{s_i}}
{\sum_je^{s_j}}
=
w_i.
\]</span></p>
<p>Therefore,</p>
<p><span class="math display">\[
\boxed{
\operatorname{softmax}(\mathbf{s}+c\mathbf{1})
=
\operatorname{softmax}(\mathbf{s}).
}
\]</span></p>
<p>Softmax is translation invariant with respect to a common score shift. For example, the vectors</p>
<p><span class="math display">\[
\begin{bmatrix}
-2\\
1\\
3
\end{bmatrix}
\]</span></p>
<p>and</p>
<p><span class="math display">\[
\begin{bmatrix}
8\\
11\\
13
\end{bmatrix}
\]</span></p>
<p>differ only by adding <span class="math inline">\(10\)</span> to every coordinate. Their pairwise differences are identical, so softmax assigns them exactly the same weights.</p>
<p>This property expresses an important modeling idea. If the scores describe comparative support, then raising every score by the same amount provides no evidence favoring one alternative over another. The allocation should therefore remain unchanged.</p>
<p>Ordinary division by the score total does not have this property. Softmax acquires it because exponentiation converts the common additive shift into a common multiplicative factor, which normalization then removes. The mechanism is</p>
<p><span class="math display">\[
\boxed{
\text{common addition in score space}
\overset{\exp}{\longrightarrow}
\text{common multiplication in strength space}
\overset{\text{normalization}}{\longrightarrow}
\text{cancellation}.
}
\]</span></p>
</section>
<section id="a-complete-numerical-example" class="level3">
<h3 class="anchored" data-anchor-id="a-complete-numerical-example">A complete numerical example</h3>
<p>Consider the score vector</p>
<p><span class="math display">\[
\mathbf{s}
=
\begin{bmatrix}
-2\\
1\\
3
\end{bmatrix}.
\]</span></p>
<p>Ordinary division by the score total would give</p>
<p><span class="math display">\[
\frac{1}{-2+1+3}
\begin{bmatrix}
-2\\
1\\
3
\end{bmatrix}
=
\frac{1}{2}
\begin{bmatrix}
-2\\
1\\
3
\end{bmatrix}
=
\begin{bmatrix}
-1\\
0.5\\
1.5
\end{bmatrix}.
\]</span></p>
<p>The entries sum to one, but the first is negative and the third exceeds one. They are not convex weights. Softmax first exponentiates the scores:</p>
<p><span class="math display">\[
e^{-2}\approx 0.1353,
\]</span></p>
<p><span class="math display">\[
e^1\approx 2.7183,
\]</span></p>
<p>and</p>
<p><span class="math display">\[
e^3\approx 20.0855.
\]</span></p>
<p>The transformed strengths are therefore</p>
<p><span class="math display">\[
\mathbf{a}
\approx
\begin{bmatrix}
0.1353\\
2.7183\\
20.0855
\end{bmatrix}.
\]</span></p>
<p>Their total is</p>
<p><span class="math display">\[
T
=
0.1353+2.7183+20.0855
\approx 22.9391.
\]</span></p>
<p>Dividing each positive strength by the total gives</p>
<p><span class="math display">\[
\mathbf{w}
\approx
\begin{bmatrix}
0.1353/22.9391\\
2.7183/22.9391\\
20.0855/22.9391
\end{bmatrix}.
\]</span></p>
<p>Thus,</p>
<p><span class="math display">\[
\boxed{
\mathbf{w}
\approx
\begin{bmatrix}
0.0059\\
0.1185\\
0.8756
\end{bmatrix}.
}
\]</span></p>
<p>Every weight is positive, and</p>
<p><span class="math display">\[
0.0059+0.1185+0.8756\approx 1.
\]</span></p>
<p>The score ordering</p>
<p><span class="math display">\[
3&gt;1&gt;-2
\]</span></p>
<p>has become the weight ordering</p>
<p><span class="math display">\[
0.8756&gt;0.1185&gt;0.0059.
\]</span></p>
<p>The ratio between the third and second weights is</p>
<p><span class="math display">\[
\frac{w_3}{w_2}
=
e^{3-1}
=
e^2
\approx 7.389.
\]</span></p>
<p>Indeed,</p>
<p><span class="math display">\[
\frac{0.8756}{0.1185}
\approx 7.389.
\]</span></p>
<p>The ratio between the second and first weights is</p>
<p><span class="math display">\[
\frac{w_2}{w_1}
=
e^{1-(-2)}
=
e^3
\approx 20.086.
\]</span></p>
<p>The numerical weights are therefore not arbitrary normalized versions of the scores. They encode the score differences multiplicatively.</p>
</section>
<section id="equal-scores-produce-uniform-weights" class="level3">
<h3 class="anchored" data-anchor-id="equal-scores-produce-uniform-weights">Equal scores produce uniform weights</h3>
<p>Suppose every score is equal:</p>
<p><span class="math display">\[
s_1=s_2=\cdots=s_n=c.
\]</span></p>
<p>Exponentiation produces equal positive strengths:</p>
<p><span class="math display">\[
e^{s_1}=e^{s_2}=\cdots=e^{s_n}=e^c.
\]</span></p>
<p>The denominator is</p>
<p><span class="math display">\[
\sum_{j=1}^{n}e^{s_j}
=
ne^c.
\]</span></p>
<p>Therefore, every weight is</p>
<p><span class="math display">\[
w_i
=
\frac{e^c}{ne^c}
=
\frac{1}{n}.
\]</span></p>
<p>Hence,</p>
<p><span class="math display">\[
\boxed{
\operatorname{softmax}
\begin{pmatrix}
c,\ldots,c
\end{pmatrix}
=
\begin{pmatrix}
1/n,\ldots,1/n
\end{pmatrix}.
}
\]</span></p>
<p>When the scores provide no reason to distinguish among alternatives, softmax divides the total contribution equally. For example,</p>
<p><span class="math display">\[
\operatorname{softmax}
\begin{pmatrix}
0,0,0
\end{pmatrix}
=
\begin{pmatrix}
1/3,1/3,1/3
\end{pmatrix}.
\]</span></p>
<p>Unlike ordinary division by the total, softmax handles the all-zero score vector naturally. Exponentiation transforms each zero into one <span class="math inline">\(e^0=1.\)</span> The vector of zero scores becomes a vector of equal positive strengths:</p>
<p><span class="math display">\[
\begin{bmatrix}
0\\
0\\
0
\end{bmatrix}
\overset{\exp}{\longrightarrow}
\begin{bmatrix}
1\\
1\\
1
\end{bmatrix}
\overset{\text{normalize}}{\longrightarrow}
\begin{bmatrix}
1/3\\
1/3\\
1/3
\end{bmatrix}.
\]</span></p>
<p>The zero score does not become zero strength. It becomes the reference strength <span class="math inline">\(1\)</span>. Positive scores produce strengths greater than one, while negative scores produce strengths between zero and one:</p>
<p><span class="math display">\[
s&gt;0\Longrightarrow e^s&gt;1,
\]</span></p>
<p><span class="math display">\[
s=0\Longrightarrow e^s=1,
\]</span></p>
<p><span class="math display">\[
s&lt;0\Longrightarrow 0&lt;e^s&lt;1.
\]</span></p>
</section>
<section id="exponentiation-accentuates-score-differences" class="level3">
<h3 class="anchored" data-anchor-id="exponentiation-accentuates-score-differences">Exponentiation accentuates score differences</h3>
<p>The exponential function is increasing, but it is not linear. Equal additive increases in a score produce equal multiplicative increases in strength.</p>
<p>If a score rises by <span class="math inline">\(\Delta\)</span>, then</p>
<p><span class="math display">\[
e^{s+\Delta}
=
e^se^\Delta.
\]</span></p>
<p>Thus, increasing a score by <span class="math inline">\(\Delta\)</span> multiplies its unnormalized strength by</p>
<p><span class="math display">\[
e^\Delta.
\]</span></p>
<p>For example, increasing a score by <span class="math inline">\(1\)</span> multiplies its strength by <span class="math inline">\(e\)</span>:</p>
<p><span class="math display">\[
e^{s+1}=e\,e^s.
\]</span></p>
<p>Increasing it by <span class="math inline">\(2\)</span> multiplies its strength by <span class="math inline">\(e^2\)</span>:</p>
<p><span class="math display">\[
e^{s+2}=e^2e^s.
\]</span></p>
<p>This is different from adding scores directly as strengths. Under a linear transformation, increasing a score by one adds the same absolute amount. Under exponentiation, it multiplies the current strength by the same factor. Consequently, separated scores can produce strongly concentrated weights. For the scores</p>
<p><span class="math display">\[
\begin{bmatrix}
2\\
5\\
3
\end{bmatrix},
\]</span></p>
<p>ordinary positive normalization gives</p>
<p><span class="math display">\[
\begin{bmatrix}
0.2\\
0.5\\
0.3
\end{bmatrix}.
\]</span></p>
<p>Softmax gives</p>
<p><span class="math display">\[
\frac{1}{e^2+e^5+e^3}
\begin{bmatrix}
e^2\\
e^5\\
e^3
\end{bmatrix}
\approx
\begin{bmatrix}
0.0420\\
0.8438\\
0.1142
\end{bmatrix}.
\]</span></p>
<p>Both transformations preserve the ordering</p>
<p><span class="math display">\[
5&gt;3&gt;2.
\]</span></p>
<p>But they interpret the numerical relationships differently. Ordinary normalization preserves the ratios of the positive scores:</p>
<p><span class="math display">\[
\frac{5}{2}=2.5.
\]</span></p>
<p>Softmax converts score differences into weight ratios:</p>
<p><span class="math display">\[
\frac{w_2}{w_1}
=
e^{5-2}
=
e^3
\approx 20.086.
\]</span></p>
<p>Neither result is universally correct independent of context. Ordinary normalization is appropriate when the inputs already represent positive amounts whose ratios have direct meaning. Softmax is appropriate when the inputs are unrestricted relative scores and additive score differences should determine multiplicative allocation ratios.</p>
</section>
<section id="why-the-base-is-usually-e" class="level3">
<h3 class="anchored" data-anchor-id="why-the-base-is-usually-e">Why the base is usually (e)</h3>
<p>Any exponential base <span class="math inline">\(b&gt;1\)</span> could produce positive, order-preserving strengths:</p>
<p><span class="math display">\[
g(s)=b^s.
\]</span></p>
<p>The resulting normalized weights would be</p>
<p><span class="math display">\[
w_i
=
\frac{b^{s_i}}
{\sum_jb^{s_j}}.
\]</span></p>
<p>Since</p>
<p><span class="math display">\[
b^s=e^{s\ln b},
\]</span></p>
<p>using base <span class="math inline">\(b\)</span> is equivalent to multiplying every score by <span class="math inline">\(\ln b\)</span> before applying the natural exponential:</p>
<p><span class="math display">\[
b^{s_i}
=
e^{(\ln b)s_i}.
\]</span></p>
<p>Thus, changing the base changes the sensitivity of the allocation to score differences. It does not create a fundamentally different family of transformations. The natural exponential is conventionally used because it interacts especially cleanly with calculus:</p>
<p><span class="math display">\[
\frac{d}{ds}e^s=e^s.
\]</span></p>
<p>Its derivative has the same form as the function itself, which simplifies the derivatives needed to train machine-learning models. The use of <span class="math inline">\(e\)</span> therefore combines algebraic and computational advantages. It maps real scores to positive strengths, converts differences into ratios, supports common-shift invariance, and has exceptionally simple derivatives.</p>
</section>
<section id="implementing-the-two-stages-directly" class="level3">
<h3 class="anchored" data-anchor-id="implementing-the-two-stages-directly">Implementing the two stages directly</h3>
<p>The mathematical construction can be expressed transparently in Python:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>scores <span class="op">=</span> np.array([<span class="op">-</span><span class="fl">2.0</span>, <span class="fl">1.0</span>, <span class="fl">3.0</span>])</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>positive_strengths <span class="op">=</span> np.exp(scores)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>weights <span class="op">=</span> positive_strengths <span class="op">/</span> np.<span class="bu">sum</span>(positive_strengths)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(positive_strengths)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(weights)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(np.<span class="bu">sum</span>(weights))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The approximate output is</p>
<pre class="text"><code>[ 0.13533528  2.71828183 20.08553692]
[0.00589975 0.11849965 0.87560060]
1.0</code></pre>
<p>The two lines</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>positive_strengths <span class="op">=</span> np.exp(scores)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>weights <span class="op">=</span> positive_strengths <span class="op">/</span> np.<span class="bu">sum</span>(positive_strengths)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>represent two different mathematical acts. The first line transforms unrestricted comparative scores into positive strengths. The second line turns those strengths into shares of their total. Combining the operations gives the direct implementation:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> softmax(scores):</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    positive_strengths <span class="op">=</span> np.exp(scores)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> positive_strengths <span class="op">/</span> np.<span class="bu">sum</span>(positive_strengths)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>This code expresses the formula</p>
<p><span class="math display">\[
\operatorname{softmax}(\mathbf{s})_i
=
\frac{e^{s_i}}
{\sum_je^{s_j}}.
\]</span></p>
<p>However, this naive implementation can fail numerically when the scores are large because exponentiation grows rapidly. The mathematical shift invariance derived earlier will allow us to solve that problem without changing the resulting weights.</p>
</section>
<section id="what-exponentiation-contributes" class="level3">
<h3 class="anchored" data-anchor-id="what-exponentiation-contributes">What exponentiation contributes</h3>
<p>The complete role of exponentiation can now be stated precisely. It guarantees positive strengths:</p>
<p><span class="math display">\[
e^{s_i}&gt;0.
\]</span></p>
<p>It preserves score ordering:</p>
<p><span class="math display">\[
s_i&gt;s_j
\Longrightarrow
e^{s_i}&gt;e^{s_j}.
\]</span></p>
<p>It preserves equality:</p>
<p><span class="math display">\[
s_i=s_j
\Longrightarrow
e^{s_i}=e^{s_j}.
\]</span></p>
<p>It converts score differences into strength ratios:</p>
<p><span class="math display">\[
\frac{e^{s_i}}{e^{s_j}}
=
e^{s_i-s_j}.
\]</span></p>
<p>It converts a common additive shift into a common multiplicative factor:</p>
<p><span class="math display">\[
e^{s_i+c}=e^ce^{s_i}.
\]</span></p>
<p>Normalization then removes that common factor:</p>
<p><span class="math display">\[
\frac{e^{s_i+c}}{\sum_je^{s_j+c}}
=
\frac{e^{s_i}}{\sum_je^{s_j}}.
\]</span></p>
<p>The entire construction can therefore be summarized as</p>
<p><span class="math display">\[
\boxed{
\begin{aligned}
\text{unrestricted score}
&amp;\overset{\exp}{\longrightarrow}
\text{positive relative strength}\\[4pt]
&amp;\overset{\text{divide by total}}{\longrightarrow}
\text{normalized share}.
\end{aligned}
}
\]</span></p>
<p>Exponentiation does not itself produce probabilities or weights. It produces positive strengths. Division by their total completes the transformation. In the next section, these two operations will be treated as one mechanism: softmax. We will examine how softmax behaves as score differences change, why it is called a <em>soft</em> form of selection, how temperature controls the concentration of its output, and how common-shift invariance produces a numerically stable implementation.</p>
</section>
</section>
<section id="softmax-as-a-smooth-allocation-mechanism" class="level2">
<h2 class="anchored" data-anchor-id="softmax-as-a-smooth-allocation-mechanism">13.4 Softmax as a Smooth Allocation Mechanism</h2>
<p>The previous sections constructed the two operations contained inside softmax. Given unrestricted scores</p>
<p><span class="math display">\[
s_1,s_2,\ldots,s_n,
\]</span></p>
<p>exponentiation produces positive strengths:</p>
<p><span class="math display">\[
a_i=e^{s_i}&gt;0.
\]</span></p>
<p>Division by their total converts those strengths into normalized shares:</p>
<p><span class="math display">\[
w_i
=
\frac{a_i}{\sum_ja_j}.
\]</span></p>
<p>Combining the two stages gives</p>
<p><span class="math display">\[
\boxed{
\operatorname{softmax}(\mathbf{s})_i
=
\frac{e^{s_i}}
{\sum_{j=1}^{n}e^{s_j}}.
}
\]</span></p>
<p>Softmax is therefore not a mysterious atomic operation. It is a composition:</p>
<p><span class="math display">\[
\boxed{
\operatorname{softmax}
=
\operatorname{normalize}
\circ
\operatorname{exponentiate}.
}
\]</span></p>
<p>The exponential function converts unrestricted real scores into positive relative strengths. Normalization then converts those strengths into shares of a unit total.</p>
<p>For every finite score vector,</p>
<p><span class="math display">\[
s_i\in\mathbb{R},
\]</span></p>
<p>the output satisfies</p>
<p><span class="math display">\[
0&lt;w_i&lt;1
\]</span></p>
<p>and</p>
<p><span class="math display">\[
\sum_{i=1}^{n}w_i=1.
\]</span></p>
<p>Thus,</p>
<p><span class="math display">\[
\operatorname{softmax}:
\mathbb{R}^n
\longrightarrow
\operatorname{int}(\Delta^{n-1}),
\]</span></p>
<p>where <span class="math inline">\(\operatorname{int}(\Delta^{n-1})\)</span> denotes the interior of the simplex. For finite scores, every weight is strictly positive. Softmax can make a weight extremely small, but in exact mathematics it does not make that weight exactly zero.</p>
<section id="from-hard-selection-to-soft-selection" class="level3">
<h3 class="anchored" data-anchor-id="from-hard-selection-to-soft-selection">From hard selection to soft selection</h3>
<p>Suppose a system produces the scores</p>
<p><span class="math display">\[
\mathbf{s}
=
\begin{bmatrix}
2\\
5\\
3
\end{bmatrix}.
\]</span></p>
<p>Hard selection chooses the index of the largest score:</p>
<p><span class="math display">\[
k
=
\operatorname*{arg\,max}_i s_i
=
2.
\]</span></p>
<p>The corresponding one-hot selection vector is</p>
<p><span class="math display">\[
\mathbf{I}
=
\begin{bmatrix}
0\\
1\\
0
\end{bmatrix}.
\]</span></p>
<p>If the alternatives are <span class="math inline">\(A_1,A_2,A_3\)</span>, the hard-selected result is</p>
<p><span class="math display">\[
C_{\text{hard}}
=
0A_1+1A_2+0A_3
=
A_2.
\]</span></p>
<p>Softmax preserves the ranking but distributes contribution across all alternatives:</p>
<p><span class="math display">\[
\operatorname{softmax}
\begin{pmatrix}
2,5,3
\end{pmatrix}
\approx
\begin{pmatrix}
0.0420,0.8438,0.1142
\end{pmatrix}.
\]</span></p>
<p>The resulting soft combination is</p>
<p><span class="math display">\[
C_{\text{soft}}
=
0.0420A_1
+
0.8438A_2
+
0.1142A_3.
\]</span></p>
<p>The second alternative still dominates, but the first and third alternatives are not completely discarded.</p>
<p>This explains the word <em>soft</em>. Hard selection assigns the complete unit of contribution to one alternative:</p>
<p><span class="math display">\[
I_i\in\{0,1\}.
\]</span></p>
<p>Soft selection permits intermediate contribution:</p>
<p><span class="math display">\[
0&lt;w_i&lt;1.
\]</span></p>
<p>The difference is not that softmax ignores the winner. It preserves the same winner:</p>
<p><span class="math display">\[
\operatorname*{arg\,max}_i
\operatorname{softmax}(\mathbf{s})_i
=
\operatorname*{arg\,max}_i s_i.
\]</span></p>
<p>The difference is that softmax retains information about the relative strengths of the alternatives instead of reducing the entire score vector to one index.</p>
<p><span class="math display">\[
\boxed{
\begin{aligned}
\operatorname{argmax}
&amp;:\quad
\text{Which alternative wins?}\\[4pt]
\operatorname{softmax}
&amp;:\quad
\text{How should one unit of contribution be distributed?}
\end{aligned}
}
\]</span></p>
</section>
<section id="why-smooth-allocation-matters" class="level3">
<h3 class="anchored" data-anchor-id="why-smooth-allocation-matters">Why smooth allocation matters</h3>
<p>The argmax operation changes discontinuously at a tie. Consider two scores:</p>
<p><span class="math display">\[
\mathbf{s}
=
\begin{bmatrix}
1.00\\
0.99
\end{bmatrix}.
\]</span></p>
<p>The first alternative wins. If the first score decreases slightly,</p>
<p><span class="math display">\[
\mathbf{s}'
=
\begin{bmatrix}
0.98\\
0.99
\end{bmatrix},
\]</span></p>
<p>the second alternative wins.</p>
<p>The score vector changed only slightly, but the one-hot output changed completely:</p>
<p><span class="math display">\[
\begin{bmatrix}
1\\
0
\end{bmatrix}
\longrightarrow
\begin{bmatrix}
0\\
1
\end{bmatrix}.
\]</span></p>
<p>Softmax responds continuously. For two scores,</p>
<p><span class="math display">\[
w_1
=
\frac{e^{s_1}}{e^{s_1}+e^{s_2}},
\qquad
w_2
=
\frac{e^{s_2}}{e^{s_1}+e^{s_2}}.
\]</span></p>
<p>The first vector produces weights close to</p>
<p><span class="math display">\[
\begin{bmatrix}
0.5025\\
0.4975
\end{bmatrix},
\]</span></p>
<p>while the second produces weights close to</p>
<p><span class="math display">\[
\begin{bmatrix}
0.4975\\
0.5025
\end{bmatrix}.
\]</span></p>
<p>A small change in the scores produces a small change in the allocation.</p>
<p>This continuity is crucial during machine learning. Training usually changes model parameters through small numerical updates. These parameter changes produce small changes in scores, and a smooth output transformation allows the effect of those changes to be measured through derivatives.</p>
<p>Argmax is useful when a final discrete decision is required, but it does not provide a useful gradient through the point of selection. Softmax creates a differentiable path from scores to normalized outputs.</p>
<p>The conceptual division is therefore:</p>
<p><span class="math display">\[
\boxed{
\text{softmax during comparison and learning}
\quad\longrightarrow\quad
\text{argmax when a hard decision is required}.
}
\]</span></p>
<p>This is not an absolute rule for every system, but it describes a common machine-learning design.</p>
</section>
<section id="softmax-creates-competition-through-a-shared-denominator" class="level3">
<h3 class="anchored" data-anchor-id="softmax-creates-competition-through-a-shared-denominator">Softmax creates competition through a shared denominator</h3>
<p>Each softmax weight is</p>
<p><span class="math display">\[
w_i
=
\frac{e^{s_i}}
{\sum_je^{s_j}}.
\]</span></p>
<p>The numerator depends directly on score <span class="math inline">\(s_i\)</span>, but the denominator depends on every score. Consequently, the alternatives are coupled.</p>
<p>If <span class="math inline">\(s_i\)</span> increases while the other scores remain fixed, then <span class="math inline">\(e^{s_i}\)</span> increases. This increases the numerator of <span class="math inline">\(w_i\)</span>, so <span class="math inline">\(w_i\)</span> rises. At the same time, it increases the shared denominator used by every other weight, so the remaining weights fall.</p>
<p>This is necessary because</p>
<p><span class="math display">\[
\sum_iw_i=1.
\]</span></p>
<p>The weights cannot all independently increase. A larger share in one position must be balanced by smaller shares elsewhere.</p>
<p>For example, compare</p>
<p><span class="math display">\[
\mathbf{s}^{(a)}
=
\begin{bmatrix}
1\\
1\\
1
\end{bmatrix}
\]</span></p>
<p>with</p>
<p><span class="math display">\[
\mathbf{s}^{(b)}
=
\begin{bmatrix}
1\\
2\\
1
\end{bmatrix}.
\]</span></p>
<p>Equal scores produce a uniform allocation:</p>
<p><span class="math display">\[
\operatorname{softmax}(\mathbf{s}^{(a)})
=
\begin{bmatrix}
1/3\\
1/3\\
1/3
\end{bmatrix}.
\]</span></p>
<p>Increasing only the second score produces approximately</p>
<p><span class="math display">\[
\operatorname{softmax}(\mathbf{s}^{(b)})
\approx
\begin{bmatrix}
0.212\\
0.576\\
0.212
\end{bmatrix}.
\]</span></p>
<p>The additional support given to the second alternative increases its share from approximately <span class="math inline">\(0.333\)</span> to <span class="math inline">\(0.576\)</span>. Since the total must remain one, the shares assigned to the first and third alternatives both decrease.</p>
<p>Softmax therefore implements a constrained competition:</p>
<p><span class="math display">\[
\boxed{
\text{greater support for one alternative}
\Longrightarrow
\text{greater share for it and less total share elsewhere}.
}
\]</span></p>
</section>
<section id="the-derivative-exposes-the-competitive-structure" class="level3">
<h3 class="anchored" data-anchor-id="the-derivative-exposes-the-competitive-structure">The derivative exposes the competitive structure</h3>
<p>Let</p>
<p><span class="math display">\[
w_i
=
\frac{e^{s_i}}
{\sum_ke^{s_k}}.
\]</span></p>
<p>The effect of changing score <span class="math inline">\(s_j\)</span> on weight <span class="math inline">\(w_i\)</span> is</p>
<p><span class="math display">\[
\boxed{
\frac{\partial w_i}{\partial s_j}
=
w_i(\delta_{ij}-w_j),
}
\]</span></p>
<p>where</p>
<p><span class="math display">\[
\delta_{ij}
=
\begin{cases}
1, &amp; i=j,\\
0, &amp; i\neq j
\end{cases}
\]</span></p>
<p>is the Kronecker delta. When <span class="math inline">\(i=j\)</span>, the derivative becomes</p>
<p><span class="math display">\[
\frac{\partial w_i}{\partial s_i}
=
w_i(1-w_i).
\]</span></p>
<p>Since</p>
<p><span class="math display">\[
0&lt;w_i&lt;1,
\]</span></p>
<p>we have</p>
<p><span class="math display">\[
w_i(1-w_i)&gt;0.
\]</span></p>
<p>Increasing an alternative’s own score increases its weight.</p>
<p>When <span class="math inline">\(i\neq j\)</span>, the derivative becomes</p>
<p><span class="math display">\[
\frac{\partial w_i}{\partial s_j}
=
-w_iw_j&lt;0.
\]</span></p>
<p>Increasing the score of another alternative decreases weight <span class="math inline">\(w_i\)</span>.</p>
<p>The derivatives also preserve the unit-total constraint. Since</p>
<p><span class="math display">\[
\sum_iw_i=1,
\]</span></p>
<p>differentiating with respect to any score <span class="math inline">\(s_j\)</span> gives</p>
<p><span class="math display">\[
\sum_i
\frac{\partial w_i}{\partial s_j}
=
0.
\]</span></p>
<p>All weight changes must balance.</p>
<p>The derivative therefore captures the same semantics that were previously described in words:</p>
<p><span class="math display">\[
\boxed{
\text{softmax redistributes a fixed unit of influence rather than creating independent outputs}.
}
\]</span></p>
</section>
<section id="equal-scores-close-scores-and-separated-scores" class="level3">
<h3 class="anchored" data-anchor-id="equal-scores-close-scores-and-separated-scores">Equal scores, close scores, and separated scores</h3>
<p>The behavior of softmax is governed by differences among scores.</p>
<p>If every score is equal,</p>
<p><span class="math display">\[
s_1=s_2=\cdots=s_n,
\]</span></p>
<p>then every alternative receives the same weight:</p>
<p><span class="math display">\[
w_i=\frac{1}{n}.
\]</span></p>
<p>If the scores are close together, the weights are relatively diffuse. For example,</p>
<p><span class="math display">\[
\operatorname{softmax}
\begin{pmatrix}
2.0,2.1,1.9
\end{pmatrix}
\approx
\begin{pmatrix}
0.332,0.367,0.301
\end{pmatrix}.
\]</span></p>
<p>No alternative dominates because the score differences are small.</p>
<p>If one score is substantially larger than the others, the allocation becomes concentrated. For example,</p>
<p><span class="math display">\[
\operatorname{softmax}
\begin{pmatrix}
2,8,1
\end{pmatrix}
\approx
\begin{pmatrix}
0.0025,0.9966,0.0009
\end{pmatrix}.
\]</span></p>
<p>Softmax has not changed its mathematical rule. The concentration emerges from the exponential ratios:</p>
<p><span class="math display">\[
\frac{w_2}{w_1}
=
e^{8-2}
=
e^6
\approx 403.43,
\]</span></p>
<p>and</p>
<p><span class="math display">\[
\frac{w_2}{w_3}
=
e^{8-1}
=
e^7
\approx 1096.63.
\]</span></p>
<p>The absolute values of the scores are not decisive. Their differences are.</p>
<p>For example,</p>
<p><span class="math display">\[
\begin{bmatrix}
2\\
8\\
1
\end{bmatrix}
\]</span></p>
<p>and</p>
<p><span class="math display">\[
\begin{bmatrix}
102\\
108\\
101
\end{bmatrix}
\]</span></p>
<p>produce exactly the same softmax weights because the second vector is obtained by adding <span class="math inline">\(100\)</span> to every score.</p>
</section>
<section id="temperature-controls-the-concentration-of-the-allocation" class="level3">
<h3 class="anchored" data-anchor-id="temperature-controls-the-concentration-of-the-allocation">Temperature controls the concentration of the allocation</h3>
<p>The standard softmax can be generalized by introducing a positive temperature parameter <span class="math inline">\(\tau\)</span>:</p>
<p><span class="math display">\[
\boxed{
w_i(\tau)
=
\frac{e^{s_i/\tau}}
{\sum_je^{s_j/\tau}},
\qquad
\tau&gt;0.
}
\]</span></p>
<p>Temperature changes the scale of the score differences before exponentiation. The ratio between two weights becomes</p>
<p><span class="math display">\[
\frac{w_i(\tau)}{w_j(\tau)}
=
e^{(s_i-s_j)/\tau}.
\]</span></p>
<p>The denominator <span class="math inline">\(\tau\)</span> determines how strongly a score difference affects the weight ratio.</p>
<p>When <span class="math inline">\(\tau\)</span> is large, the divided score differences become smaller:</p>
<p><span class="math display">\[
\frac{s_i-s_j}{\tau}
\longrightarrow 0
\qquad\text{as}\qquad
\tau\longrightarrow\infty.
\]</span></p>
<p>Then</p>
<p><span class="math display">\[
e^{(s_i-s_j)/\tau}
\longrightarrow e^0=1.
\]</span></p>
<p>The weights become more similar and approach the uniform distribution:</p>
<p><span class="math display">\[
\boxed{
\lim_{\tau\to\infty}
w_i(\tau)
=
\frac{1}{n}.
}
\]</span></p>
<p>A high temperature therefore produces a softer, more diffuse allocation.</p>
<p>When <span class="math inline">\(\tau\)</span> is small, score differences are enlarged:</p>
<p><span class="math display">\[
\left|
\frac{s_i-s_j}{\tau}
\right|
&gt;
|s_i-s_j|
\qquad\text{when}\qquad
0&lt;\tau&lt;1.
\]</span></p>
<p>If <span class="math inline">\(s_k\)</span> is the unique maximum score, then for every <span class="math inline">\(j\neq k\)</span>,</p>
<p><span class="math display">\[
s_k-s_j&gt;0.
\]</span></p>
<p>As <span class="math inline">\(\tau\)</span> approaches zero,</p>
<p><span class="math display">\[
e^{(s_k-s_j)/\tau}
\longrightarrow\infty.
\]</span></p>
<p>The maximum-score alternative dominates:</p>
<p><span class="math display">\[
\boxed{
\lim_{\tau\to0^+}
w_k(\tau)=1,
\qquad
\lim_{\tau\to0^+}
w_j(\tau)=0
\quad(j\neq k).
}
\]</span></p>
<p>A low temperature therefore makes softmax approach hard argmax selection.</p>
<p>For the scores</p>
<p><span class="math display">\[
\mathbf{s}
=
\begin{bmatrix}
2\\
5\\
3
\end{bmatrix},
\]</span></p>
<p>different temperatures produce approximately the following allocations:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Temperature <span class="math inline">\(\tau\)</span></th>
<th>Softmax weights</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><span class="math inline">\(5\)</span></td>
<td><span class="math inline">\((0.247,\ 0.451,\ 0.302)\)</span></td>
<td>Diffuse allocation</td>
</tr>
<tr class="even">
<td style="text-align: right;"><span class="math inline">\(2\)</span></td>
<td><span class="math inline">\((0.140,\ 0.629,\ 0.231)\)</span></td>
<td>Moderate preference</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><span class="math inline">\(1\)</span></td>
<td><span class="math inline">\((0.042,\ 0.844,\ 0.114)\)</span></td>
<td>Standard softmax</td>
</tr>
<tr class="even">
<td style="text-align: right;"><span class="math inline">\(0.5\)</span></td>
<td><span class="math inline">\((0.002,\ 0.980,\ 0.018)\)</span></td>
<td>Nearly hard selection</td>
</tr>
</tbody>
</table>
<p>The score ordering remains unchanged at every positive temperature. Temperature changes how sharply that ordering is expressed.</p>
<p>The reciprocal quantity</p>
<p><span class="math display">\[
\beta=\frac{1}{\tau}
\]</span></p>
<p>is sometimes called inverse temperature. The temperature form</p>
<p><span class="math display">\[
e^{s_i/\tau}
\]</span></p>
<p>and the scale form</p>
<p><span class="math display">\[
e^{\beta s_i}
\]</span></p>
<p>describe the same mechanism.</p>
<p>Temperature is useful when a system must control the balance between concentration and diffusion. In sampling from a language model, for example, a lower temperature concentrates probability on higher-scoring tokens, while a higher temperature distributes more probability among alternatives. In knowledge distillation, a higher temperature may expose relationships among non-winning classes by preventing the largest score from dominating completely.</p>
<p>Temperature does not create new evidence. It changes how strongly existing score differences are translated into allocation differences.</p>
</section>
<section id="why-the-direct-implementation-can-overflow" class="level3">
<h3 class="anchored" data-anchor-id="why-the-direct-implementation-can-overflow">Why the direct implementation can overflow</h3>
<p>The mathematical expression</p>
<p><span class="math display">\[
e^{s_i}
\]</span></p>
<p>is defined for every finite real score. Computer arithmetic, however, can represent only a finite range of numerical values.</p>
<p>Exponentiation grows rapidly:</p>
<p><span class="math display">\[
e^{10}\approx 22\,026,
\]</span></p>
<p><span class="math display">\[
e^{100}\approx 2.688\times 10^{43},
\]</span></p>
<p>and</p>
<p><span class="math display">\[
e^{1000}\approx 1.970\times 10^{434}.
\]</span></p>
<p>A standard 64-bit floating-point number cannot represent <span class="math inline">\(e^{1000}\)</span>. A direct NumPy calculation may therefore overflow:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>scores <span class="op">=</span> np.array([<span class="fl">1000.0</span>, <span class="fl">1001.0</span>, <span class="fl">1002.0</span>])</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>strengths <span class="op">=</span> np.exp(scores)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>weights <span class="op">=</span> strengths <span class="op">/</span> np.<span class="bu">sum</span>(strengths)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The values in <code>strengths</code> may become <code>inf</code>. The normalization can then produce undefined expressions such as</p>
<pre class="text"><code>inf / inf</code></pre>
<p>resulting in <code>nan</code>.</p>
<p>This is a mechanical failure of finite numerical representation, not a failure of the mathematical definition.</p>
</section>
<section id="shift-invariance-produces-numerical-stability" class="level3">
<h3 class="anchored" data-anchor-id="shift-invariance-produces-numerical-stability">Shift invariance produces numerical stability</h3>
<p>Section 13.3 proved that adding the same constant to every score does not change softmax:</p>
<p><span class="math display">\[
\operatorname{softmax}(\mathbf{s}+c\mathbf{1})
=
\operatorname{softmax}(\mathbf{s}).
\]</span></p>
<p>We can therefore choose a convenient shift without changing the mathematical result.</p>
<p>Let</p>
<p><span class="math display">\[
m=\max_i s_i.
\]</span></p>
<p>Subtract <span class="math inline">\(m\)</span> from every score:</p>
<p><span class="math display">\[
s_i'=s_i-m.
\]</span></p>
<p>Then</p>
<p><span class="math display">\[
\max_i s_i'=0,
\]</span></p>
<p>and every shifted score satisfies</p>
<p><span class="math display">\[
s_i'\leq 0.
\]</span></p>
<p>The softmax becomes</p>
<p><span class="math display">\[
\boxed{
w_i
=
\frac{e^{s_i-m}}
{\sum_je^{s_j-m}}.
}
\]</span></p>
<p>Because every exponent is nonpositive,</p>
<p><span class="math display">\[
0&lt;e^{s_i-m}\leq 1.
\]</span></p>
<p>The largest shifted score is zero, so at least one transformed strength equals</p>
<p><span class="math display">\[
e^0=1.
\]</span></p>
<p>This prevents the denominator from becoming zero while avoiding extremely large exponential values.</p>
<p>For</p>
<p><span class="math display">\[
\mathbf{s}
=
\begin{bmatrix}
1000\\
1001\\
1002
\end{bmatrix},
\]</span></p>
<p>the maximum is</p>
<p><span class="math display">\[
m=1002.
\]</span></p>
<p>The shifted scores are</p>
<p><span class="math display">\[
\mathbf{s}-m\mathbf{1}
=
\begin{bmatrix}
-2\\
-1\\
0
\end{bmatrix}.
\]</span></p>
<p>The stable softmax is therefore</p>
<p><span class="math display">\[
\frac{1}{e^{-2}+e^{-1}+e^0}
\begin{bmatrix}
e^{-2}\\
e^{-1}\\
e^0
\end{bmatrix}.
\]</span></p>
<p>Numerically,</p>
<p><span class="math display">\[
\operatorname{softmax}
\begin{pmatrix}
1000,1001,1002
\end{pmatrix}
\approx
\begin{pmatrix}
0.0900,0.2447,0.6652
\end{pmatrix}.
\]</span></p>
<p>These are exactly the same weights produced mathematically by</p>
<p><span class="math display">\[
\operatorname{softmax}
\begin{pmatrix}
-2,-1,0
\end{pmatrix},
\]</span></p>
<p>because the two score vectors differ only by a common shift. The stable implementation is:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> softmax(scores):</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    scores <span class="op">=</span> np.asarray(scores, dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    shifted_scores <span class="op">=</span> scores <span class="op">-</span> np.<span class="bu">max</span>(scores)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    strengths <span class="op">=</span> np.exp(shifted_scores)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> strengths <span class="op">/</span> np.<span class="bu">sum</span>(strengths)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Using it:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>scores <span class="op">=</span> np.array([<span class="fl">1000.0</span>, <span class="fl">1001.0</span>, <span class="fl">1002.0</span>])</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>weights <span class="op">=</span> softmax(scores)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(weights)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(np.<span class="bu">sum</span>(weights))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>produces approximately</p>
<pre class="text"><code>[0.09003057 0.24472847 0.66524096]
1.0</code></pre>
<p>Subtracting the maximum is not an approximation. In exact arithmetic, it produces exactly the same softmax values. It changes the computational representation of the formula while preserving its mathematical meaning.</p>
<p>This is an important pattern in numerical programming:</p>
<p><span class="math display">\[
\boxed{
\text{Use mathematical invariance to choose a computationally safer equivalent expression.}
}
\]</span></p>
</section>
<section id="stable-softmax-with-temperature" class="level3">
<h3 class="anchored" data-anchor-id="stable-softmax-with-temperature">Stable softmax with temperature</h3>
<p>Temperature and numerical stabilization can be combined:</p>
<p><span class="math display">\[
w_i(\tau)
=
\frac{
e^{(s_i-m)/\tau}
}{
\sum_j e^{(s_j-m)/\tau}
},
\qquad
m=\max_js_j.
\]</span></p>
<p>A reusable implementation is:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> softmax(scores, temperature<span class="op">=</span><span class="fl">1.0</span>):</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    scores <span class="op">=</span> np.asarray(scores, dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> scores.ndim <span class="op">!=</span> <span class="dv">1</span>:</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"scores must be one-dimensional"</span>)</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> temperature <span class="op">&lt;=</span> <span class="dv">0</span>:</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"temperature must be positive"</span>)</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>    scaled_scores <span class="op">=</span> scores <span class="op">/</span> temperature</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>    shifted_scores <span class="op">=</span> scaled_scores <span class="op">-</span> np.<span class="bu">max</span>(scaled_scores)</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>    strengths <span class="op">=</span> np.exp(shifted_scores)</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> strengths <span class="op">/</span> np.<span class="bu">sum</span>(strengths)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The temperature must be positive. A zero temperature would require division by zero, while a negative temperature would reverse the ordering because larger scores would become smaller scaled scores.</p>
</section>
<section id="softmax-across-a-batch" class="level3">
<h3 class="anchored" data-anchor-id="softmax-across-a-batch">Softmax across a batch</h3>
<p>A machine-learning model usually processes several examples at once. Suppose a batch contains three examples and the model produces four class scores for each example:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>scores <span class="op">=</span> np.array([</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>    [<span class="fl">2.0</span>, <span class="fl">5.0</span>, <span class="fl">3.0</span>, <span class="fl">1.0</span>],</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    [<span class="fl">1.0</span>, <span class="fl">1.0</span>, <span class="fl">1.0</span>, <span class="fl">1.0</span>],</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    [<span class="fl">1000.0</span>, <span class="fl">1001.0</span>, <span class="fl">999.0</span>, <span class="fl">998.0</span>],</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The array has shape</p>
<pre class="text"><code>(3, 4)</code></pre>
<p>because it contains three rows and four columns. Each row belongs to one example, and each column belongs to one class.</p>
<p>Softmax must distribute one unit of probability across the classes of each example. Therefore, normalization must occur across the class axis, which is <code>axis=1</code>.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> softmax_rows(scores):</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>    scores <span class="op">=</span> np.asarray(scores, dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    shifted <span class="op">=</span> scores <span class="op">-</span> np.<span class="bu">max</span>(</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>        scores,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>        axis<span class="op">=</span><span class="dv">1</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>        keepdims<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>    strengths <span class="op">=</span> np.exp(shifted)</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> strengths <span class="op">/</span> np.<span class="bu">sum</span>(</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>        strengths,</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>        axis<span class="op">=</span><span class="dv">1</span>,</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>        keepdims<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The argument</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>keepdims<span class="op">=</span><span class="va">True</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>preserves the reduced axis as a dimension of length one. If <code>scores</code> has shape</p>
<pre class="text"><code>(3, 4)</code></pre>
<p>then</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>np.<span class="bu">max</span>(scores, axis<span class="op">=</span><span class="dv">1</span>, keepdims<span class="op">=</span><span class="va">True</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>has shape</p>
<pre class="text"><code>(3, 1)</code></pre>
<p>and</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>np.<span class="bu">sum</span>(strengths, axis<span class="op">=</span><span class="dv">1</span>, keepdims<span class="op">=</span><span class="va">True</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>also has shape</p>
<pre class="text"><code>(3, 1)</code></pre>
<p>Each row maximum can then be subtracted from its corresponding row, and each row total can divide its corresponding row.</p>
<p>The result satisfies</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>weights.<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>approximately equal to</p>
<pre class="text"><code>[1. 1. 1.]</code></pre>
<p>The mathematical requirement determines the axis:</p>
<p><span class="math display">\[
\boxed{
\text{Normalize across the alternatives that compete for the same unit total.}
}
\]</span></p>
<p>Choosing an axis is therefore not merely a syntactic NumPy decision. It identifies which values belong to one competition.</p>
<p>If normalization were mistakenly applied across the batch axis, the classes of different examples would compete with one another. The code might execute successfully, but the resulting weights would answer the wrong question.</p>
</section>
<section id="softmax-in-multiclass-classification" class="level3">
<h3 class="anchored" data-anchor-id="softmax-in-multiclass-classification">Softmax in multiclass classification</h3>
<p>Suppose a classifier must choose among <span class="math inline">\(n\)</span> mutually exclusive classes. For an input <span class="math inline">\(\mathbf{x}\)</span>, the model produces a score vector</p>
<p><span class="math display">\[
\mathbf{s}(\mathbf{x})
=
\begin{bmatrix}
s_1(\mathbf{x})\\
s_2(\mathbf{x})\\
\vdots\\
s_n(\mathbf{x})
\end{bmatrix}.
\]</span></p>
<p>These scores are often called logits. They may be produced by a linear transformation:</p>
<p><span class="math display">\[
\mathbf{s}
=
W\mathbf{x}+\mathbf{b}.
\]</span></p>
<p>Softmax converts the logits into normalized class outputs:</p>
<p><span class="math display">\[
p_i
=
\frac{e^{s_i}}
{\sum_je^{s_j}}.
\]</span></p>
<p>The resulting vector satisfies</p>
<p><span class="math display">\[
p_i&gt;0
\]</span></p>
<p>and</p>
<p><span class="math display">\[
\sum_ip_i=1.
\]</span></p>
<p>It can therefore be used as a categorical probability distribution within the model:</p>
<p><span class="math display">\[
\mathbf{p}
=
\operatorname{softmax}(\mathbf{s}).
\]</span></p>
<p>For example, suppose the classes are</p>
<p><span class="math display">\[
\text{cat},\qquad
\text{dog},\qquad
\text{bird}
\]</span></p>
<p>and the logits are</p>
<p><span class="math display">\[
\mathbf{s}
=
\begin{bmatrix}
-1.2\\
2.4\\
0.7
\end{bmatrix}.
\]</span></p>
<p>Softmax produces approximately</p>
<p><span class="math display">\[
\mathbf{p}
=
\begin{bmatrix}
0.022\\
0.827\\
0.151
\end{bmatrix}.
\]</span></p>
<p>The predicted class is</p>
<p><span class="math display">\[
\operatorname*{arg\,max}_i p_i
=
\operatorname*{arg\,max}_i s_i
=
\text{dog}.
\]</span></p>
<p>Softmax has not changed the winning class. It has provided a normalized distribution that can be compared with the true class during training.</p>
</section>
<section id="probability-shaped-output-is-not-automatically-trustworthy-probability" class="level3">
<h3 class="anchored" data-anchor-id="probability-shaped-output-is-not-automatically-trustworthy-probability">Probability-shaped output is not automatically trustworthy probability</h3>
<p>A softmax vector satisfies the mathematical constraints of a categorical probability distribution:</p>
<p><span class="math display">\[
p_i\geq 0,
\qquad
\sum_ip_i=1.
\]</span></p>
<p>This makes it valid as a probability-shaped allocation inside the model. However, mathematical validity should not be confused with empirical reliability.</p>
<p>Suppose a classifier assigns probability <span class="math inline">\(0.9\)</span> to its predicted class for many inputs. If the model is well calibrated, predictions made with confidence near <span class="math inline">\(0.9\)</span> should be correct approximately <span class="math inline">\(90\%\)</span> of the time.</p>
<p>Softmax alone does not guarantee this relationship.</p>
<p>A model may produce a highly concentrated output because its logits are widely separated:</p>
<p><span class="math display">\[
\operatorname{softmax}
\begin{pmatrix}
10,1,0
\end{pmatrix}
\approx
\begin{pmatrix}
0.9998,0.0001,0.0000
\end{pmatrix}.
\]</span></p>
<p>The output says that the model strongly favors the first class relative to the alternatives it considered. It does not prove that the model is correct, that the input belongs to the training distribution, or that the model’s numerical confidence is calibrated to real-world frequency.</p>
<p>Softmax guarantees structural properties:</p>
<p><span class="math display">\[
p_i&gt;0,
\qquad
\sum_ip_i=1.
\]</span></p>
<p>It does not guarantee semantic truth:</p>
<p><span class="math display">\[
p_i
=
\text{actual probability that the model is correct}.
\]</span></p>
<p>The distinction is</p>
<p><span class="math display">\[
\boxed{
\text{normalized model belief}
\neq
\text{guaranteed real-world certainty}.
}
\]</span></p>
<p>This becomes especially important in anomaly detection and safety-critical systems. A model can be confidently wrong on an unfamiliar input because softmax must distribute one unit among the available classes even when none of those classes adequately describes the observation.</p>
</section>
<section id="softmax-in-attention" class="level3">
<h3 class="anchored" data-anchor-id="softmax-in-attention">Softmax in attention</h3>
<p>Softmax also appears when a system must distribute attention across several representations.</p>
<p>Suppose a query is compared with keys to produce compatibility scores</p>
<p><span class="math display">\[
s_1,s_2,\ldots,s_n.
\]</span></p>
<p>Softmax converts these scores into attention weights:</p>
<p><span class="math display">\[
\alpha_i
=
\frac{e^{s_i}}
{\sum_je^{s_j}}.
\]</span></p>
<p>The weights are then used to combine value vectors:</p>
<p><span class="math display">\[
\mathbf{c}
=
\sum_{i=1}^{n}\alpha_i\mathbf{v}_i.
\]</span></p>
<p>The complete structure is</p>
<p><span class="math display">\[
\boxed{
\text{query--key comparisons}
\longrightarrow
\text{scores}
\longrightarrow
\text{softmax weights}
\longrightarrow
\text{weighted value combination}.
}
\]</span></p>
<p>For example, suppose the compatibility scores are</p>
<p><span class="math display">\[
\mathbf{s}
=
\begin{bmatrix}
1\\
3\\
2
\end{bmatrix}.
\]</span></p>
<p>Softmax produces approximately</p>
<p><span class="math display">\[
\boldsymbol{\alpha}
=
\begin{bmatrix}
0.090\\
0.665\\
0.245
\end{bmatrix}.
\]</span></p>
<p>The second value vector receives the greatest influence because its key received the greatest compatibility score.</p>
<p>The attention weights have the mathematical form of a probability distribution over positions, but their immediate computational meaning is contribution to the context vector. They should not automatically be interpreted as a complete causal explanation of the model’s decision.</p>
<p>Again, the same mathematical structure supports different semantic roles:</p>
<p><span class="math display">\[
\boxed{
\begin{aligned}
\text{classification softmax}
&amp;:\quad
\text{allocation across classes},\\[4pt]
\text{attention softmax}
&amp;:\quad
\text{allocation across value positions}.
\end{aligned}
}
\]</span></p>
<p>The algebra is the same. The objects receiving the allocation are different.</p>
</section>
<section id="what-softmax-preserves-and-what-it-discards" class="level3">
<h3 class="anchored" data-anchor-id="what-softmax-preserves-and-what-it-discards">What softmax preserves and what it discards</h3>
<p>Softmax preserves the ordering of scores:</p>
<p><span class="math display">\[
s_i&gt;s_j
\Longrightarrow
w_i&gt;w_j.
\]</span></p>
<p>It preserves pairwise score differences through weight ratios:</p>
<p><span class="math display">\[
\frac{w_i}{w_j}
=
e^{s_i-s_j}.
\]</span></p>
<p>It treats equal scores equally:</p>
<p><span class="math display">\[
s_i=s_j
\Longrightarrow
w_i=w_j.
\]</span></p>
<p>It ignores a common additive baseline:</p>
<p><span class="math display">\[
\operatorname{softmax}(\mathbf{s}+c\mathbf{1})
=
\operatorname{softmax}(\mathbf{s}).
\]</span></p>
<p>It produces a smooth, nonnegative, unit-sum allocation.</p>
<p>At the same time, softmax discards the absolute score level. The vectors</p>
<p><span class="math display">\[
\begin{bmatrix}
1\\
2\\
3
\end{bmatrix}
\]</span></p>
<p>and</p>
<p><span class="math display">\[
\begin{bmatrix}
101\\
102\\
103
\end{bmatrix}
\]</span></p>
<p>produce the same weights. Once the scores have been transformed into softmax weights, their common baseline cannot be recovered.</p>
<p>Softmax also compresses an unrestricted space into a constrained one:</p>
<p><span class="math display">\[
\mathbb{R}^n
\longrightarrow
\Delta^{n-1}.
\]</span></p>
<p>Because the output weights sum to one, only <span class="math inline">\(n-1\)</span> of them are independent. This corresponds to the fact that the original score vector is identifiable only up to a common additive constant.</p>
<p>Softmax therefore preserves precisely the relational information it is designed to represent while discarding a degree of absolute location that does not affect relative allocation.</p>
</section>
<section id="chapter-conclusion" class="level3">
<h3 class="anchored" data-anchor-id="chapter-conclusion">Chapter conclusion</h3>
<p>This chapter began with unrestricted scores:</p>
<p><span class="math display">\[
\mathbf{s}
=
\begin{bmatrix}
s_1\\
s_2\\
\vdots\\
s_n
\end{bmatrix}
\in\mathbb{R}^n.
\]</span></p>
<p>A score provides comparative support, but it is not yet a share. To construct a weighted combination, a mixture, a class distribution, or an attention allocation, the scores must be transformed into nonnegative weights whose total is one.</p>
<p>Ordinary normalization begins with nonnegative amounts:</p>
<p><span class="math display">\[
a_i\geq 0
\]</span></p>
<p>and divides each amount by the total:</p>
<p><span class="math display">\[
w_i
=
\frac{a_i}{\sum_ja_j}.
\]</span></p>
<p>This operation constructs shares, preserves ratios, removes common scale, and maps positive amount vectors onto the simplex. However, it cannot safely normalize arbitrary real scores because negative values may remain negative, signed totals may vanish, and cancellation may produce unstable coefficients.</p>
<p>Exponentiation solves the positivity problem:</p>
<p><span class="math display">\[
a_i=e^{s_i}&gt;0.
\]</span></p>
<p>It also preserves ordering and converts score differences into strength ratios:</p>
<p><span class="math display">\[
\frac{e^{s_i}}{e^{s_j}}
=
e^{s_i-s_j}.
\]</span></p>
<p>Normalization then produces softmax:</p>
<p><span class="math display">\[
\boxed{
w_i
=
\frac{e^{s_i}}
{\sum_je^{s_j}}.
}
\]</span></p>
<p>The resulting weights are smooth, strictly positive, and sum to one. Temperature controls how sharply the unit contribution is concentrated:</p>
<p><span class="math display">\[
w_i(\tau)
=
\frac{e^{s_i/\tau}}
{\sum_je^{s_j/\tau}}.
\]</span></p>
<p>Finally, common-shift invariance gives the numerically stable form:</p>
<p><span class="math display">\[
\boxed{
w_i
=
\frac{e^{s_i-m}}
{\sum_je^{s_j-m}},
\qquad
m=\max_js_j.
}
\]</span></p>
<p>The full conceptual journey is</p>
<p><span class="math display">\[
\boxed{
\text{unrestricted scores}
\longrightarrow
\text{positive strengths}
\longrightarrow
\text{normalized shares}
\longrightarrow
\text{soft selection or weighted combination}.
}
\]</span></p>
<p>Softmax is therefore not merely a formula used at the end of a neural network. It is a carefully structured answer to a general mathematical problem:</p>
<blockquote class="blockquote">
<p>How can unrestricted comparative scores be transformed into a smooth allocation of one whole?</p>
</blockquote>
<p>The next chapter will move from the normalization mechanism to the system that produces the scores. We will examine how inputs, parameters, dot products, and biases construct logits through expressions such as</p>
<p><span class="math display">\[
\mathbf{s}=W\mathbf{x}+\mathbf{b},
\]</span></p>
<p>and how those logits become concrete machine-learning predictions.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/hafizarslanamjad\.github\.io\/mathematical-understanding\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Articles and books by Hafiz Arslan Amjad</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://github.com/hafizarslanamjad/mathematical-understanding">
<p>Source</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>